/* combobox.c generated by valac 0.18.1, the Vala compiler
 * generated from combobox.vala, do not modify */

/* 
    Copyright 2013 Julien Lavergne <gilir@ubuntu.com>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Block4Data Block4Data;

struct _Block4Data {
	int _ref_count_;
	GtkListStore* list_store;
	GtkTreeIter iter;
	GtkComboBox* return_combobox;
	GtkBuilder* builder;
	gchar* entry_name;
};



GtkComboBox* ldefault_apps_ui_combobox_init (GtkBuilder* builder, const gchar* combobox_name, gchar** combobox_list, int combobox_list_length1, const gchar* entry_name, const gchar* by_default);
static Block4Data* block4_data_ref (Block4Data* _data4_);
static void block4_data_unref (void * _userdata_);
static void __lambda5_ (Block4Data* _data4_);
static void ___lambda5__gtk_combo_box_changed (GtkComboBox* _sender, gpointer self);
gint ldefault_apps_return_combobox_position (GtkComboBox* combo);
gchar* ldefault_apps_return_combobox_text (GtkComboBox* combo);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static Block4Data* block4_data_ref (Block4Data* _data4_) {
	g_atomic_int_inc (&_data4_->_ref_count_);
	return _data4_;
}


static void block4_data_unref (void * _userdata_) {
	Block4Data* _data4_;
	_data4_ = (Block4Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data4_->_ref_count_)) {
		_g_object_unref0 (_data4_->return_combobox);
		_g_object_unref0 (_data4_->list_store);
		_g_object_unref0 (_data4_->builder);
		_g_free0 (_data4_->entry_name);
		g_slice_free (Block4Data, _data4_);
	}
}


static void __lambda5_ (Block4Data* _data4_) {
	GValue val1 = {0};
	GValue val2 = {0};
	GtkComboBox* _tmp0_;
	GtkTreeIter _tmp1_ = {0};
	GtkListStore* _tmp2_;
	GtkTreeIter _tmp3_;
	GValue _tmp4_ = {0};
	GtkListStore* _tmp5_;
	GtkTreeIter _tmp6_;
	GValue _tmp7_ = {0};
	GValue _tmp8_;
	GValue _tmp9_;
	const gchar* _tmp10_;
	_tmp0_ = _data4_->return_combobox;
	gtk_combo_box_get_active_iter (_tmp0_, &_tmp1_);
	_data4_->iter = _tmp1_;
	_tmp2_ = _data4_->list_store;
	_tmp3_ = _data4_->iter;
	gtk_tree_model_get_value ((GtkTreeModel*) _tmp2_, &_tmp3_, 0, &_tmp4_);
	G_IS_VALUE (&val1) ? (g_value_unset (&val1), NULL) : NULL;
	val1 = _tmp4_;
	_tmp5_ = _data4_->list_store;
	_tmp6_ = _data4_->iter;
	gtk_tree_model_get_value ((GtkTreeModel*) _tmp5_, &_tmp6_, 1, &_tmp7_);
	G_IS_VALUE (&val2) ? (g_value_unset (&val2), NULL) : NULL;
	val2 = _tmp7_;
	_tmp8_ = val1;
	_tmp9_ = val2;
	g_message ("combobox.vala:99: Selection: %s, %d\n", g_value_get_string (&_tmp8_), g_value_get_int (&_tmp9_));
	_tmp10_ = _data4_->entry_name;
	if (_tmp10_ != NULL) {
		GtkBuilder* _tmp11_;
		const gchar* _tmp12_;
		GObject* _tmp13_ = NULL;
		GtkEntry* _tmp14_;
		GtkEntry* entry;
		GValue _tmp15_;
		_tmp11_ = _data4_->builder;
		_tmp12_ = _data4_->entry_name;
		_tmp13_ = gtk_builder_get_object (_tmp11_, _tmp12_);
		_tmp14_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp13_, GTK_TYPE_ENTRY) ? ((GtkEntry*) _tmp13_) : NULL);
		entry = _tmp14_;
		_tmp15_ = val2;
		if (g_value_get_int (&_tmp15_) == 99) {
			GtkEntry* _tmp16_;
			_tmp16_ = entry;
			gtk_widget_show_all ((GtkWidget*) _tmp16_);
		} else {
			GtkEntry* _tmp17_;
			_tmp17_ = entry;
			gtk_widget_hide_all ((GtkWidget*) _tmp17_);
		}
		_g_object_unref0 (entry);
	}
	G_IS_VALUE (&val2) ? (g_value_unset (&val2), NULL) : NULL;
	G_IS_VALUE (&val1) ? (g_value_unset (&val1), NULL) : NULL;
}


static void ___lambda5__gtk_combo_box_changed (GtkComboBox* _sender, gpointer self) {
	__lambda5_ (self);
}


GtkComboBox* ldefault_apps_ui_combobox_init (GtkBuilder* builder, const gchar* combobox_name, gchar** combobox_list, int combobox_list_length1, const gchar* entry_name, const gchar* by_default) {
	GtkComboBox* result = NULL;
	Block4Data* _data4_;
	GtkBuilder* _tmp0_;
	GtkBuilder* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	GtkListStore* _tmp4_;
	gint default_index;
	GtkListStore* _tmp23_;
	GtkTreeIter _tmp24_ = {0};
	GtkListStore* _tmp25_;
	GtkTreeIter _tmp26_;
	const gchar* _tmp27_;
	GtkBuilder* _tmp28_;
	const gchar* _tmp29_;
	GObject* _tmp30_ = NULL;
	GtkComboBox* _tmp31_;
	GtkComboBox* _tmp32_;
	GtkListStore* _tmp33_;
	GtkCellRendererText* _tmp34_;
	GtkCellRendererText* renderer;
	GtkComboBox* _tmp35_;
	GtkCellRendererText* _tmp36_;
	GtkComboBox* _tmp37_;
	GtkCellRendererText* _tmp38_;
	GtkComboBox* _tmp39_;
	gint _tmp40_;
	GtkComboBox* _tmp67_;
	GtkComboBox* _tmp68_;
	GtkComboBox* _tmp69_;
	g_return_val_if_fail (builder != NULL, NULL);
	g_return_val_if_fail (combobox_name != NULL, NULL);
	g_return_val_if_fail (by_default != NULL, NULL);
	_data4_ = g_slice_new0 (Block4Data);
	_data4_->_ref_count_ = 1;
	_tmp0_ = builder;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (_data4_->builder);
	_data4_->builder = _tmp1_;
	_tmp2_ = entry_name;
	_tmp3_ = g_strdup (_tmp2_);
	_g_free0 (_data4_->entry_name);
	_data4_->entry_name = _tmp3_;
	_tmp4_ = gtk_list_store_new (2, G_TYPE_STRING, G_TYPE_INT);
	_data4_->list_store = _tmp4_;
	default_index = -1;
	{
		gint a;
		a = 0;
		{
			gboolean _tmp5_;
			_tmp5_ = TRUE;
			while (TRUE) {
				gboolean _tmp6_;
				gint _tmp8_;
				gchar** _tmp9_;
				gint _tmp9__length1;
				GtkListStore* _tmp10_;
				GtkTreeIter _tmp11_ = {0};
				GtkListStore* _tmp12_;
				GtkTreeIter _tmp13_;
				gchar** _tmp14_;
				gint _tmp14__length1;
				gint _tmp15_;
				const gchar* _tmp16_;
				gint _tmp17_;
				gchar** _tmp18_;
				gint _tmp18__length1;
				gint _tmp19_;
				const gchar* _tmp20_;
				const gchar* _tmp21_;
				_tmp6_ = _tmp5_;
				if (!_tmp6_) {
					gint _tmp7_;
					_tmp7_ = a;
					a = _tmp7_ + 1;
				}
				_tmp5_ = FALSE;
				_tmp8_ = a;
				_tmp9_ = combobox_list;
				_tmp9__length1 = combobox_list_length1;
				if (!(_tmp8_ < _tmp9__length1)) {
					break;
				}
				_tmp10_ = _data4_->list_store;
				gtk_list_store_append (_tmp10_, &_tmp11_);
				_data4_->iter = _tmp11_;
				_tmp12_ = _data4_->list_store;
				_tmp13_ = _data4_->iter;
				_tmp14_ = combobox_list;
				_tmp14__length1 = combobox_list_length1;
				_tmp15_ = a;
				_tmp16_ = _tmp14_[_tmp15_];
				_tmp17_ = a;
				gtk_list_store_set (_tmp12_, &_tmp13_, 0, _tmp16_, 1, _tmp17_, -1);
				_tmp18_ = combobox_list;
				_tmp18__length1 = combobox_list_length1;
				_tmp19_ = a;
				_tmp20_ = _tmp18_[_tmp19_];
				_tmp21_ = by_default;
				if (g_strcmp0 (_tmp20_, _tmp21_) == 0) {
					gint _tmp22_;
					_tmp22_ = a;
					default_index = _tmp22_;
				}
			}
		}
	}
	_tmp23_ = _data4_->list_store;
	gtk_list_store_append (_tmp23_, &_tmp24_);
	_data4_->iter = _tmp24_;
	_tmp25_ = _data4_->list_store;
	_tmp26_ = _data4_->iter;
	gtk_list_store_set (_tmp25_, &_tmp26_, 0, "Other", 1, 99, -1);
	_tmp27_ = by_default;
	g_message ("combobox.vala:44: Defaut = %s", _tmp27_);
	_tmp28_ = _data4_->builder;
	_tmp29_ = combobox_name;
	_tmp30_ = gtk_builder_get_object (_tmp28_, _tmp29_);
	_tmp31_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp30_, GTK_TYPE_COMBO_BOX) ? ((GtkComboBox*) _tmp30_) : NULL);
	_data4_->return_combobox = _tmp31_;
	_tmp32_ = _data4_->return_combobox;
	_tmp33_ = _data4_->list_store;
	gtk_combo_box_set_model (_tmp32_, (GtkTreeModel*) _tmp33_);
	_tmp34_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
	g_object_ref_sink (_tmp34_);
	renderer = _tmp34_;
	_tmp35_ = _data4_->return_combobox;
	_tmp36_ = renderer;
	gtk_cell_layout_pack_start ((GtkCellLayout*) _tmp35_, (GtkCellRenderer*) _tmp36_, TRUE);
	_tmp37_ = _data4_->return_combobox;
	_tmp38_ = renderer;
	gtk_cell_layout_add_attribute ((GtkCellLayout*) _tmp37_, (GtkCellRenderer*) _tmp38_, "text", 0);
	_tmp39_ = _data4_->return_combobox;
	gtk_combo_box_set_active (_tmp39_, 0);
	_tmp40_ = default_index;
	if (_tmp40_ == (-1)) {
		const gchar* _tmp41_;
		const gchar* _tmp42_;
		GQuark _tmp44_ = 0U;
		static GQuark _tmp43_label0 = 0;
		static GQuark _tmp43_label1 = 0;
		static GQuark _tmp43_label2 = 0;
		g_message ("combobox.vala:57: Iter == -1");
		_tmp41_ = by_default;
		_tmp42_ = _tmp41_;
		_tmp44_ = (NULL == _tmp42_) ? 0 : g_quark_from_string (_tmp42_);
		if (_tmp44_ == ((0 != _tmp43_label0) ? _tmp43_label0 : (_tmp43_label0 = g_quark_from_static_string (NULL)))) {
			switch (0) {
				default:
				{
					GtkComboBox* _tmp45_;
					_tmp45_ = _data4_->return_combobox;
					gtk_combo_box_set_active (_tmp45_, 0);
					break;
				}
			}
		} else if (_tmp44_ == ((0 != _tmp43_label1) ? _tmp43_label1 : (_tmp43_label1 = g_quark_from_static_string ("")))) {
			switch (0) {
				default:
				{
					GtkComboBox* _tmp46_;
					_tmp46_ = _data4_->return_combobox;
					gtk_combo_box_set_active (_tmp46_, 0);
					break;
				}
			}
		} else if (_tmp44_ == ((0 != _tmp43_label2) ? _tmp43_label2 : (_tmp43_label2 = g_quark_from_static_string (" ")))) {
			switch (0) {
				default:
				{
					GtkComboBox* _tmp47_;
					_tmp47_ = _data4_->return_combobox;
					gtk_combo_box_set_active (_tmp47_, 0);
					break;
				}
			}
		} else {
			switch (0) {
				default:
				{
					GtkComboBox* _tmp48_;
					GtkTreeIter _tmp49_;
					const gchar* _tmp50_;
					_tmp48_ = _data4_->return_combobox;
					_tmp49_ = _data4_->iter;
					gtk_combo_box_set_active_iter (_tmp48_, &_tmp49_);
					_tmp50_ = _data4_->entry_name;
					if (_tmp50_ != NULL) {
						GtkBuilder* _tmp51_;
						const gchar* _tmp52_;
						GObject* _tmp53_ = NULL;
						GtkEntry* _tmp54_;
						GtkEntry* entry_default;
						GtkEntry* _tmp55_;
						const gchar* _tmp56_;
						GtkEntry* _tmp57_;
						_tmp51_ = _data4_->builder;
						_tmp52_ = _data4_->entry_name;
						_tmp53_ = gtk_builder_get_object (_tmp51_, _tmp52_);
						_tmp54_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp53_, GTK_TYPE_ENTRY) ? ((GtkEntry*) _tmp53_) : NULL);
						entry_default = _tmp54_;
						_tmp55_ = entry_default;
						_tmp56_ = by_default;
						gtk_entry_set_text (_tmp55_, _tmp56_);
						_tmp57_ = entry_default;
						gtk_widget_show_all ((GtkWidget*) _tmp57_);
						_g_object_unref0 (entry_default);
					}
					break;
				}
			}
		}
	} else {
		gint _tmp58_;
		GtkComboBox* _tmp59_;
		gint _tmp60_;
		const gchar* _tmp61_;
		_tmp58_ = default_index;
		g_message ("combobox.vala:82: Iter == %d", _tmp58_);
		_tmp59_ = _data4_->return_combobox;
		_tmp60_ = default_index;
		gtk_combo_box_set_active (_tmp59_, _tmp60_);
		_tmp61_ = _data4_->entry_name;
		if (_tmp61_ != NULL) {
			GtkBuilder* _tmp62_;
			const gchar* _tmp63_;
			GObject* _tmp64_ = NULL;
			GtkEntry* _tmp65_;
			GtkEntry* entry_default;
			GtkEntry* _tmp66_;
			_tmp62_ = _data4_->builder;
			_tmp63_ = _data4_->entry_name;
			_tmp64_ = gtk_builder_get_object (_tmp62_, _tmp63_);
			_tmp65_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp64_, GTK_TYPE_ENTRY) ? ((GtkEntry*) _tmp64_) : NULL);
			entry_default = _tmp65_;
			_tmp66_ = entry_default;
			gtk_widget_hide_all ((GtkWidget*) _tmp66_);
			_g_object_unref0 (entry_default);
		}
	}
	_tmp67_ = _data4_->return_combobox;
	g_signal_connect_data (_tmp67_, "changed", (GCallback) ___lambda5__gtk_combo_box_changed, block4_data_ref (_data4_), (GClosureNotify) block4_data_unref, 0);
	_tmp68_ = _data4_->return_combobox;
	_tmp69_ = _g_object_ref0 (_tmp68_);
	result = _tmp69_;
	_g_object_unref0 (renderer);
	block4_data_unref (_data4_);
	_data4_ = NULL;
	return result;
}


gint ldefault_apps_return_combobox_position (GtkComboBox* combo) {
	gint result = 0;
	GtkTreeIter iter = {0};
	GtkListStore* model = NULL;
	GValue value1 = {0};
	GValue value1_position = {0};
	GtkComboBox* _tmp0_;
	GtkTreeIter _tmp1_ = {0};
	GtkComboBox* _tmp2_;
	GtkTreeModel* _tmp3_ = NULL;
	GtkListStore* _tmp4_;
	GtkTreeIter _tmp5_;
	GValue _tmp6_ = {0};
	GtkTreeIter _tmp7_;
	GValue _tmp8_ = {0};
	GValue _tmp9_;
	GValue _tmp10_;
	g_return_val_if_fail (combo != NULL, 0);
	_tmp0_ = combo;
	gtk_combo_box_get_active_iter (_tmp0_, &_tmp1_);
	iter = _tmp1_;
	_tmp2_ = combo;
	_tmp3_ = gtk_combo_box_get_model (_tmp2_);
	_tmp4_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp3_, GTK_TYPE_LIST_STORE, GtkListStore));
	_g_object_unref0 (model);
	model = _tmp4_;
	_tmp5_ = iter;
	gtk_tree_model_get_value ((GtkTreeModel*) model, &_tmp5_, 0, &_tmp6_);
	G_IS_VALUE (&value1) ? (g_value_unset (&value1), NULL) : NULL;
	value1 = _tmp6_;
	_tmp7_ = iter;
	gtk_tree_model_get_value ((GtkTreeModel*) model, &_tmp7_, 1, &_tmp8_);
	G_IS_VALUE (&value1_position) ? (g_value_unset (&value1_position), NULL) : NULL;
	value1_position = _tmp8_;
	_tmp9_ = value1;
	g_message ("combobox.vala:131:  Return position for %s", g_value_get_string (&_tmp9_));
	_tmp10_ = value1_position;
	result = g_value_get_int (&_tmp10_);
	G_IS_VALUE (&value1_position) ? (g_value_unset (&value1_position), NULL) : NULL;
	G_IS_VALUE (&value1) ? (g_value_unset (&value1), NULL) : NULL;
	_g_object_unref0 (model);
	return result;
}


gchar* ldefault_apps_return_combobox_text (GtkComboBox* combo) {
	gchar* result = NULL;
	GtkTreeIter iter = {0};
	GtkListStore* model = NULL;
	GValue value1 = {0};
	GtkComboBox* _tmp0_;
	GtkTreeIter _tmp1_ = {0};
	GtkComboBox* _tmp2_;
	GtkTreeModel* _tmp3_ = NULL;
	GtkListStore* _tmp4_;
	GtkTreeIter _tmp5_;
	GValue _tmp6_ = {0};
	GValue _tmp7_;
	GValue _tmp8_;
	gchar* _tmp9_;
	g_return_val_if_fail (combo != NULL, NULL);
	_tmp0_ = combo;
	gtk_combo_box_get_active_iter (_tmp0_, &_tmp1_);
	iter = _tmp1_;
	_tmp2_ = combo;
	_tmp3_ = gtk_combo_box_get_model (_tmp2_);
	_tmp4_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp3_, GTK_TYPE_LIST_STORE, GtkListStore));
	_g_object_unref0 (model);
	model = _tmp4_;
	_tmp5_ = iter;
	gtk_tree_model_get_value ((GtkTreeModel*) model, &_tmp5_, 0, &_tmp6_);
	G_IS_VALUE (&value1) ? (g_value_unset (&value1), NULL) : NULL;
	value1 = _tmp6_;
	_tmp7_ = value1;
	g_message ("combobox.vala:146:  Return value for %s", g_value_get_string (&_tmp7_));
	_tmp8_ = value1;
	_tmp9_ = g_strdup (g_value_get_string (&_tmp8_));
	result = _tmp9_;
	G_IS_VALUE (&value1) ? (g_value_unset (&value1), NULL) : NULL;
	_g_object_unref0 (model);
	return result;
}



