/* autostart.c generated by valac 0.18.1, the Vala compiler
 * generated from autostart.vala, do not modify */

/* 
 *      Copyright 2011 Julien Lavergne <gilir@ubuntu.com>
 *
 *      This program is free software; you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published by
 *      the Free Software Foundation; either version 2 of the License, or
 *      (at your option) any later version.
 *
 *      This program is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 *
 *      You should have received a copy of the GNU General Public License
 *      along with this program; if not, write to the Free Software
 *      Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 *      MA 02110-1301, USA.
 */

#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>


#define LXSESSION_TYPE_LXSESSION_AUTOSTART_CONFIG (lxsession_lxsession_autostart_config_get_type ())
#define LXSESSION_LXSESSION_AUTOSTART_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_LXSESSION_AUTOSTART_CONFIG, LxsessionLxsessionAutostartConfig))
#define LXSESSION_LXSESSION_AUTOSTART_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_LXSESSION_AUTOSTART_CONFIG, LxsessionLxsessionAutostartConfigClass))
#define LXSESSION_IS_LXSESSION_AUTOSTART_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_LXSESSION_AUTOSTART_CONFIG))
#define LXSESSION_IS_LXSESSION_AUTOSTART_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_LXSESSION_AUTOSTART_CONFIG))
#define LXSESSION_LXSESSION_AUTOSTART_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_LXSESSION_AUTOSTART_CONFIG, LxsessionLxsessionAutostartConfigClass))

typedef struct _LxsessionLxsessionAutostartConfig LxsessionLxsessionAutostartConfig;
typedef struct _LxsessionLxsessionAutostartConfigClass LxsessionLxsessionAutostartConfigClass;
typedef struct _LxsessionLxsessionAutostartConfigPrivate LxsessionLxsessionAutostartConfigPrivate;

#define LXSESSION_TYPE_APP_TYPE (lxsession_app_type_get_type ())
typedef struct _LxsessionAppType LxsessionAppType;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _lxsession_app_type_free0(var) ((var == NULL) ? NULL : (var = (lxsession_app_type_free (var), NULL)))

#define LXSESSION_TYPE_APP_OBJECT (lxsession_app_object_get_type ())
#define LXSESSION_APP_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_APP_OBJECT, LxsessionAppObject))
#define LXSESSION_APP_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_APP_OBJECT, LxsessionAppObjectClass))
#define LXSESSION_IS_APP_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_APP_OBJECT))
#define LXSESSION_IS_APP_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_APP_OBJECT))
#define LXSESSION_APP_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_APP_OBJECT, LxsessionAppObjectClass))

typedef struct _LxsessionAppObject LxsessionAppObject;
typedef struct _LxsessionAppObjectClass LxsessionAppObjectClass;

#define LXSESSION_TYPE_GENERIC_APP_OBJECT (lxsession_generic_app_object_get_type ())
#define LXSESSION_GENERIC_APP_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_GENERIC_APP_OBJECT, LxsessionGenericAppObject))
#define LXSESSION_GENERIC_APP_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_GENERIC_APP_OBJECT, LxsessionGenericAppObjectClass))
#define LXSESSION_IS_GENERIC_APP_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_GENERIC_APP_OBJECT))
#define LXSESSION_IS_GENERIC_APP_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_GENERIC_APP_OBJECT))
#define LXSESSION_GENERIC_APP_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_GENERIC_APP_OBJECT, LxsessionGenericAppObjectClass))

typedef struct _LxsessionGenericAppObject LxsessionGenericAppObject;
typedef struct _LxsessionGenericAppObjectClass LxsessionGenericAppObjectClass;

struct _LxsessionLxsessionAutostartConfig {
	GObject parent_instance;
	LxsessionLxsessionAutostartConfigPrivate * priv;
};

struct _LxsessionLxsessionAutostartConfigClass {
	GObjectClass parent_class;
};

struct _LxsessionAppType {
	gchar* name;
	gchar** command;
	gint command_length1;
	gboolean guard;
	gchar* application_type;
};

struct _LxsessionLxsessionAutostartConfigPrivate {
	GeeArrayList* stock_list;
};


static gpointer lxsession_lxsession_autostart_config_parent_class = NULL;

GType lxsession_lxsession_autostart_config_get_type (void) G_GNUC_CONST;
GType lxsession_app_type_get_type (void) G_GNUC_CONST;
LxsessionAppType* lxsession_app_type_dup (const LxsessionAppType* self);
void lxsession_app_type_free (LxsessionAppType* self);
void lxsession_app_type_copy (const LxsessionAppType* self, LxsessionAppType* dest);
void lxsession_app_type_destroy (LxsessionAppType* self);
#define LXSESSION_LXSESSION_AUTOSTART_CONFIG_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), LXSESSION_TYPE_LXSESSION_AUTOSTART_CONFIG, LxsessionLxsessionAutostartConfigPrivate))
enum  {
	LXSESSION_LXSESSION_AUTOSTART_CONFIG_DUMMY_PROPERTY
};
LxsessionLxsessionAutostartConfig* lxsession_lxsession_autostart_config_new (void);
LxsessionLxsessionAutostartConfig* lxsession_lxsession_autostart_config_construct (GType object_type);
GeeArrayList* lxsession_lxsession_autostart_config_load_autostart_file (LxsessionLxsessionAutostartConfig* self);
gchar* lxsession_get_config_path (const gchar* conf_file);
static gchar** _vala_array_dup3 (gchar** self, int length);
static gchar** _vala_array_dup4 (gchar** self, int length);
void lxsession_lxsession_autostart_config_start_applications (LxsessionLxsessionAutostartConfig* self);
LxsessionGenericAppObject* lxsession_generic_app_object_new (LxsessionAppType* app_type);
LxsessionGenericAppObject* lxsession_generic_app_object_construct (GType object_type, LxsessionAppType* app_type);
GType lxsession_app_object_get_type (void) G_GNUC_CONST;
GType lxsession_generic_app_object_get_type (void) G_GNUC_CONST;
void lxsession_app_object_launch (LxsessionAppObject* self);
void lxsession_lxsession_autostart_config_check_dupplicate (LxsessionLxsessionAutostartConfig* self);
static void lxsession_lxsession_autostart_config_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


LxsessionLxsessionAutostartConfig* lxsession_lxsession_autostart_config_construct (GType object_type) {
	LxsessionLxsessionAutostartConfig * self = NULL;
	GeeArrayList* _tmp0_ = NULL;
	self = (LxsessionLxsessionAutostartConfig*) g_object_new (object_type, NULL);
	_tmp0_ = lxsession_lxsession_autostart_config_load_autostart_file (self);
	_g_object_unref0 (self->priv->stock_list);
	self->priv->stock_list = _tmp0_;
	return self;
}


LxsessionLxsessionAutostartConfig* lxsession_lxsession_autostart_config_new (void) {
	return lxsession_lxsession_autostart_config_construct (LXSESSION_TYPE_LXSESSION_AUTOSTART_CONFIG);
}


static gchar* string_slice (const gchar* self, glong start, glong end) {
	gchar* result = NULL;
	gint _tmp0_;
	gint _tmp1_;
	glong string_length;
	glong _tmp2_;
	glong _tmp5_;
	gboolean _tmp8_ = FALSE;
	glong _tmp9_;
	gboolean _tmp12_;
	gboolean _tmp13_ = FALSE;
	glong _tmp14_;
	gboolean _tmp17_;
	glong _tmp18_;
	glong _tmp19_;
	glong _tmp20_;
	glong _tmp21_;
	glong _tmp22_;
	gchar* _tmp23_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	string_length = (glong) _tmp1_;
	_tmp2_ = start;
	if (_tmp2_ < ((glong) 0)) {
		glong _tmp3_;
		glong _tmp4_;
		_tmp3_ = string_length;
		_tmp4_ = start;
		start = _tmp3_ + _tmp4_;
	}
	_tmp5_ = end;
	if (_tmp5_ < ((glong) 0)) {
		glong _tmp6_;
		glong _tmp7_;
		_tmp6_ = string_length;
		_tmp7_ = end;
		end = _tmp6_ + _tmp7_;
	}
	_tmp9_ = start;
	if (_tmp9_ >= ((glong) 0)) {
		glong _tmp10_;
		glong _tmp11_;
		_tmp10_ = start;
		_tmp11_ = string_length;
		_tmp8_ = _tmp10_ <= _tmp11_;
	} else {
		_tmp8_ = FALSE;
	}
	_tmp12_ = _tmp8_;
	g_return_val_if_fail (_tmp12_, NULL);
	_tmp14_ = end;
	if (_tmp14_ >= ((glong) 0)) {
		glong _tmp15_;
		glong _tmp16_;
		_tmp15_ = end;
		_tmp16_ = string_length;
		_tmp13_ = _tmp15_ <= _tmp16_;
	} else {
		_tmp13_ = FALSE;
	}
	_tmp17_ = _tmp13_;
	g_return_val_if_fail (_tmp17_, NULL);
	_tmp18_ = start;
	_tmp19_ = end;
	g_return_val_if_fail (_tmp18_ <= _tmp19_, NULL);
	_tmp20_ = start;
	_tmp21_ = end;
	_tmp22_ = start;
	_tmp23_ = g_strndup (((gchar*) self) + _tmp20_, (gsize) (_tmp21_ - _tmp22_));
	result = _tmp23_;
	return result;
}


static gchar** _vala_array_dup3 (gchar** self, int length) {
	gchar** result;
	int i;
	result = g_new0 (gchar*, length + 1);
	for (i = 0; i < length; i++) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


static gchar** _vala_array_dup4 (gchar** self, int length) {
	gchar** result;
	int i;
	result = g_new0 (gchar*, length + 1);
	for (i = 0; i < length; i++) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


GeeArrayList* lxsession_lxsession_autostart_config_load_autostart_file (LxsessionLxsessionAutostartConfig* self) {
	GeeArrayList* result = NULL;
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	GFile* _tmp2_ = NULL;
	GFile* _tmp3_;
	GFile* file;
	GeeArrayList* _tmp4_;
	GeeArrayList* app_list;
	GFile* _tmp5_;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_;
	GFile* _tmp8_;
	gboolean _tmp9_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = lxsession_get_config_path ("autostart");
	_tmp1_ = _tmp0_;
	_tmp2_ = g_file_new_for_path (_tmp1_);
	_tmp3_ = _tmp2_;
	_g_free0 (_tmp1_);
	file = _tmp3_;
	_tmp4_ = gee_array_list_new (LXSESSION_TYPE_APP_TYPE, (GBoxedCopyFunc) lxsession_app_type_dup, lxsession_app_type_free, NULL);
	app_list = _tmp4_;
	_tmp5_ = file;
	_tmp6_ = g_file_get_path (_tmp5_);
	_tmp7_ = _tmp6_;
	g_message ("autostart.vala:44: Autostart path : %s", _tmp7_);
	_g_free0 (_tmp7_);
	_tmp8_ = file;
	_tmp9_ = g_file_query_exists (_tmp8_, NULL);
	if (_tmp9_) {
		{
			GFile* _tmp10_;
			GFileInputStream* _tmp11_ = NULL;
			GFileInputStream* _tmp12_;
			GFileInputStream* _tmp13_;
			GDataInputStream* _tmp14_;
			GDataInputStream* _tmp15_;
			GDataInputStream* dis;
			gchar* line = NULL;
			_tmp10_ = file;
			_tmp11_ = g_file_read (_tmp10_, NULL, &_inner_error_);
			_tmp12_ = _tmp11_;
			if (_inner_error_ != NULL) {
				goto __catch5_g_error;
			}
			_tmp13_ = _tmp12_;
			_tmp14_ = g_data_input_stream_new ((GInputStream*) _tmp13_);
			_tmp15_ = _tmp14_;
			_g_object_unref0 (_tmp13_);
			dis = _tmp15_;
			while (TRUE) {
				GDataInputStream* _tmp16_;
				gchar* _tmp17_ = NULL;
				gchar* _tmp18_;
				const gchar* _tmp19_;
				const gchar* _tmp20_;
				gchar* _tmp21_ = NULL;
				gchar* first;
				const gchar* _tmp22_;
				const gchar* _tmp23_;
				GQuark _tmp25_ = 0U;
				static GQuark _tmp24_label0 = 0;
				static GQuark _tmp24_label1 = 0;
				_tmp16_ = dis;
				_tmp17_ = g_data_input_stream_read_line (_tmp16_, NULL, NULL, &_inner_error_);
				_tmp18_ = _tmp17_;
				if (_inner_error_ != NULL) {
					_g_free0 (line);
					_g_object_unref0 (dis);
					goto __catch5_g_error;
				}
				_g_free0 (line);
				line = _tmp18_;
				_tmp19_ = line;
				if (!(_tmp19_ != NULL)) {
					break;
				}
				_tmp20_ = line;
				_tmp21_ = string_slice (_tmp20_, (glong) 0, (glong) 1);
				first = _tmp21_;
				_tmp22_ = first;
				_tmp23_ = _tmp22_;
				_tmp25_ = (NULL == _tmp23_) ? 0 : g_quark_from_string (_tmp23_);
				if (_tmp25_ == ((0 != _tmp24_label0) ? _tmp24_label0 : (_tmp24_label0 = g_quark_from_static_string ("@")))) {
					switch (0) {
						default:
						{
							GString* _tmp26_;
							GString* builder;
							GString* _tmp27_;
							const gchar* _tmp28_;
							GString* _tmp29_;
							GString* _tmp30_;
							const gchar* _tmp31_;
							gchar** _tmp32_;
							gchar** _tmp33_ = NULL;
							gchar** command;
							gint command_length1;
							gint _command_size_;
							gchar** _tmp34_;
							gint _tmp34__length1;
							const gchar* _tmp35_;
							gchar* _tmp36_;
							gchar** _tmp37_;
							gint _tmp37__length1;
							gchar** _tmp38_;
							gint _tmp38__length1;
							gchar* _tmp39_;
							LxsessionAppType _tmp40_ = {0};
							LxsessionAppType app;
							GeeArrayList* _tmp41_;
							LxsessionAppType _tmp42_;
							_tmp26_ = g_string_new ("");
							builder = _tmp26_;
							_tmp27_ = builder;
							_tmp28_ = line;
							g_string_append (_tmp27_, _tmp28_);
							_tmp29_ = builder;
							g_string_erase (_tmp29_, (gssize) 0, (gssize) 1);
							_tmp30_ = builder;
							_tmp31_ = _tmp30_->str;
							_tmp33_ = _tmp32_ = g_strsplit_set (_tmp31_, " ", 0);
							command = _tmp33_;
							command_length1 = _vala_array_length (_tmp32_);
							_command_size_ = command_length1;
							_tmp34_ = command;
							_tmp34__length1 = command_length1;
							_tmp35_ = _tmp34_[0];
							_tmp36_ = g_strdup (_tmp35_);
							_tmp37_ = command;
							_tmp37__length1 = command_length1;
							_tmp38_ = (_tmp37_ != NULL) ? _vala_array_dup3 (_tmp37_, _tmp37__length1) : ((gpointer) _tmp37_);
							_tmp38__length1 = _tmp37__length1;
							_tmp39_ = g_strdup ("");
							_g_free0 (_tmp40_.name);
							_tmp40_.name = _tmp36_;
							_tmp40_.command = (_vala_array_free (_tmp40_.command, _tmp40_.command_length1, (GDestroyNotify) g_free), NULL);
							_tmp40_.command = _tmp38_;
							_tmp40_.command_length1 = _tmp38__length1;
							_tmp40_.guard = TRUE;
							_g_free0 (_tmp40_.application_type);
							_tmp40_.application_type = _tmp39_;
							app = _tmp40_;
							_tmp41_ = app_list;
							_tmp42_ = app;
							gee_abstract_collection_add ((GeeAbstractCollection*) _tmp41_, &_tmp42_);
							lxsession_app_type_destroy (&app);
							command = (_vala_array_free (command, command_length1, (GDestroyNotify) g_free), NULL);
							_g_string_free0 (builder);
							break;
						}
					}
				} else if (_tmp25_ == ((0 != _tmp24_label1) ? _tmp24_label1 : (_tmp24_label1 = g_quark_from_static_string ("#")))) {
					switch (0) {
						default:
						{
							break;
						}
					}
				} else {
					switch (0) {
						default:
						{
							const gchar* _tmp43_;
							gchar** _tmp44_;
							gchar** _tmp45_ = NULL;
							gchar** command;
							gint command_length1;
							gint _command_size_;
							gchar** _tmp46_;
							gint _tmp46__length1;
							const gchar* _tmp47_;
							gchar* _tmp48_;
							gchar** _tmp49_;
							gint _tmp49__length1;
							gchar** _tmp50_;
							gint _tmp50__length1;
							gchar* _tmp51_;
							LxsessionAppType _tmp52_ = {0};
							LxsessionAppType app;
							GeeArrayList* _tmp53_;
							LxsessionAppType _tmp54_;
							_tmp43_ = line;
							_tmp45_ = _tmp44_ = g_strsplit_set (_tmp43_, " ", 0);
							command = _tmp45_;
							command_length1 = _vala_array_length (_tmp44_);
							_command_size_ = command_length1;
							_tmp46_ = command;
							_tmp46__length1 = command_length1;
							_tmp47_ = _tmp46_[0];
							_tmp48_ = g_strdup (_tmp47_);
							_tmp49_ = command;
							_tmp49__length1 = command_length1;
							_tmp50_ = (_tmp49_ != NULL) ? _vala_array_dup4 (_tmp49_, _tmp49__length1) : ((gpointer) _tmp49_);
							_tmp50__length1 = _tmp49__length1;
							_tmp51_ = g_strdup ("");
							_g_free0 (_tmp52_.name);
							_tmp52_.name = _tmp48_;
							_tmp52_.command = (_vala_array_free (_tmp52_.command, _tmp52_.command_length1, (GDestroyNotify) g_free), NULL);
							_tmp52_.command = _tmp50_;
							_tmp52_.command_length1 = _tmp50__length1;
							_tmp52_.guard = FALSE;
							_g_free0 (_tmp52_.application_type);
							_tmp52_.application_type = _tmp51_;
							app = _tmp52_;
							_tmp53_ = app_list;
							_tmp54_ = app;
							gee_abstract_collection_add ((GeeAbstractCollection*) _tmp53_, &_tmp54_);
							lxsession_app_type_destroy (&app);
							command = (_vala_array_free (command, command_length1, (GDestroyNotify) g_free), NULL);
							break;
						}
					}
				}
				_g_free0 (first);
			}
			_g_free0 (line);
			_g_object_unref0 (dis);
		}
		goto __finally5;
		__catch5_g_error:
		{
			GError* e = NULL;
			const gchar* _tmp55_;
			e = _inner_error_;
			_inner_error_ = NULL;
			_tmp55_ = e->message;
			g_error ("autostart.vala:77: %s", _tmp55_);
			_g_error_free0 (e);
		}
		__finally5:
		if (_inner_error_ != NULL) {
			_g_object_unref0 (app_list);
			_g_object_unref0 (file);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	result = app_list;
	_g_object_unref0 (file);
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void lxsession_lxsession_autostart_config_start_applications (LxsessionLxsessionAutostartConfig* self) {
	g_return_if_fail (self != NULL);
	{
		GeeArrayList* _tmp0_;
		GeeArrayList* _tmp1_;
		GeeArrayList* _s_list;
		GeeArrayList* _tmp2_;
		gint _tmp3_;
		gint _tmp4_;
		gint _s_size;
		gint _s_index;
		_tmp0_ = self->priv->stock_list;
		_tmp1_ = _g_object_ref0 (_tmp0_);
		_s_list = _tmp1_;
		_tmp2_ = _s_list;
		_tmp3_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_s_size = _tmp4_;
		_s_index = -1;
		while (TRUE) {
			gint _tmp5_;
			gint _tmp6_;
			gint _tmp7_;
			GeeArrayList* _tmp8_;
			gint _tmp9_;
			gpointer _tmp10_ = NULL;
			LxsessionAppType* _tmp11_;
			LxsessionAppType _tmp12_ = {0};
			LxsessionAppType _tmp13_;
			LxsessionAppType s;
			LxsessionAppType _tmp14_;
			LxsessionGenericAppObject* _tmp15_;
			LxsessionGenericAppObject* launch_app;
			LxsessionGenericAppObject* _tmp16_;
			_tmp5_ = _s_index;
			_s_index = _tmp5_ + 1;
			_tmp6_ = _s_index;
			_tmp7_ = _s_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _s_list;
			_tmp9_ = _s_index;
			_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
			_tmp11_ = (LxsessionAppType*) _tmp10_;
			lxsession_app_type_copy (_tmp11_, &_tmp12_);
			_tmp13_ = _tmp12_;
			_lxsession_app_type_free0 (_tmp11_);
			s = _tmp13_;
			_tmp14_ = s;
			_tmp15_ = lxsession_generic_app_object_new (&_tmp14_);
			launch_app = _tmp15_;
			_tmp16_ = launch_app;
			lxsession_app_object_launch ((LxsessionAppObject*) _tmp16_);
			_g_object_unref0 (launch_app);
			lxsession_app_type_destroy (&s);
		}
		_g_object_unref0 (_s_list);
	}
}


void lxsession_lxsession_autostart_config_check_dupplicate (LxsessionLxsessionAutostartConfig* self) {
	g_return_if_fail (self != NULL);
}


static void lxsession_lxsession_autostart_config_class_init (LxsessionLxsessionAutostartConfigClass * klass) {
	lxsession_lxsession_autostart_config_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (LxsessionLxsessionAutostartConfigPrivate));
	G_OBJECT_CLASS (klass)->finalize = lxsession_lxsession_autostart_config_finalize;
}


static void lxsession_lxsession_autostart_config_instance_init (LxsessionLxsessionAutostartConfig * self) {
	self->priv = LXSESSION_LXSESSION_AUTOSTART_CONFIG_GET_PRIVATE (self);
}


static void lxsession_lxsession_autostart_config_finalize (GObject* obj) {
	LxsessionLxsessionAutostartConfig * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, LXSESSION_TYPE_LXSESSION_AUTOSTART_CONFIG, LxsessionLxsessionAutostartConfig);
	_g_object_unref0 (self->priv->stock_list);
	G_OBJECT_CLASS (lxsession_lxsession_autostart_config_parent_class)->finalize (obj);
}


GType lxsession_lxsession_autostart_config_get_type (void) {
	static volatile gsize lxsession_lxsession_autostart_config_type_id__volatile = 0;
	if (g_once_init_enter (&lxsession_lxsession_autostart_config_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LxsessionLxsessionAutostartConfigClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) lxsession_lxsession_autostart_config_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LxsessionLxsessionAutostartConfig), 0, (GInstanceInitFunc) lxsession_lxsession_autostart_config_instance_init, NULL };
		GType lxsession_lxsession_autostart_config_type_id;
		lxsession_lxsession_autostart_config_type_id = g_type_register_static (G_TYPE_OBJECT, "LxsessionLxsessionAutostartConfig", &g_define_type_info, 0);
		g_once_init_leave (&lxsession_lxsession_autostart_config_type_id__volatile, lxsession_lxsession_autostart_config_type_id);
	}
	return lxsession_lxsession_autostart_config_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



