/* conffiles.c generated by valac 0.18.1, the Vala compiler
 * generated from conffiles.vala, do not modify */

/* 
 *      Copyright 2012 Julien Lavergne <gilir@ubuntu.com>
 *
 *      This program is free software; you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published by
 *      the Free Software Foundation; either version 2 of the License, or
 *      (at your option) any later version.
 *
 *      This program is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 *
 *      You should have received a copy of the GNU General Public License
 *      along with this program; if not, write to the Free Software
 *      Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 *      MA 02110-1301, USA.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>


#define LXSESSION_TYPE_CONFFILES_OBJECT (lxsession_conffiles_object_get_type ())
#define LXSESSION_CONFFILES_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_CONFFILES_OBJECT, LxsessionConffilesObject))
#define LXSESSION_CONFFILES_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_CONFFILES_OBJECT, LxsessionConffilesObjectClass))
#define LXSESSION_IS_CONFFILES_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_CONFFILES_OBJECT))
#define LXSESSION_IS_CONFFILES_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_CONFFILES_OBJECT))
#define LXSESSION_CONFFILES_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_CONFFILES_OBJECT, LxsessionConffilesObjectClass))

typedef struct _LxsessionConffilesObject LxsessionConffilesObject;
typedef struct _LxsessionConffilesObjectClass LxsessionConffilesObjectClass;
typedef struct _LxsessionConffilesObjectPrivate LxsessionConffilesObjectPrivate;
#define _g_key_file_free0(var) ((var == NULL) ? NULL : (var = (g_key_file_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _LxsessionConffilesObject {
	GObject parent_instance;
	LxsessionConffilesObjectPrivate * priv;
	GKeyFile* kf;
	gchar* Openbox_dest;
	gchar* Qt_dest;
	gchar* Leafpad_dest;
	gchar* Lxterminal_dest;
	gchar* XScreensaver_dest;
	gchar* libfm_dest;
};

struct _LxsessionConffilesObjectClass {
	GObjectClass parent_class;
};


static gpointer lxsession_conffiles_object_parent_class = NULL;

GType lxsession_conffiles_object_get_type (void) G_GNUC_CONST;
enum  {
	LXSESSION_CONFFILES_OBJECT_DUMMY_PROPERTY
};
LxsessionConffilesObject* lxsession_conffiles_object_new (const gchar* conffiles_conf);
LxsessionConffilesObject* lxsession_conffiles_object_construct (GType object_type, const gchar* conffiles_conf);
GKeyFile* lxsession_load_keyfile (const gchar* config_path);
void lxsession_conffiles_object_copy_file (LxsessionConffilesObject* self, const gchar* source_path, const gchar* dest_path);
gchar* lxsession_conffiles_object_load_dest_path (LxsessionConffilesObject* self, const gchar* config_type);
void lxsession_conffiles_object_copy_conf (LxsessionConffilesObject* self, const gchar* config_type, const gchar* source_path);
void lxsession_conffiles_object_apply (LxsessionConffilesObject* self);
static void lxsession_conffiles_object_finalize (GObject* obj);


LxsessionConffilesObject* lxsession_conffiles_object_construct (GType object_type, const gchar* conffiles_conf) {
	LxsessionConffilesObject * self = NULL;
	const gchar* _tmp0_;
	GKeyFile* _tmp1_ = NULL;
	g_return_val_if_fail (conffiles_conf != NULL, NULL);
	self = (LxsessionConffilesObject*) g_object_new (object_type, NULL);
	_tmp0_ = conffiles_conf;
	_tmp1_ = lxsession_load_keyfile (_tmp0_);
	_g_key_file_free0 (self->kf);
	self->kf = _tmp1_;
	return self;
}


LxsessionConffilesObject* lxsession_conffiles_object_new (const gchar* conffiles_conf) {
	return lxsession_conffiles_object_construct (LXSESSION_TYPE_CONFFILES_OBJECT, conffiles_conf);
}


void lxsession_conffiles_object_copy_file (LxsessionConffilesObject* self, const gchar* source_path, const gchar* dest_path) {
	const gchar* _tmp0_;
	GFile* _tmp1_ = NULL;
	GFile* source_file;
	const gchar* _tmp2_;
	GFile* _tmp3_ = NULL;
	GFile* dest_file;
	GFile* _tmp4_;
	gboolean _tmp5_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (source_path != NULL);
	g_return_if_fail (dest_path != NULL);
	_tmp0_ = source_path;
	_tmp1_ = g_file_new_for_path (_tmp0_);
	source_file = _tmp1_;
	_tmp2_ = dest_path;
	_tmp3_ = g_file_new_for_path (_tmp2_);
	dest_file = _tmp3_;
	_tmp4_ = dest_file;
	_tmp5_ = g_file_query_exists (_tmp4_, NULL);
	if (!_tmp5_) {
		{
			GFile* _tmp6_;
			GFile* _tmp7_;
			_tmp6_ = source_file;
			_tmp7_ = dest_file;
			g_file_copy (_tmp6_, _tmp7_, G_FILE_COPY_NONE, NULL, NULL, NULL, &_inner_error_);
			if (_inner_error_ != NULL) {
				goto __catch6_g_error;
			}
		}
		goto __finally6;
		__catch6_g_error:
		{
			GError* err = NULL;
			GError* _tmp8_;
			const gchar* _tmp9_;
			err = _inner_error_;
			_inner_error_ = NULL;
			_tmp8_ = err;
			_tmp9_ = _tmp8_->message;
			g_message ("conffiles.vala:54: %s", _tmp9_);
			_g_error_free0 (err);
		}
		__finally6:
		if (_inner_error_ != NULL) {
			_g_object_unref0 (dest_file);
			_g_object_unref0 (source_file);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	_g_object_unref0 (dest_file);
	_g_object_unref0 (source_file);
}


gchar* lxsession_conffiles_object_load_dest_path (LxsessionConffilesObject* self, const gchar* config_type) {
	gchar* result = NULL;
	gchar* source = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (config_type != NULL, NULL);
	{
		GKeyFile* _tmp0_;
		const gchar* _tmp1_;
		gchar* _tmp2_ = NULL;
		gchar* _tmp3_;
		_tmp0_ = self->kf;
		_tmp1_ = config_type;
		_tmp2_ = g_key_file_get_value (_tmp0_, _tmp1_, "source", &_inner_error_);
		_tmp3_ = _tmp2_;
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_KEY_FILE_ERROR) {
				goto __catch7_g_key_file_error;
			}
			_g_free0 (source);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_g_free0 (source);
		source = _tmp3_;
		result = source;
		return result;
	}
	goto __finally7;
	__catch7_g_key_file_error:
	{
		GError* err = NULL;
		GError* _tmp4_;
		const gchar* _tmp5_;
		gchar* _tmp6_;
		err = _inner_error_;
		_inner_error_ = NULL;
		_tmp4_ = err;
		_tmp5_ = _tmp4_->message;
		g_message ("conffiles.vala:68: %s", _tmp5_);
		_tmp6_ = g_strdup ("");
		result = _tmp6_;
		_g_error_free0 (err);
		_g_free0 (source);
		return result;
	}
	__finally7:
	_g_free0 (source);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return NULL;
}


void lxsession_conffiles_object_copy_conf (LxsessionConffilesObject* self, const gchar* config_type, const gchar* source_path) {
	GKeyFile* _tmp0_;
	const gchar* _tmp1_;
	gboolean _tmp2_ = FALSE;
	g_return_if_fail (self != NULL);
	g_return_if_fail (config_type != NULL);
	g_return_if_fail (source_path != NULL);
	_tmp0_ = self->kf;
	_tmp1_ = config_type;
	_tmp2_ = g_key_file_has_group (_tmp0_, _tmp1_);
	if (_tmp2_) {
		const gchar* _tmp3_;
		const gchar* _tmp4_;
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_;
		_tmp3_ = source_path;
		_tmp4_ = config_type;
		_tmp5_ = lxsession_conffiles_object_load_dest_path (self, _tmp4_);
		_tmp6_ = _tmp5_;
		lxsession_conffiles_object_copy_file (self, _tmp3_, _tmp6_);
		_g_free0 (_tmp6_);
	}
}


void lxsession_conffiles_object_apply (LxsessionConffilesObject* self) {
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->Openbox_dest;
	lxsession_conffiles_object_copy_conf (self, "Openbox", _tmp0_);
	_tmp1_ = self->Qt_dest;
	lxsession_conffiles_object_copy_conf (self, "Qt", _tmp1_);
	_tmp2_ = self->Leafpad_dest;
	lxsession_conffiles_object_copy_conf (self, "Leafpad", _tmp2_);
	_tmp3_ = self->Lxterminal_dest;
	lxsession_conffiles_object_copy_conf (self, "Lxterminal", _tmp3_);
	_tmp4_ = self->XScreensaver_dest;
	lxsession_conffiles_object_copy_conf (self, "XScreensaver", _tmp4_);
	_tmp5_ = self->libfm_dest;
	lxsession_conffiles_object_copy_conf (self, "libfm", _tmp5_);
}


static void lxsession_conffiles_object_class_init (LxsessionConffilesObjectClass * klass) {
	lxsession_conffiles_object_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = lxsession_conffiles_object_finalize;
}


static void lxsession_conffiles_object_instance_init (LxsessionConffilesObject * self) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	const gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	_tmp0_ = g_get_user_config_dir ();
	_tmp1_ = g_build_filename (_tmp0_, "openbox", "lubuntu.xml", NULL);
	self->Openbox_dest = _tmp1_;
	_tmp2_ = g_get_user_config_dir ();
	_tmp3_ = g_build_filename (_tmp2_, "Trolltech.conf", NULL);
	self->Qt_dest = _tmp3_;
	_tmp4_ = g_get_user_config_dir ();
	_tmp5_ = g_build_filename (_tmp4_, "leafpad", "leafpadrc", NULL);
	self->Leafpad_dest = _tmp5_;
	_tmp6_ = g_get_user_config_dir ();
	_tmp7_ = g_build_filename (_tmp6_, "lxterminal", "lxterminal.conf", NULL);
	self->Lxterminal_dest = _tmp7_;
	_tmp8_ = g_get_home_dir ();
	_tmp9_ = g_build_filename (_tmp8_, ".xscreensaver", NULL);
	self->XScreensaver_dest = _tmp9_;
	_tmp10_ = g_get_user_config_dir ();
	_tmp11_ = g_build_filename (_tmp10_, "libfm", "libfm.conf", NULL);
	self->libfm_dest = _tmp11_;
}


static void lxsession_conffiles_object_finalize (GObject* obj) {
	LxsessionConffilesObject * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, LXSESSION_TYPE_CONFFILES_OBJECT, LxsessionConffilesObject);
	_g_key_file_free0 (self->kf);
	_g_free0 (self->Openbox_dest);
	_g_free0 (self->Qt_dest);
	_g_free0 (self->Leafpad_dest);
	_g_free0 (self->Lxterminal_dest);
	_g_free0 (self->XScreensaver_dest);
	_g_free0 (self->libfm_dest);
	G_OBJECT_CLASS (lxsession_conffiles_object_parent_class)->finalize (obj);
}


GType lxsession_conffiles_object_get_type (void) {
	static volatile gsize lxsession_conffiles_object_type_id__volatile = 0;
	if (g_once_init_enter (&lxsession_conffiles_object_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LxsessionConffilesObjectClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) lxsession_conffiles_object_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LxsessionConffilesObject), 0, (GInstanceInitFunc) lxsession_conffiles_object_instance_init, NULL };
		GType lxsession_conffiles_object_type_id;
		lxsession_conffiles_object_type_id = g_type_register_static (G_TYPE_OBJECT, "LxsessionConffilesObject", &g_define_type_info, 0);
		g_once_init_leave (&lxsession_conffiles_object_type_id__volatile, lxsession_conffiles_object_type_id);
	}
	return lxsession_conffiles_object_type_id__volatile;
}



