/* environement.c generated by valac 0.18.1, the Vala compiler
 * generated from environement.vala, do not modify */

/* 
 *      Copyright 2011 Julien Lavergne <gilir@ubuntu.com>
 *
 *      This program is free software; you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published by
 *      the Free Software Foundation; either version 2 of the License, or
 *      (at your option) any later version.
 *
 *      This program is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 *
 *      You should have received a copy of the GNU General Public License
 *      along with this program; if not, write to the Free Software
 *      Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 *      MA 02110-1301, USA.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>


#define LXSESSION_TYPE_LXSESSION_ENV (lxsession_lxsession_env_get_type ())
#define LXSESSION_LXSESSION_ENV(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_LXSESSION_ENV, LxsessionLxsessionEnv))
#define LXSESSION_LXSESSION_ENV_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_LXSESSION_ENV, LxsessionLxsessionEnvClass))
#define LXSESSION_IS_LXSESSION_ENV(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_LXSESSION_ENV))
#define LXSESSION_IS_LXSESSION_ENV_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_LXSESSION_ENV))
#define LXSESSION_LXSESSION_ENV_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_LXSESSION_ENV, LxsessionLxsessionEnvClass))

typedef struct _LxsessionLxsessionEnv LxsessionLxsessionEnv;
typedef struct _LxsessionLxsessionEnvClass LxsessionLxsessionEnvClass;
typedef struct _LxsessionLxsessionEnvPrivate LxsessionLxsessionEnvPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

#define LXSESSION_TYPE_LXSESSION_CONFIG (lxsession_lxsession_config_get_type ())
#define LXSESSION_LXSESSION_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_LXSESSION_CONFIG, LxsessionLxsessionConfig))
#define LXSESSION_LXSESSION_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_LXSESSION_CONFIG, LxsessionLxsessionConfigClass))
#define LXSESSION_IS_LXSESSION_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_LXSESSION_CONFIG))
#define LXSESSION_IS_LXSESSION_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_LXSESSION_CONFIG))
#define LXSESSION_LXSESSION_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_LXSESSION_CONFIG, LxsessionLxsessionConfigClass))

typedef struct _LxsessionLxsessionConfig LxsessionLxsessionConfig;
typedef struct _LxsessionLxsessionConfigClass LxsessionLxsessionConfigClass;

#define LXSESSION_TYPE_LXSESSION_CONFIG_KEY_FILE (lxsession_lxsession_config_key_file_get_type ())
#define LXSESSION_LXSESSION_CONFIG_KEY_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_LXSESSION_CONFIG_KEY_FILE, LxsessionLxsessionConfigKeyFile))
#define LXSESSION_LXSESSION_CONFIG_KEY_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_LXSESSION_CONFIG_KEY_FILE, LxsessionLxsessionConfigKeyFileClass))
#define LXSESSION_IS_LXSESSION_CONFIG_KEY_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_LXSESSION_CONFIG_KEY_FILE))
#define LXSESSION_IS_LXSESSION_CONFIG_KEY_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_LXSESSION_CONFIG_KEY_FILE))
#define LXSESSION_LXSESSION_CONFIG_KEY_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_LXSESSION_CONFIG_KEY_FILE, LxsessionLxsessionConfigKeyFileClass))

typedef struct _LxsessionLxsessionConfigKeyFile LxsessionLxsessionConfigKeyFile;
typedef struct _LxsessionLxsessionConfigKeyFileClass LxsessionLxsessionConfigKeyFileClass;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _LxsessionLxsessionEnv {
	GObject parent_instance;
	LxsessionLxsessionEnvPrivate * priv;
};

struct _LxsessionLxsessionEnvClass {
	GObjectClass parent_class;
};

struct _LxsessionLxsessionEnvPrivate {
	gchar* display_env;
	gchar* pid_env;
	gchar* session_env;
	gchar* desktop_environment_env;
	gchar* display_name;
	gchar* pid_str;
	gchar* session;
	gchar* desktop_environment;
	gchar* config_home;
	gchar* config_dirs;
	gchar* data_dirs;
	gchar* home_path;
};


static gpointer lxsession_lxsession_env_parent_class = NULL;
extern LxsessionLxsessionConfigKeyFile* lxsession_global_settings;

GType lxsession_lxsession_env_get_type (void) G_GNUC_CONST;
#define LXSESSION_LXSESSION_ENV_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), LXSESSION_TYPE_LXSESSION_ENV, LxsessionLxsessionEnvPrivate))
enum  {
	LXSESSION_LXSESSION_ENV_DUMMY_PROPERTY
};
LxsessionLxsessionEnv* lxsession_lxsession_env_new (const gchar* session_arg, const gchar* desktop_environment_arg);
LxsessionLxsessionEnv* lxsession_lxsession_env_construct (GType object_type, const gchar* session_arg, const gchar* desktop_environment_arg);
void lxsession_lxsession_env_export_env (LxsessionLxsessionEnv* self);
GType lxsession_lxsession_config_get_type (void) G_GNUC_CONST;
GType lxsession_lxsession_config_key_file_get_type (void) G_GNUC_CONST;
const gchar* lxsession_lxsession_config_get_env_menu_prefix (LxsessionLxsessionConfig* self);
void lxsession_lxsession_env_set_xdg_dirs (LxsessionLxsessionEnv* self);
void lxsession_lxsession_env_set_misc (LxsessionLxsessionEnv* self);
gboolean lxsession_lxsession_env_check_alone (LxsessionLxsessionEnv* self);
const gchar* lxsession_lxsession_config_get_env_type (LxsessionLxsessionConfig* self);
static void lxsession_lxsession_env_finalize (GObject* obj);


LxsessionLxsessionEnv* lxsession_lxsession_env_construct (GType object_type, const gchar* session_arg, const gchar* desktop_environment_arg) {
	LxsessionLxsessionEnv * self = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	const gchar* _tmp4_;
	const gchar* _tmp5_ = NULL;
	gchar* _tmp6_;
	g_return_val_if_fail (session_arg != NULL, NULL);
	g_return_val_if_fail (desktop_environment_arg != NULL, NULL);
	self = (LxsessionLxsessionEnv*) g_object_new (object_type, NULL);
	_tmp0_ = session_arg;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->session);
	self->priv->session = _tmp1_;
	_tmp2_ = desktop_environment_arg;
	_tmp3_ = g_strdup (_tmp2_);
	_g_free0 (self->priv->desktop_environment);
	self->priv->desktop_environment = _tmp3_;
	_tmp4_ = self->priv->display_env;
	_tmp5_ = g_getenv (_tmp4_);
	_tmp6_ = g_strdup (_tmp5_);
	_g_free0 (self->priv->display_name);
	self->priv->display_name = _tmp6_;
	return self;
}


LxsessionLxsessionEnv* lxsession_lxsession_env_new (const gchar* session_arg, const gchar* desktop_environment_arg) {
	return lxsession_lxsession_env_construct (LXSESSION_TYPE_LXSESSION_ENV, session_arg, desktop_environment_arg);
}


void lxsession_lxsession_env_export_env (LxsessionLxsessionEnv* self) {
	const gchar* _tmp0_;
	pid_t _tmp1_ = 0;
	gchar* _tmp2_ = NULL;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	const gchar* _tmp6_;
	const gchar* _tmp7_;
	const gchar* _tmp8_;
	const gchar* _tmp9_;
	const gchar* _tmp10_;
	const gchar* _tmp11_ = NULL;
	gchar* _tmp12_;
	const gchar* _tmp13_ = NULL;
	gchar* _tmp14_;
	LxsessionLxsessionConfigKeyFile* _tmp15_;
	const gchar* _tmp16_;
	const gchar* _tmp17_;
	const gchar* _tmp18_;
	g_return_if_fail (self != NULL);
	g_message ("environement.vala:56: Exporting variable");
	_tmp0_ = self->priv->desktop_environment_env;
	g_message ("environement.vala:57: desktop_environnement %s", _tmp0_);
	_tmp1_ = getpid ();
	_tmp2_ = g_strdup_printf ("%d", (gint) _tmp1_);
	_g_free0 (self->priv->pid_str);
	self->priv->pid_str = _tmp2_;
	_tmp3_ = self->priv->session_env;
	_tmp4_ = self->priv->session;
	g_setenv (_tmp3_, _tmp4_, TRUE);
	_tmp5_ = self->priv->desktop_environment_env;
	_tmp6_ = self->priv->desktop_environment;
	g_setenv (_tmp5_, _tmp6_, TRUE);
	_tmp7_ = self->priv->pid_env;
	_tmp8_ = self->priv->pid_str;
	g_setenv (_tmp7_, _tmp8_, TRUE);
	_tmp9_ = self->priv->display_env;
	_tmp10_ = self->priv->display_name;
	g_setenv (_tmp9_, _tmp10_, TRUE);
	g_set_application_name ("lxsession");
	_tmp11_ = g_getenv ("HOME");
	_tmp12_ = g_strdup (_tmp11_);
	_g_free0 (self->priv->home_path);
	self->priv->home_path = _tmp12_;
	_tmp13_ = g_getenv ("XDG_CONFIG_HOME");
	_tmp14_ = g_strdup (_tmp13_);
	_g_free0 (self->priv->config_home);
	self->priv->config_home = _tmp14_;
	_tmp15_ = lxsession_global_settings;
	_tmp16_ = lxsession_lxsession_config_get_env_menu_prefix ((LxsessionLxsessionConfig*) _tmp15_);
	_tmp17_ = _tmp16_;
	g_setenv ("XDG_MENU_PREFIX", _tmp17_, TRUE);
	lxsession_lxsession_env_set_xdg_dirs (self);
	lxsession_lxsession_env_set_misc (self);
	_tmp18_ = self->priv->config_home;
	if (_tmp18_ == NULL) {
		const gchar* _tmp19_;
		gchar* _tmp20_;
		const gchar* _tmp21_;
		_tmp19_ = self->priv->home_path;
		_tmp20_ = g_strconcat (_tmp19_, "/.config", NULL);
		_g_free0 (self->priv->config_home);
		self->priv->config_home = _tmp20_;
		_tmp21_ = self->priv->config_home;
		g_setenv ("XDG_CONFIG_HOME", _tmp21_, TRUE);
	}
}


gboolean lxsession_lxsession_env_check_alone (LxsessionLxsessionEnv* self) {
	gboolean result = FALSE;
	gchar* lxsession_pid = NULL;
	const gchar* _tmp0_;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	g_return_val_if_fail (self != NULL, FALSE);
	g_message ("environement.vala:86: Getting lxsession pid");
	_tmp0_ = self->priv->pid_env;
	_tmp1_ = g_getenv (_tmp0_);
	_tmp2_ = g_strdup (_tmp1_);
	_g_free0 (lxsession_pid);
	lxsession_pid = _tmp2_;
	_tmp3_ = lxsession_pid;
	g_message ("environement.vala:89: Checking pid : %s", _tmp3_);
	_tmp4_ = lxsession_pid;
	if (_tmp4_ == NULL) {
		g_message ("environement.vala:93: Lxsession not detected");
		result = TRUE;
		_g_free0 (lxsession_pid);
		return result;
	} else {
		g_message ("environement.vala:98: Lxsession detected");
		result = FALSE;
		_g_free0 (lxsession_pid);
		return result;
	}
	_g_free0 (lxsession_pid);
}


void lxsession_lxsession_env_set_xdg_dirs (LxsessionLxsessionEnv* self) {
	gchar* custom_config = NULL;
	gchar* custom_data = NULL;
	gchar* return_config = NULL;
	gchar* return_data = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_;
	const gchar* _tmp4_;
	LxsessionLxsessionConfigKeyFile* _tmp9_;
	const gchar* _tmp10_;
	const gchar* _tmp11_;
	const gchar* _tmp12_;
	GQuark _tmp14_ = 0U;
	static GQuark _tmp13_label0 = 0;
	const gchar* _tmp17_;
	const gchar* _tmp29_;
	const gchar* _tmp31_;
	const gchar* _tmp43_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_getenv ("XDG_CONFIG_DIRS");
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->config_dirs);
	self->priv->config_dirs = _tmp1_;
	_tmp2_ = g_getenv ("XDG_CONFIG_DIRS");
	_tmp3_ = g_strdup (_tmp2_);
	_g_free0 (self->priv->data_dirs);
	self->priv->data_dirs = _tmp3_;
	_tmp4_ = self->priv->session;
	if (g_strcmp0 (_tmp4_, "Lubuntu") == 0) {
		gchar* _tmp5_;
		gchar* _tmp6_;
		_tmp5_ = g_strdup ("/etc/xdg/lubuntu:/etc/xdg");
		_g_free0 (custom_config);
		custom_config = _tmp5_;
		_tmp6_ = g_strdup ("/etc/xdg/lubuntu:/usr/local/share:/usr/share:/usr/share/gdm:/var/lib/m" \
"enu-xdg");
		_g_free0 (custom_data);
		custom_data = _tmp6_;
	} else {
		gchar* _tmp7_;
		gchar* _tmp8_;
		_tmp7_ = g_strdup ("/etc/xdg");
		_g_free0 (custom_config);
		custom_config = _tmp7_;
		_tmp8_ = g_strdup ("/usr/local/share:/usr/share:/usr/share/gdm:/var/lib/menu-xdg");
		_g_free0 (custom_data);
		custom_data = _tmp8_;
	}
	_tmp9_ = lxsession_global_settings;
	_tmp10_ = lxsession_lxsession_config_get_env_type ((LxsessionLxsessionConfig*) _tmp9_);
	_tmp11_ = _tmp10_;
	_tmp12_ = _tmp11_;
	_tmp14_ = (NULL == _tmp12_) ? 0 : g_quark_from_string (_tmp12_);
	if (_tmp14_ == ((0 != _tmp13_label0) ? _tmp13_label0 : (_tmp13_label0 = g_quark_from_static_string ("lubuntu")))) {
		switch (0) {
			default:
			{
				gchar* _tmp15_;
				gchar* _tmp16_;
				_tmp15_ = g_strdup ("/etc/xdg/lubuntu:/etc/xdg");
				_g_free0 (custom_config);
				custom_config = _tmp15_;
				_tmp16_ = g_strdup ("/etc/xdg/lubuntu:/usr/local/share:/usr/share:/usr/share/gdm:/var/lib/m" \
"enu-xdg");
				_g_free0 (custom_data);
				custom_data = _tmp16_;
				break;
			}
		}
	} else {
		switch (0) {
			default:
			{
				break;
			}
		}
	}
	_tmp17_ = self->priv->config_dirs;
	if (_tmp17_ == NULL) {
		const gchar* _tmp18_;
		gchar* _tmp19_;
		const gchar* _tmp20_;
		_tmp18_ = custom_config;
		_tmp19_ = g_strdup (_tmp18_);
		_g_free0 (return_config);
		return_config = _tmp19_;
		_tmp20_ = return_config;
		g_message ("environement.vala:139: confir_dirs is null, export : %s", _tmp20_);
	} else {
		const gchar* _tmp21_;
		gchar* _tmp22_;
		gchar* _tmp23_;
		const gchar* _tmp24_;
		gchar* _tmp25_;
		const gchar* _tmp26_;
		const gchar* _tmp27_;
		const gchar* _tmp28_;
		_tmp21_ = custom_config;
		_tmp22_ = g_strconcat (_tmp21_, ":", NULL);
		_tmp23_ = _tmp22_;
		_tmp24_ = self->priv->config_dirs;
		_tmp25_ = g_strconcat (_tmp23_, _tmp24_, NULL);
		_g_free0 (return_config);
		return_config = _tmp25_;
		_g_free0 (_tmp23_);
		_tmp26_ = custom_config;
		g_message ("environement.vala:144: custom_config :%s", _tmp26_);
		_tmp27_ = self->priv->config_dirs;
		g_message ("environement.vala:145: config_dirs :%s", _tmp27_);
		_tmp28_ = return_config;
		g_message ("environement.vala:146: confir_dirs not null, export : %s", _tmp28_);
	}
	_tmp29_ = return_config;
	if (_tmp29_ != NULL) {
		const gchar* _tmp30_;
		g_message ("environement.vala:151: Exporting XDG_CONFIG_DIRS");
		_tmp30_ = return_config;
		g_setenv ("XDG_CONFIG_DIRS", _tmp30_, TRUE);
	}
	_tmp31_ = self->priv->data_dirs;
	if (_tmp31_ == NULL) {
		const gchar* _tmp32_;
		gchar* _tmp33_;
		const gchar* _tmp34_;
		_tmp32_ = custom_data;
		_tmp33_ = g_strdup (_tmp32_);
		_g_free0 (return_data);
		return_data = _tmp33_;
		_tmp34_ = return_data;
		g_message ("environement.vala:158: data_dirs is null, export : %s", _tmp34_);
	} else {
		const gchar* _tmp35_;
		gchar* _tmp36_;
		gchar* _tmp37_;
		const gchar* _tmp38_;
		gchar* _tmp39_;
		const gchar* _tmp40_;
		const gchar* _tmp41_;
		const gchar* _tmp42_;
		_tmp35_ = custom_data;
		_tmp36_ = g_strconcat (_tmp35_, ":", NULL);
		_tmp37_ = _tmp36_;
		_tmp38_ = self->priv->data_dirs;
		_tmp39_ = g_strconcat (_tmp37_, _tmp38_, NULL);
		_g_free0 (return_data);
		return_data = _tmp39_;
		_g_free0 (_tmp37_);
		_tmp40_ = custom_data;
		g_message ("environement.vala:163: custom_data :%s", _tmp40_);
		_tmp41_ = self->priv->data_dirs;
		g_message ("environement.vala:164: data_dirs :%s", _tmp41_);
		_tmp42_ = return_data;
		g_message ("environement.vala:165: data_dirs not null, export : %s", _tmp42_);
	}
	_tmp43_ = return_data;
	if (_tmp43_ != NULL) {
		const gchar* _tmp44_;
		g_message ("environement.vala:170: Exporting XDG_DATA_DIRS");
		_tmp44_ = return_data;
		g_setenv ("XDG_DATA_DIRS", _tmp44_, TRUE);
	}
	_g_free0 (return_data);
	_g_free0 (return_config);
	_g_free0 (custom_data);
	_g_free0 (custom_config);
}


void lxsession_lxsession_env_set_misc (LxsessionLxsessionEnv* self) {
	gchar* dbus_path = NULL;
	gchar* dbus_env = NULL;
	gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_;
	const gchar* _tmp5_;
	gchar* qt_plugin = NULL;
	const gchar* _tmp9_ = NULL;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	{
		g_spawn_command_line_async ("xprop -root -remove _NET_NUMBER_OF_DESKTOPS -remove _NET_DESKTOP_NAMES" \
" -remove _NET_CURRENT_DESKTOP", &_inner_error_);
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_SPAWN_ERROR) {
				goto __catch16_g_spawn_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	goto __finally16;
	__catch16_g_spawn_error:
	{
		GError* err = NULL;
		GError* _tmp0_;
		const gchar* _tmp1_;
		err = _inner_error_;
		_inner_error_ = NULL;
		_tmp0_ = err;
		_tmp1_ = _tmp0_->message;
		g_message ("environement.vala:184: %s", _tmp1_);
		_g_error_free0 (err);
	}
	__finally16:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp2_ = g_find_program_in_path ("dbus-launch");
	_g_free0 (dbus_path);
	dbus_path = _tmp2_;
	_tmp3_ = g_getenv ("DBUS_SESSION_BUS_ADDRESS");
	_tmp4_ = g_strdup (_tmp3_);
	_g_free0 (dbus_env);
	dbus_env = _tmp4_;
	_tmp5_ = dbus_path;
	if (_tmp5_ == NULL) {
		const gchar* _tmp6_;
		_tmp6_ = dbus_env;
		if (_tmp6_ == NULL) {
			{
				g_spawn_command_line_async ("dbus-launch --sh-syntax --exit-with-session", &_inner_error_);
				if (_inner_error_ != NULL) {
					if (_inner_error_->domain == G_SPAWN_ERROR) {
						goto __catch17_g_spawn_error;
					}
					_g_free0 (dbus_env);
					_g_free0 (dbus_path);
					g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return;
				}
			}
			goto __finally17;
			__catch17_g_spawn_error:
			{
				GError* err = NULL;
				GError* _tmp7_;
				const gchar* _tmp8_;
				err = _inner_error_;
				_inner_error_ = NULL;
				_tmp7_ = err;
				_tmp8_ = _tmp7_->message;
				g_message ("environement.vala:204: %s", _tmp8_);
				_g_error_free0 (err);
			}
			__finally17:
			if (_inner_error_ != NULL) {
				_g_free0 (dbus_env);
				_g_free0 (dbus_path);
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return;
			}
		}
	}
	g_setenv ("SAL_USE_VCLPLUGIN", "gtk", TRUE);
	_tmp9_ = g_getenv ("QT_PLUGIN_PATH");
	_tmp10_ = g_strdup (_tmp9_);
	_g_free0 (qt_plugin);
	qt_plugin = _tmp10_;
	_tmp11_ = g_strconcat (qt_plugin, ":/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins", NULL);
	_tmp12_ = _tmp11_;
	g_setenv ("QT_PLUGIN_PATH", _tmp12_, TRUE);
	_g_free0 (_tmp12_);
	_g_free0 (qt_plugin);
	_g_free0 (dbus_env);
	_g_free0 (dbus_path);
}


static void lxsession_lxsession_env_class_init (LxsessionLxsessionEnvClass * klass) {
	lxsession_lxsession_env_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (LxsessionLxsessionEnvPrivate));
	G_OBJECT_CLASS (klass)->finalize = lxsession_lxsession_env_finalize;
}


static void lxsession_lxsession_env_instance_init (LxsessionLxsessionEnv * self) {
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	self->priv = LXSESSION_LXSESSION_ENV_GET_PRIVATE (self);
	_tmp0_ = g_strdup ("DISPLAY");
	self->priv->display_env = _tmp0_;
	_tmp1_ = g_strdup ("_LXSESSION_PID");
	self->priv->pid_env = _tmp1_;
	_tmp2_ = g_strdup ("DESKTOP_SESSION");
	self->priv->session_env = _tmp2_;
	_tmp3_ = g_strdup ("XDG_CURRENT_DESKTOP");
	self->priv->desktop_environment_env = _tmp3_;
}


static void lxsession_lxsession_env_finalize (GObject* obj) {
	LxsessionLxsessionEnv * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, LXSESSION_TYPE_LXSESSION_ENV, LxsessionLxsessionEnv);
	_g_free0 (self->priv->display_env);
	_g_free0 (self->priv->pid_env);
	_g_free0 (self->priv->session_env);
	_g_free0 (self->priv->desktop_environment_env);
	_g_free0 (self->priv->display_name);
	_g_free0 (self->priv->pid_str);
	_g_free0 (self->priv->session);
	_g_free0 (self->priv->desktop_environment);
	_g_free0 (self->priv->config_home);
	_g_free0 (self->priv->config_dirs);
	_g_free0 (self->priv->data_dirs);
	_g_free0 (self->priv->home_path);
	G_OBJECT_CLASS (lxsession_lxsession_env_parent_class)->finalize (obj);
}


GType lxsession_lxsession_env_get_type (void) {
	static volatile gsize lxsession_lxsession_env_type_id__volatile = 0;
	if (g_once_init_enter (&lxsession_lxsession_env_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LxsessionLxsessionEnvClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) lxsession_lxsession_env_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LxsessionLxsessionEnv), 0, (GInstanceInitFunc) lxsession_lxsession_env_instance_init, NULL };
		GType lxsession_lxsession_env_type_id;
		lxsession_lxsession_env_type_id = g_type_register_static (G_TYPE_OBJECT, "LxsessionLxsessionEnv", &g_define_type_info, 0);
		g_once_init_leave (&lxsession_lxsession_env_type_id__volatile, lxsession_lxsession_env_type_id);
	}
	return lxsession_lxsession_env_type_id__volatile;
}



