/* main.c generated by valac 0.18.1, the Vala compiler
 * generated from main.vala, do not modify */

/* 
 *      Copyright 2011 Julien Lavergne <gilir@ubuntu.com>
 *
 *      This program is free software; you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published by
 *      the Free Software Foundation; either version 2 of the License, or
 *      (at your option) any later version.
 *
 *      This program is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 *
 *      You should have received a copy of the GNU General Public License
 *      along with this program; if not, write to the Free Software
 *      Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 *      MA 02110-1301, USA.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <fcntl.h>
#include <sys/types.h>
#include <unistd.h>
#include <glib/gstdio.h>
#include <../lxsettings-daemon/settings-daemon.h>
#include <../xdg-autostart/xdg-autostart.h>


#define LXSESSION_TYPE_LX_SIGNALS (lxsession_lx_signals_get_type ())
#define LXSESSION_LX_SIGNALS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_LX_SIGNALS, LxsessionLxSignals))
#define LXSESSION_LX_SIGNALS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_LX_SIGNALS, LxsessionLxSignalsClass))
#define LXSESSION_IS_LX_SIGNALS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_LX_SIGNALS))
#define LXSESSION_IS_LX_SIGNALS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_LX_SIGNALS))
#define LXSESSION_LX_SIGNALS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_LX_SIGNALS, LxsessionLxSignalsClass))

typedef struct _LxsessionLxSignals LxsessionLxSignals;
typedef struct _LxsessionLxSignalsClass LxsessionLxSignalsClass;

#define LXSESSION_TYPE_LXSESSION_CONFIG (lxsession_lxsession_config_get_type ())
#define LXSESSION_LXSESSION_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_LXSESSION_CONFIG, LxsessionLxsessionConfig))
#define LXSESSION_LXSESSION_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_LXSESSION_CONFIG, LxsessionLxsessionConfigClass))
#define LXSESSION_IS_LXSESSION_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_LXSESSION_CONFIG))
#define LXSESSION_IS_LXSESSION_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_LXSESSION_CONFIG))
#define LXSESSION_LXSESSION_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_LXSESSION_CONFIG, LxsessionLxsessionConfigClass))

typedef struct _LxsessionLxsessionConfig LxsessionLxsessionConfig;
typedef struct _LxsessionLxsessionConfigClass LxsessionLxsessionConfigClass;

#define LXSESSION_TYPE_LXSESSION_CONFIG_KEY_FILE (lxsession_lxsession_config_key_file_get_type ())
#define LXSESSION_LXSESSION_CONFIG_KEY_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_LXSESSION_CONFIG_KEY_FILE, LxsessionLxsessionConfigKeyFile))
#define LXSESSION_LXSESSION_CONFIG_KEY_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_LXSESSION_CONFIG_KEY_FILE, LxsessionLxsessionConfigKeyFileClass))
#define LXSESSION_IS_LXSESSION_CONFIG_KEY_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_LXSESSION_CONFIG_KEY_FILE))
#define LXSESSION_IS_LXSESSION_CONFIG_KEY_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_LXSESSION_CONFIG_KEY_FILE))
#define LXSESSION_LXSESSION_CONFIG_KEY_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_LXSESSION_CONFIG_KEY_FILE, LxsessionLxsessionConfigKeyFileClass))

typedef struct _LxsessionLxsessionConfigKeyFile LxsessionLxsessionConfigKeyFile;
typedef struct _LxsessionLxsessionConfigKeyFileClass LxsessionLxsessionConfigKeyFileClass;

#define LXSESSION_TYPE_APP_OBJECT (lxsession_app_object_get_type ())
#define LXSESSION_APP_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_APP_OBJECT, LxsessionAppObject))
#define LXSESSION_APP_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_APP_OBJECT, LxsessionAppObjectClass))
#define LXSESSION_IS_APP_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_APP_OBJECT))
#define LXSESSION_IS_APP_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_APP_OBJECT))
#define LXSESSION_APP_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_APP_OBJECT, LxsessionAppObjectClass))

typedef struct _LxsessionAppObject LxsessionAppObject;
typedef struct _LxsessionAppObjectClass LxsessionAppObjectClass;

#define LXSESSION_TYPE_SIMPLE_APP_OBJECT (lxsession_simple_app_object_get_type ())
#define LXSESSION_SIMPLE_APP_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_SIMPLE_APP_OBJECT, LxsessionSimpleAppObject))
#define LXSESSION_SIMPLE_APP_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_SIMPLE_APP_OBJECT, LxsessionSimpleAppObjectClass))
#define LXSESSION_IS_SIMPLE_APP_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_SIMPLE_APP_OBJECT))
#define LXSESSION_IS_SIMPLE_APP_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_SIMPLE_APP_OBJECT))
#define LXSESSION_SIMPLE_APP_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_SIMPLE_APP_OBJECT, LxsessionSimpleAppObjectClass))

typedef struct _LxsessionSimpleAppObject LxsessionSimpleAppObject;
typedef struct _LxsessionSimpleAppObjectClass LxsessionSimpleAppObjectClass;

#define LXSESSION_TYPE_PANEL_APP (lxsession_panel_app_get_type ())
#define LXSESSION_PANEL_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_PANEL_APP, LxsessionPanelApp))
#define LXSESSION_PANEL_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_PANEL_APP, LxsessionPanelAppClass))
#define LXSESSION_IS_PANEL_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_PANEL_APP))
#define LXSESSION_IS_PANEL_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_PANEL_APP))
#define LXSESSION_PANEL_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_PANEL_APP, LxsessionPanelAppClass))

typedef struct _LxsessionPanelApp LxsessionPanelApp;
typedef struct _LxsessionPanelAppClass LxsessionPanelAppClass;

#define LXSESSION_TYPE_DOCK_APP (lxsession_dock_app_get_type ())
#define LXSESSION_DOCK_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_DOCK_APP, LxsessionDockApp))
#define LXSESSION_DOCK_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_DOCK_APP, LxsessionDockAppClass))
#define LXSESSION_IS_DOCK_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_DOCK_APP))
#define LXSESSION_IS_DOCK_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_DOCK_APP))
#define LXSESSION_DOCK_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_DOCK_APP, LxsessionDockAppClass))

typedef struct _LxsessionDockApp LxsessionDockApp;
typedef struct _LxsessionDockAppClass LxsessionDockAppClass;

#define LXSESSION_TYPE_WINDOWS_MANAGER_APP (lxsession_windows_manager_app_get_type ())
#define LXSESSION_WINDOWS_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_WINDOWS_MANAGER_APP, LxsessionWindowsManagerApp))
#define LXSESSION_WINDOWS_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_WINDOWS_MANAGER_APP, LxsessionWindowsManagerAppClass))
#define LXSESSION_IS_WINDOWS_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_WINDOWS_MANAGER_APP))
#define LXSESSION_IS_WINDOWS_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_WINDOWS_MANAGER_APP))
#define LXSESSION_WINDOWS_MANAGER_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_WINDOWS_MANAGER_APP, LxsessionWindowsManagerAppClass))

typedef struct _LxsessionWindowsManagerApp LxsessionWindowsManagerApp;
typedef struct _LxsessionWindowsManagerAppClass LxsessionWindowsManagerAppClass;

#define LXSESSION_TYPE_FILE_MANAGER_APP (lxsession_file_manager_app_get_type ())
#define LXSESSION_FILE_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_FILE_MANAGER_APP, LxsessionFileManagerApp))
#define LXSESSION_FILE_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_FILE_MANAGER_APP, LxsessionFileManagerAppClass))
#define LXSESSION_IS_FILE_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_FILE_MANAGER_APP))
#define LXSESSION_IS_FILE_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_FILE_MANAGER_APP))
#define LXSESSION_FILE_MANAGER_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_FILE_MANAGER_APP, LxsessionFileManagerAppClass))

typedef struct _LxsessionFileManagerApp LxsessionFileManagerApp;
typedef struct _LxsessionFileManagerAppClass LxsessionFileManagerAppClass;

#define LXSESSION_TYPE_DESKTOP_APP (lxsession_desktop_app_get_type ())
#define LXSESSION_DESKTOP_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_DESKTOP_APP, LxsessionDesktopApp))
#define LXSESSION_DESKTOP_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_DESKTOP_APP, LxsessionDesktopAppClass))
#define LXSESSION_IS_DESKTOP_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_DESKTOP_APP))
#define LXSESSION_IS_DESKTOP_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_DESKTOP_APP))
#define LXSESSION_DESKTOP_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_DESKTOP_APP, LxsessionDesktopAppClass))

typedef struct _LxsessionDesktopApp LxsessionDesktopApp;
typedef struct _LxsessionDesktopAppClass LxsessionDesktopAppClass;

#define LXSESSION_TYPE_POLKIT_APP (lxsession_polkit_app_get_type ())
#define LXSESSION_POLKIT_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_POLKIT_APP, LxsessionPolkitApp))
#define LXSESSION_POLKIT_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_POLKIT_APP, LxsessionPolkitAppClass))
#define LXSESSION_IS_POLKIT_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_POLKIT_APP))
#define LXSESSION_IS_POLKIT_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_POLKIT_APP))
#define LXSESSION_POLKIT_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_POLKIT_APP, LxsessionPolkitAppClass))

typedef struct _LxsessionPolkitApp LxsessionPolkitApp;
typedef struct _LxsessionPolkitAppClass LxsessionPolkitAppClass;

#define LXSESSION_TYPE_SCREENSAVER_APP (lxsession_screensaver_app_get_type ())
#define LXSESSION_SCREENSAVER_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_SCREENSAVER_APP, LxsessionScreensaverApp))
#define LXSESSION_SCREENSAVER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_SCREENSAVER_APP, LxsessionScreensaverAppClass))
#define LXSESSION_IS_SCREENSAVER_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_SCREENSAVER_APP))
#define LXSESSION_IS_SCREENSAVER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_SCREENSAVER_APP))
#define LXSESSION_SCREENSAVER_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_SCREENSAVER_APP, LxsessionScreensaverAppClass))

typedef struct _LxsessionScreensaverApp LxsessionScreensaverApp;
typedef struct _LxsessionScreensaverAppClass LxsessionScreensaverAppClass;

#define LXSESSION_TYPE_POWER_MANAGER_APP (lxsession_power_manager_app_get_type ())
#define LXSESSION_POWER_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_POWER_MANAGER_APP, LxsessionPowerManagerApp))
#define LXSESSION_POWER_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_POWER_MANAGER_APP, LxsessionPowerManagerAppClass))
#define LXSESSION_IS_POWER_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_POWER_MANAGER_APP))
#define LXSESSION_IS_POWER_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_POWER_MANAGER_APP))
#define LXSESSION_POWER_MANAGER_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_POWER_MANAGER_APP, LxsessionPowerManagerAppClass))

typedef struct _LxsessionPowerManagerApp LxsessionPowerManagerApp;
typedef struct _LxsessionPowerManagerAppClass LxsessionPowerManagerAppClass;

#define LXSESSION_TYPE_NETWORK_GUI_APP (lxsession_network_gui_app_get_type ())
#define LXSESSION_NETWORK_GUI_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_NETWORK_GUI_APP, LxsessionNetworkGuiApp))
#define LXSESSION_NETWORK_GUI_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_NETWORK_GUI_APP, LxsessionNetworkGuiAppClass))
#define LXSESSION_IS_NETWORK_GUI_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_NETWORK_GUI_APP))
#define LXSESSION_IS_NETWORK_GUI_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_NETWORK_GUI_APP))
#define LXSESSION_NETWORK_GUI_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_NETWORK_GUI_APP, LxsessionNetworkGuiAppClass))

typedef struct _LxsessionNetworkGuiApp LxsessionNetworkGuiApp;
typedef struct _LxsessionNetworkGuiAppClass LxsessionNetworkGuiAppClass;

#define LXSESSION_TYPE_COMPOSITE_MANAGER_APP (lxsession_composite_manager_app_get_type ())
#define LXSESSION_COMPOSITE_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_COMPOSITE_MANAGER_APP, LxsessionCompositeManagerApp))
#define LXSESSION_COMPOSITE_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_COMPOSITE_MANAGER_APP, LxsessionCompositeManagerAppClass))
#define LXSESSION_IS_COMPOSITE_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_COMPOSITE_MANAGER_APP))
#define LXSESSION_IS_COMPOSITE_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_COMPOSITE_MANAGER_APP))
#define LXSESSION_COMPOSITE_MANAGER_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_COMPOSITE_MANAGER_APP, LxsessionCompositeManagerAppClass))

typedef struct _LxsessionCompositeManagerApp LxsessionCompositeManagerApp;
typedef struct _LxsessionCompositeManagerAppClass LxsessionCompositeManagerAppClass;

#define LXSESSION_TYPE_AUDIO_MANAGER_APP (lxsession_audio_manager_app_get_type ())
#define LXSESSION_AUDIO_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_AUDIO_MANAGER_APP, LxsessionAudioManagerApp))
#define LXSESSION_AUDIO_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_AUDIO_MANAGER_APP, LxsessionAudioManagerAppClass))
#define LXSESSION_IS_AUDIO_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_AUDIO_MANAGER_APP))
#define LXSESSION_IS_AUDIO_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_AUDIO_MANAGER_APP))
#define LXSESSION_AUDIO_MANAGER_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_AUDIO_MANAGER_APP, LxsessionAudioManagerAppClass))

typedef struct _LxsessionAudioManagerApp LxsessionAudioManagerApp;
typedef struct _LxsessionAudioManagerAppClass LxsessionAudioManagerAppClass;

#define LXSESSION_TYPE_QUIT_MANAGER_APP (lxsession_quit_manager_app_get_type ())
#define LXSESSION_QUIT_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_QUIT_MANAGER_APP, LxsessionQuitManagerApp))
#define LXSESSION_QUIT_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_QUIT_MANAGER_APP, LxsessionQuitManagerAppClass))
#define LXSESSION_IS_QUIT_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_QUIT_MANAGER_APP))
#define LXSESSION_IS_QUIT_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_QUIT_MANAGER_APP))
#define LXSESSION_QUIT_MANAGER_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_QUIT_MANAGER_APP, LxsessionQuitManagerAppClass))

typedef struct _LxsessionQuitManagerApp LxsessionQuitManagerApp;
typedef struct _LxsessionQuitManagerAppClass LxsessionQuitManagerAppClass;

#define LXSESSION_TYPE_WORKSPACE_MANAGER_APP (lxsession_workspace_manager_app_get_type ())
#define LXSESSION_WORKSPACE_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_WORKSPACE_MANAGER_APP, LxsessionWorkspaceManagerApp))
#define LXSESSION_WORKSPACE_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_WORKSPACE_MANAGER_APP, LxsessionWorkspaceManagerAppClass))
#define LXSESSION_IS_WORKSPACE_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_WORKSPACE_MANAGER_APP))
#define LXSESSION_IS_WORKSPACE_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_WORKSPACE_MANAGER_APP))
#define LXSESSION_WORKSPACE_MANAGER_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_WORKSPACE_MANAGER_APP, LxsessionWorkspaceManagerAppClass))

typedef struct _LxsessionWorkspaceManagerApp LxsessionWorkspaceManagerApp;
typedef struct _LxsessionWorkspaceManagerAppClass LxsessionWorkspaceManagerAppClass;

#define LXSESSION_TYPE_LAUNCHER_MANAGER_APP (lxsession_launcher_manager_app_get_type ())
#define LXSESSION_LAUNCHER_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_LAUNCHER_MANAGER_APP, LxsessionLauncherManagerApp))
#define LXSESSION_LAUNCHER_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_LAUNCHER_MANAGER_APP, LxsessionLauncherManagerAppClass))
#define LXSESSION_IS_LAUNCHER_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_LAUNCHER_MANAGER_APP))
#define LXSESSION_IS_LAUNCHER_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_LAUNCHER_MANAGER_APP))
#define LXSESSION_LAUNCHER_MANAGER_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_LAUNCHER_MANAGER_APP, LxsessionLauncherManagerAppClass))

typedef struct _LxsessionLauncherManagerApp LxsessionLauncherManagerApp;
typedef struct _LxsessionLauncherManagerAppClass LxsessionLauncherManagerAppClass;

#define LXSESSION_TYPE_TERMINAL_MANAGER_APP (lxsession_terminal_manager_app_get_type ())
#define LXSESSION_TERMINAL_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_TERMINAL_MANAGER_APP, LxsessionTerminalManagerApp))
#define LXSESSION_TERMINAL_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_TERMINAL_MANAGER_APP, LxsessionTerminalManagerAppClass))
#define LXSESSION_IS_TERMINAL_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_TERMINAL_MANAGER_APP))
#define LXSESSION_IS_TERMINAL_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_TERMINAL_MANAGER_APP))
#define LXSESSION_TERMINAL_MANAGER_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_TERMINAL_MANAGER_APP, LxsessionTerminalManagerAppClass))

typedef struct _LxsessionTerminalManagerApp LxsessionTerminalManagerApp;
typedef struct _LxsessionTerminalManagerAppClass LxsessionTerminalManagerAppClass;

#define LXSESSION_TYPE_SCREENSHOT_MANAGER_APP (lxsession_screenshot_manager_app_get_type ())
#define LXSESSION_SCREENSHOT_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_SCREENSHOT_MANAGER_APP, LxsessionScreenshotManagerApp))
#define LXSESSION_SCREENSHOT_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_SCREENSHOT_MANAGER_APP, LxsessionScreenshotManagerAppClass))
#define LXSESSION_IS_SCREENSHOT_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_SCREENSHOT_MANAGER_APP))
#define LXSESSION_IS_SCREENSHOT_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_SCREENSHOT_MANAGER_APP))
#define LXSESSION_SCREENSHOT_MANAGER_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_SCREENSHOT_MANAGER_APP, LxsessionScreenshotManagerAppClass))

typedef struct _LxsessionScreenshotManagerApp LxsessionScreenshotManagerApp;
typedef struct _LxsessionScreenshotManagerAppClass LxsessionScreenshotManagerAppClass;

#define LXSESSION_TYPE_UPGRADE_MANAGER_APP (lxsession_upgrade_manager_app_get_type ())
#define LXSESSION_UPGRADE_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_UPGRADE_MANAGER_APP, LxsessionUpgradeManagerApp))
#define LXSESSION_UPGRADE_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_UPGRADE_MANAGER_APP, LxsessionUpgradeManagerAppClass))
#define LXSESSION_IS_UPGRADE_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_UPGRADE_MANAGER_APP))
#define LXSESSION_IS_UPGRADE_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_UPGRADE_MANAGER_APP))
#define LXSESSION_UPGRADE_MANAGER_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_UPGRADE_MANAGER_APP, LxsessionUpgradeManagerAppClass))

typedef struct _LxsessionUpgradeManagerApp LxsessionUpgradeManagerApp;
typedef struct _LxsessionUpgradeManagerAppClass LxsessionUpgradeManagerAppClass;

#define LXSESSION_TYPE_OPTION (lxsession_option_get_type ())
#define LXSESSION_OPTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_OPTION, LxsessionOption))
#define LXSESSION_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_OPTION, LxsessionOptionClass))
#define LXSESSION_IS_OPTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_OPTION))
#define LXSESSION_IS_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_OPTION))
#define LXSESSION_OPTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_OPTION, LxsessionOptionClass))

typedef struct _LxsessionOption LxsessionOption;
typedef struct _LxsessionOptionClass LxsessionOptionClass;

#define LXSESSION_TYPE_CLIPBOARD_OPTION (lxsession_clipboard_option_get_type ())
#define LXSESSION_CLIPBOARD_OPTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_CLIPBOARD_OPTION, LxsessionClipboardOption))
#define LXSESSION_CLIPBOARD_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_CLIPBOARD_OPTION, LxsessionClipboardOptionClass))
#define LXSESSION_IS_CLIPBOARD_OPTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_CLIPBOARD_OPTION))
#define LXSESSION_IS_CLIPBOARD_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_CLIPBOARD_OPTION))
#define LXSESSION_CLIPBOARD_OPTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_CLIPBOARD_OPTION, LxsessionClipboardOptionClass))

typedef struct _LxsessionClipboardOption LxsessionClipboardOption;
typedef struct _LxsessionClipboardOptionClass LxsessionClipboardOptionClass;

#define LXSESSION_TYPE_KEYMAP_OPTION (lxsession_keymap_option_get_type ())
#define LXSESSION_KEYMAP_OPTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_KEYMAP_OPTION, LxsessionKeymapOption))
#define LXSESSION_KEYMAP_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_KEYMAP_OPTION, LxsessionKeymapOptionClass))
#define LXSESSION_IS_KEYMAP_OPTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_KEYMAP_OPTION))
#define LXSESSION_IS_KEYMAP_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_KEYMAP_OPTION))
#define LXSESSION_KEYMAP_OPTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_KEYMAP_OPTION, LxsessionKeymapOptionClass))

typedef struct _LxsessionKeymapOption LxsessionKeymapOption;
typedef struct _LxsessionKeymapOptionClass LxsessionKeymapOptionClass;

#define LXSESSION_TYPE_XRANDR_OPTION (lxsession_xrandr_option_get_type ())
#define LXSESSION_XRANDR_OPTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_XRANDR_OPTION, LxsessionXrandrOption))
#define LXSESSION_XRANDR_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_XRANDR_OPTION, LxsessionXrandrOptionClass))
#define LXSESSION_IS_XRANDR_OPTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_XRANDR_OPTION))
#define LXSESSION_IS_XRANDR_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_XRANDR_OPTION))
#define LXSESSION_XRANDR_OPTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_XRANDR_OPTION, LxsessionXrandrOptionClass))

typedef struct _LxsessionXrandrOption LxsessionXrandrOption;
typedef struct _LxsessionXrandrOptionClass LxsessionXrandrOptionClass;

#define LXSESSION_TYPE_KEYRING_OPTION (lxsession_keyring_option_get_type ())
#define LXSESSION_KEYRING_OPTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_KEYRING_OPTION, LxsessionKeyringOption))
#define LXSESSION_KEYRING_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_KEYRING_OPTION, LxsessionKeyringOptionClass))
#define LXSESSION_IS_KEYRING_OPTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_KEYRING_OPTION))
#define LXSESSION_IS_KEYRING_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_KEYRING_OPTION))
#define LXSESSION_KEYRING_OPTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_KEYRING_OPTION, LxsessionKeyringOptionClass))

typedef struct _LxsessionKeyringOption LxsessionKeyringOption;
typedef struct _LxsessionKeyringOptionClass LxsessionKeyringOptionClass;

#define LXSESSION_TYPE_A11Y_OPTION (lxsession_a11y_option_get_type ())
#define LXSESSION_A11Y_OPTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_A11Y_OPTION, LxsessionA11yOption))
#define LXSESSION_A11Y_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_A11Y_OPTION, LxsessionA11yOptionClass))
#define LXSESSION_IS_A11Y_OPTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_A11Y_OPTION))
#define LXSESSION_IS_A11Y_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_A11Y_OPTION))
#define LXSESSION_A11Y_OPTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_A11Y_OPTION, LxsessionA11yOptionClass))

typedef struct _LxsessionA11yOption LxsessionA11yOption;
typedef struct _LxsessionA11yOptionClass LxsessionA11yOptionClass;

#define LXSESSION_TYPE_UPDATES_OPTION (lxsession_updates_option_get_type ())
#define LXSESSION_UPDATES_OPTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_UPDATES_OPTION, LxsessionUpdatesOption))
#define LXSESSION_UPDATES_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_UPDATES_OPTION, LxsessionUpdatesOptionClass))
#define LXSESSION_IS_UPDATES_OPTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_UPDATES_OPTION))
#define LXSESSION_IS_UPDATES_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_UPDATES_OPTION))
#define LXSESSION_UPDATES_OPTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_UPDATES_OPTION, LxsessionUpdatesOptionClass))

typedef struct _LxsessionUpdatesOption LxsessionUpdatesOption;
typedef struct _LxsessionUpdatesOptionClass LxsessionUpdatesOptionClass;

#define LXSESSION_TYPE_IM_APP (lxsession_im_app_get_type ())
#define LXSESSION_IM_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_IM_APP, LxsessionIMApp))
#define LXSESSION_IM_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_IM_APP, LxsessionIMAppClass))
#define LXSESSION_IS_IM_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_IM_APP))
#define LXSESSION_IS_IM_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_IM_APP))
#define LXSESSION_IM_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_IM_APP, LxsessionIMAppClass))

typedef struct _LxsessionIMApp LxsessionIMApp;
typedef struct _LxsessionIMAppClass LxsessionIMAppClass;

#define LXSESSION_TYPE_IM1_APP (lxsession_im1_app_get_type ())
#define LXSESSION_IM1_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_IM1_APP, LxsessionIM1App))
#define LXSESSION_IM1_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_IM1_APP, LxsessionIM1AppClass))
#define LXSESSION_IS_IM1_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_IM1_APP))
#define LXSESSION_IS_IM1_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_IM1_APP))
#define LXSESSION_IM1_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_IM1_APP, LxsessionIM1AppClass))

typedef struct _LxsessionIM1App LxsessionIM1App;
typedef struct _LxsessionIM1AppClass LxsessionIM1AppClass;

#define LXSESSION_TYPE_IM2_APP (lxsession_im2_app_get_type ())
#define LXSESSION_IM2_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_IM2_APP, LxsessionIM2App))
#define LXSESSION_IM2_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_IM2_APP, LxsessionIM2AppClass))
#define LXSESSION_IS_IM2_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_IM2_APP))
#define LXSESSION_IS_IM2_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_IM2_APP))
#define LXSESSION_IM2_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_IM2_APP, LxsessionIM2AppClass))

typedef struct _LxsessionIM2App LxsessionIM2App;
typedef struct _LxsessionIM2AppClass LxsessionIM2AppClass;

#define LXSESSION_TYPE_WIDGET_APP (lxsession_widget_app_get_type ())
#define LXSESSION_WIDGET_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_WIDGET_APP, LxsessionWidgetApp))
#define LXSESSION_WIDGET_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_WIDGET_APP, LxsessionWidgetAppClass))
#define LXSESSION_IS_WIDGET_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_WIDGET_APP))
#define LXSESSION_IS_WIDGET_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_WIDGET_APP))
#define LXSESSION_WIDGET_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_WIDGET_APP, LxsessionWidgetAppClass))

typedef struct _LxsessionWidgetApp LxsessionWidgetApp;
typedef struct _LxsessionWidgetAppClass LxsessionWidgetAppClass;

#define LXSESSION_TYPE_PROXY_OPTION (lxsession_proxy_option_get_type ())
#define LXSESSION_PROXY_OPTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_PROXY_OPTION, LxsessionProxyOption))
#define LXSESSION_PROXY_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_PROXY_OPTION, LxsessionProxyOptionClass))
#define LXSESSION_IS_PROXY_OPTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_PROXY_OPTION))
#define LXSESSION_IS_PROXY_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_PROXY_OPTION))
#define LXSESSION_PROXY_OPTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_PROXY_OPTION, LxsessionProxyOptionClass))

typedef struct _LxsessionProxyOption LxsessionProxyOption;
typedef struct _LxsessionProxyOptionClass LxsessionProxyOptionClass;

#define LXSESSION_TYPE_UPSTART_USER_SESSION_OPTION (lxsession_upstart_user_session_option_get_type ())
#define LXSESSION_UPSTART_USER_SESSION_OPTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_UPSTART_USER_SESSION_OPTION, LxsessionUpstartUserSessionOption))
#define LXSESSION_UPSTART_USER_SESSION_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_UPSTART_USER_SESSION_OPTION, LxsessionUpstartUserSessionOptionClass))
#define LXSESSION_IS_UPSTART_USER_SESSION_OPTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_UPSTART_USER_SESSION_OPTION))
#define LXSESSION_IS_UPSTART_USER_SESSION_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_UPSTART_USER_SESSION_OPTION))
#define LXSESSION_UPSTART_USER_SESSION_OPTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_UPSTART_USER_SESSION_OPTION, LxsessionUpstartUserSessionOptionClass))

typedef struct _LxsessionUpstartUserSessionOption LxsessionUpstartUserSessionOption;
typedef struct _LxsessionUpstartUserSessionOptionClass LxsessionUpstartUserSessionOptionClass;

#define LXSESSION_TYPE_MAIN (lxsession_main_get_type ())
#define LXSESSION_MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_MAIN, LxsessionMain))
#define LXSESSION_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_MAIN, LxsessionMainClass))
#define LXSESSION_IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_MAIN))
#define LXSESSION_IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_MAIN))
#define LXSESSION_MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_MAIN, LxsessionMainClass))

typedef struct _LxsessionMain LxsessionMain;
typedef struct _LxsessionMainClass LxsessionMainClass;
typedef struct _LxsessionMainPrivate LxsessionMainPrivate;
#define _g_option_context_free0(var) ((var == NULL) ? NULL : (var = (g_option_context_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define LXSESSION_TYPE_RAZOR_QT_CONFIG_KEY_FILE (lxsession_razor_qt_config_key_file_get_type ())
#define LXSESSION_RAZOR_QT_CONFIG_KEY_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_RAZOR_QT_CONFIG_KEY_FILE, LxsessionRazorQtConfigKeyFile))
#define LXSESSION_RAZOR_QT_CONFIG_KEY_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_RAZOR_QT_CONFIG_KEY_FILE, LxsessionRazorQtConfigKeyFileClass))
#define LXSESSION_IS_RAZOR_QT_CONFIG_KEY_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_RAZOR_QT_CONFIG_KEY_FILE))
#define LXSESSION_IS_RAZOR_QT_CONFIG_KEY_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_RAZOR_QT_CONFIG_KEY_FILE))
#define LXSESSION_RAZOR_QT_CONFIG_KEY_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_RAZOR_QT_CONFIG_KEY_FILE, LxsessionRazorQtConfigKeyFileClass))

typedef struct _LxsessionRazorQtConfigKeyFile LxsessionRazorQtConfigKeyFile;
typedef struct _LxsessionRazorQtConfigKeyFileClass LxsessionRazorQtConfigKeyFileClass;

#define LXSESSION_TYPE_LXSESSION_ENV (lxsession_lxsession_env_get_type ())
#define LXSESSION_LXSESSION_ENV(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_LXSESSION_ENV, LxsessionLxsessionEnv))
#define LXSESSION_LXSESSION_ENV_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_LXSESSION_ENV, LxsessionLxsessionEnvClass))
#define LXSESSION_IS_LXSESSION_ENV(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_LXSESSION_ENV))
#define LXSESSION_IS_LXSESSION_ENV_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_LXSESSION_ENV))
#define LXSESSION_LXSESSION_ENV_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_LXSESSION_ENV, LxsessionLxsessionEnvClass))

typedef struct _LxsessionLxsessionEnv LxsessionLxsessionEnv;
typedef struct _LxsessionLxsessionEnvClass LxsessionLxsessionEnvClass;
#define _g_key_file_free0(var) ((var == NULL) ? NULL : (var = (g_key_file_free (var), NULL)))

#define LXSESSION_TYPE_LXSESSION_AUTOSTART_CONFIG (lxsession_lxsession_autostart_config_get_type ())
#define LXSESSION_LXSESSION_AUTOSTART_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_LXSESSION_AUTOSTART_CONFIG, LxsessionLxsessionAutostartConfig))
#define LXSESSION_LXSESSION_AUTOSTART_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_LXSESSION_AUTOSTART_CONFIG, LxsessionLxsessionAutostartConfigClass))
#define LXSESSION_IS_LXSESSION_AUTOSTART_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_LXSESSION_AUTOSTART_CONFIG))
#define LXSESSION_IS_LXSESSION_AUTOSTART_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_LXSESSION_AUTOSTART_CONFIG))
#define LXSESSION_LXSESSION_AUTOSTART_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_LXSESSION_AUTOSTART_CONFIG, LxsessionLxsessionAutostartConfigClass))

typedef struct _LxsessionLxsessionAutostartConfig LxsessionLxsessionAutostartConfig;
typedef struct _LxsessionLxsessionAutostartConfigClass LxsessionLxsessionAutostartConfigClass;
#define _g_main_loop_unref0(var) ((var == NULL) ? NULL : (var = (g_main_loop_unref (var), NULL)))

struct _LxsessionMain {
	GObject parent_instance;
	LxsessionMainPrivate * priv;
};

struct _LxsessionMainClass {
	GObjectClass parent_class;
};


extern LxsessionLxSignals* lxsession_global_sig;
LxsessionLxSignals* lxsession_global_sig = NULL;
extern LxsessionLxsessionConfigKeyFile* lxsession_global_settings;
LxsessionLxsessionConfigKeyFile* lxsession_global_settings = NULL;
extern LxsessionPanelApp* lxsession_global_panel;
LxsessionPanelApp* lxsession_global_panel = NULL;
extern LxsessionDockApp* lxsession_global_dock;
LxsessionDockApp* lxsession_global_dock = NULL;
extern LxsessionWindowsManagerApp* lxsession_global_windows_manager;
LxsessionWindowsManagerApp* lxsession_global_windows_manager = NULL;
extern LxsessionFileManagerApp* lxsession_global_file_manager;
LxsessionFileManagerApp* lxsession_global_file_manager = NULL;
extern LxsessionDesktopApp* lxsession_global_desktop;
LxsessionDesktopApp* lxsession_global_desktop = NULL;
extern LxsessionPolkitApp* lxsession_global_polkit;
LxsessionPolkitApp* lxsession_global_polkit = NULL;
extern LxsessionScreensaverApp* lxsession_global_screensaver;
LxsessionScreensaverApp* lxsession_global_screensaver = NULL;
extern LxsessionPowerManagerApp* lxsession_global_power_manager;
LxsessionPowerManagerApp* lxsession_global_power_manager = NULL;
extern LxsessionNetworkGuiApp* lxsession_global_network_gui;
LxsessionNetworkGuiApp* lxsession_global_network_gui = NULL;
extern LxsessionCompositeManagerApp* lxsession_global_composite_manager;
LxsessionCompositeManagerApp* lxsession_global_composite_manager = NULL;
extern LxsessionAudioManagerApp* lxsession_global_audio_manager;
LxsessionAudioManagerApp* lxsession_global_audio_manager = NULL;
extern LxsessionQuitManagerApp* lxsession_global_quit_manager;
LxsessionQuitManagerApp* lxsession_global_quit_manager = NULL;
extern LxsessionWorkspaceManagerApp* lxsession_global_workspace_manager;
LxsessionWorkspaceManagerApp* lxsession_global_workspace_manager = NULL;
extern LxsessionLauncherManagerApp* lxsession_global_launcher_manager;
LxsessionLauncherManagerApp* lxsession_global_launcher_manager = NULL;
extern LxsessionTerminalManagerApp* lxsession_global_terminal_manager;
LxsessionTerminalManagerApp* lxsession_global_terminal_manager = NULL;
extern LxsessionScreenshotManagerApp* lxsession_global_screenshot_manager;
LxsessionScreenshotManagerApp* lxsession_global_screenshot_manager = NULL;
extern LxsessionUpgradeManagerApp* lxsession_global_upgrade_manager;
LxsessionUpgradeManagerApp* lxsession_global_upgrade_manager = NULL;
extern LxsessionClipboardOption* lxsession_global_clipboard;
LxsessionClipboardOption* lxsession_global_clipboard = NULL;
extern LxsessionKeymapOption* lxsession_global_keymap;
LxsessionKeymapOption* lxsession_global_keymap = NULL;
extern LxsessionXrandrOption* lxsession_global_xrandr;
LxsessionXrandrOption* lxsession_global_xrandr = NULL;
extern LxsessionKeyringOption* lxsession_global_keyring;
LxsessionKeyringOption* lxsession_global_keyring = NULL;
extern LxsessionA11yOption* lxsession_global_a11y;
LxsessionA11yOption* lxsession_global_a11y = NULL;
extern LxsessionUpdatesOption* lxsession_global_updates;
LxsessionUpdatesOption* lxsession_global_updates = NULL;
extern LxsessionIM1App* lxsession_global_im1;
LxsessionIM1App* lxsession_global_im1 = NULL;
extern LxsessionIM2App* lxsession_global_im2;
LxsessionIM2App* lxsession_global_im2 = NULL;
extern LxsessionWidgetApp* lxsession_global_widget1;
LxsessionWidgetApp* lxsession_global_widget1 = NULL;
extern LxsessionProxyOption* lxsession_global_proxy;
LxsessionProxyOption* lxsession_global_proxy = NULL;
extern LxsessionUpstartUserSessionOption* lxsession_global_upstart_session;
LxsessionUpstartUserSessionOption* lxsession_global_upstart_session = NULL;
static gpointer lxsession_main_parent_class = NULL;
static gchar* lxsession_main_session;
static gchar* lxsession_main_session = NULL;
static gchar* lxsession_main_desktop_environnement;
static gchar* lxsession_main_desktop_environnement = NULL;
static gboolean lxsession_main_reload;
static gboolean lxsession_main_reload = FALSE;
static gboolean lxsession_main_noxsettings;
static gboolean lxsession_main_noxsettings = FALSE;
static gboolean lxsession_main_autostart;
static gboolean lxsession_main_autostart = FALSE;
static gchar* lxsession_main_compatibility;
static gchar* lxsession_main_compatibility = NULL;
extern gchar* lxsession_session_global;

GType lxsession_lx_signals_get_type (void) G_GNUC_CONST;
GType lxsession_lxsession_config_get_type (void) G_GNUC_CONST;
GType lxsession_lxsession_config_key_file_get_type (void) G_GNUC_CONST;
GType lxsession_app_object_get_type (void) G_GNUC_CONST;
GType lxsession_simple_app_object_get_type (void) G_GNUC_CONST;
GType lxsession_panel_app_get_type (void) G_GNUC_CONST;
GType lxsession_dock_app_get_type (void) G_GNUC_CONST;
GType lxsession_windows_manager_app_get_type (void) G_GNUC_CONST;
GType lxsession_file_manager_app_get_type (void) G_GNUC_CONST;
GType lxsession_desktop_app_get_type (void) G_GNUC_CONST;
GType lxsession_polkit_app_get_type (void) G_GNUC_CONST;
GType lxsession_screensaver_app_get_type (void) G_GNUC_CONST;
GType lxsession_power_manager_app_get_type (void) G_GNUC_CONST;
GType lxsession_network_gui_app_get_type (void) G_GNUC_CONST;
GType lxsession_composite_manager_app_get_type (void) G_GNUC_CONST;
GType lxsession_audio_manager_app_get_type (void) G_GNUC_CONST;
GType lxsession_quit_manager_app_get_type (void) G_GNUC_CONST;
GType lxsession_workspace_manager_app_get_type (void) G_GNUC_CONST;
GType lxsession_launcher_manager_app_get_type (void) G_GNUC_CONST;
GType lxsession_terminal_manager_app_get_type (void) G_GNUC_CONST;
GType lxsession_screenshot_manager_app_get_type (void) G_GNUC_CONST;
GType lxsession_upgrade_manager_app_get_type (void) G_GNUC_CONST;
GType lxsession_option_get_type (void) G_GNUC_CONST;
GType lxsession_clipboard_option_get_type (void) G_GNUC_CONST;
GType lxsession_keymap_option_get_type (void) G_GNUC_CONST;
GType lxsession_xrandr_option_get_type (void) G_GNUC_CONST;
GType lxsession_keyring_option_get_type (void) G_GNUC_CONST;
GType lxsession_a11y_option_get_type (void) G_GNUC_CONST;
GType lxsession_updates_option_get_type (void) G_GNUC_CONST;
GType lxsession_im_app_get_type (void) G_GNUC_CONST;
GType lxsession_im1_app_get_type (void) G_GNUC_CONST;
GType lxsession_im2_app_get_type (void) G_GNUC_CONST;
GType lxsession_widget_app_get_type (void) G_GNUC_CONST;
GType lxsession_proxy_option_get_type (void) G_GNUC_CONST;
GType lxsession_upstart_user_session_option_get_type (void) G_GNUC_CONST;
GType lxsession_main_get_type (void) G_GNUC_CONST;
enum  {
	LXSESSION_MAIN_DUMMY_PROPERTY
};
gint lxsession_main_main (gchar** args, int args_length1);
LxsessionLxSignals* lxsession_lx_signals_new (void);
LxsessionLxSignals* lxsession_lx_signals_construct (GType object_type);
LxsessionRazorQtConfigKeyFile* lxsession_razor_qt_config_key_file_new (const gchar* session_arg, const gchar* desktop_env_name_arg);
LxsessionRazorQtConfigKeyFile* lxsession_razor_qt_config_key_file_construct (GType object_type, const gchar* session_arg, const gchar* desktop_env_name_arg);
GType lxsession_razor_qt_config_key_file_get_type (void) G_GNUC_CONST;
LxsessionLxsessionConfigKeyFile* lxsession_lxsession_config_key_file_new (const gchar* session_arg, const gchar* desktop_env_name_arg);
LxsessionLxsessionConfigKeyFile* lxsession_lxsession_config_key_file_construct (GType object_type, const gchar* session_arg, const gchar* desktop_env_name_arg);
void lxsession_lxsession_config_key_file_sync_setting_files (LxsessionLxsessionConfigKeyFile* self);
LxsessionLxsessionEnv* lxsession_lxsession_env_new (const gchar* session_arg, const gchar* desktop_environment_arg);
LxsessionLxsessionEnv* lxsession_lxsession_env_construct (GType object_type, const gchar* session_arg, const gchar* desktop_environment_arg);
GType lxsession_lxsession_env_get_type (void) G_GNUC_CONST;
void lxsession_lxsession_env_export_env (LxsessionLxsessionEnv* self);
gchar* lxsession_get_config_path (const gchar* conf_file);
GKeyFile* lxsession_load_keyfile (const gchar* config_path);
const gchar* lxsession_lxsession_config_get_window_manager (LxsessionLxsessionConfig* self);
LxsessionWindowsManagerApp* lxsession_windows_manager_app_new (void);
LxsessionWindowsManagerApp* lxsession_windows_manager_app_construct (GType object_type);
void lxsession_windows_manager_app_launch (LxsessionWindowsManagerApp* self);
const gchar* lxsession_lxsession_config_get_windows_manager_command (LxsessionLxsessionConfig* self);
const gchar* lxsession_lxsession_config_get_disable_autostart (LxsessionLxsessionConfig* self);
const gchar* lxsession_lxsession_config_get_panel_command (LxsessionLxsessionConfig* self);
LxsessionPanelApp* lxsession_panel_app_new (void);
LxsessionPanelApp* lxsession_panel_app_construct (GType object_type);
void lxsession_app_object_launch (LxsessionAppObject* self);
const gchar* lxsession_lxsession_config_get_dock_command (LxsessionLxsessionConfig* self);
LxsessionDockApp* lxsession_dock_app_new (void);
LxsessionDockApp* lxsession_dock_app_construct (GType object_type);
const gchar* lxsession_lxsession_config_get_screensaver_command (LxsessionLxsessionConfig* self);
LxsessionScreensaverApp* lxsession_screensaver_app_new (void);
LxsessionScreensaverApp* lxsession_screensaver_app_construct (GType object_type);
const gchar* lxsession_lxsession_config_get_power_manager_command (LxsessionLxsessionConfig* self);
const gchar* lxsession_lxsession_config_get_laptop_mode (LxsessionLxsessionConfig* self);
gboolean lxsession_detect_laptop (void);
LxsessionPowerManagerApp* lxsession_power_manager_app_new (void);
LxsessionPowerManagerApp* lxsession_power_manager_app_construct (GType object_type);
const gchar* lxsession_lxsession_config_get_network_gui_command (LxsessionLxsessionConfig* self);
LxsessionNetworkGuiApp* lxsession_network_gui_app_new (void);
LxsessionNetworkGuiApp* lxsession_network_gui_app_construct (GType object_type);
const gchar* lxsession_lxsession_config_get_desktop_command (LxsessionLxsessionConfig* self);
LxsessionDesktopApp* lxsession_desktop_app_new (void);
LxsessionDesktopApp* lxsession_desktop_app_construct (GType object_type);
const gchar* lxsession_lxsession_config_get_composite_manager_autostart (LxsessionLxsessionConfig* self);
const gchar* lxsession_lxsession_config_get_composite_manager_command (LxsessionLxsessionConfig* self);
LxsessionCompositeManagerApp* lxsession_composite_manager_app_new (void);
LxsessionCompositeManagerApp* lxsession_composite_manager_app_construct (GType object_type);
const gchar* lxsession_lxsession_config_get_polkit_command (LxsessionLxsessionConfig* self);
LxsessionPolkitApp* lxsession_polkit_app_new (void);
LxsessionPolkitApp* lxsession_polkit_app_construct (GType object_type);
const gchar* lxsession_lxsession_config_get_launcher_manager_autostart (LxsessionLxsessionConfig* self);
const gchar* lxsession_lxsession_config_get_launcher_manager_command (LxsessionLxsessionConfig* self);
LxsessionLauncherManagerApp* lxsession_launcher_manager_app_new (void);
LxsessionLauncherManagerApp* lxsession_launcher_manager_app_construct (GType object_type);
void lxsession_launcher_manager_app_autostart_launch (LxsessionLauncherManagerApp* self);
const gchar* lxsession_lxsession_config_get_im1_autostart (LxsessionLxsessionConfig* self);
const gchar* lxsession_lxsession_config_get_im1_command (LxsessionLxsessionConfig* self);
LxsessionIM1App* lxsession_im1_app_new (void);
LxsessionIM1App* lxsession_im1_app_construct (GType object_type);
const gchar* lxsession_lxsession_config_get_im2_autostart (LxsessionLxsessionConfig* self);
const gchar* lxsession_lxsession_config_get_im2_command (LxsessionLxsessionConfig* self);
LxsessionIM2App* lxsession_im2_app_new (void);
LxsessionIM2App* lxsession_im2_app_construct (GType object_type);
const gchar* lxsession_lxsession_config_get_widget1_autostart (LxsessionLxsessionConfig* self);
const gchar* lxsession_lxsession_config_get_widget1_command (LxsessionLxsessionConfig* self);
LxsessionWidgetApp* lxsession_widget_app_new (void);
LxsessionWidgetApp* lxsession_widget_app_construct (GType object_type);
LxsessionLxsessionAutostartConfig* lxsession_lxsession_autostart_config_new (void);
LxsessionLxsessionAutostartConfig* lxsession_lxsession_autostart_config_construct (GType object_type);
GType lxsession_lxsession_autostart_config_get_type (void) G_GNUC_CONST;
void lxsession_lxsession_autostart_config_start_applications (LxsessionLxsessionAutostartConfig* self);
const gchar* lxsession_lxsession_config_get_clipboard_command (LxsessionLxsessionConfig* self);
LxsessionClipboardOption* lxsession_clipboard_option_new (LxsessionLxsessionConfig* config);
LxsessionClipboardOption* lxsession_clipboard_option_construct (GType object_type, LxsessionLxsessionConfig* config);
void lxsession_option_activate (LxsessionOption* self);
const gchar* lxsession_lxsession_config_get_keymap_mode (LxsessionLxsessionConfig* self);
LxsessionKeymapOption* lxsession_keymap_option_new (LxsessionLxsessionConfig* config);
LxsessionKeymapOption* lxsession_keymap_option_construct (GType object_type, LxsessionLxsessionConfig* config);
const gchar* lxsession_lxsession_config_get_xrandr_mode (LxsessionLxsessionConfig* self);
LxsessionXrandrOption* lxsession_xrandr_option_new (LxsessionLxsessionConfig* config);
LxsessionXrandrOption* lxsession_xrandr_option_construct (GType object_type, LxsessionLxsessionConfig* config);
const gchar* lxsession_lxsession_config_get_security_keyring (LxsessionLxsessionConfig* self);
LxsessionKeyringOption* lxsession_keyring_option_new (LxsessionLxsessionConfig* config);
LxsessionKeyringOption* lxsession_keyring_option_construct (GType object_type, LxsessionLxsessionConfig* config);
void lxsession_keyring_option_activate (LxsessionKeyringOption* self);
const gchar* lxsession_lxsession_config_get_a11y_type (LxsessionLxsessionConfig* self);
LxsessionA11yOption* lxsession_a11y_option_new (LxsessionLxsessionConfig* config);
LxsessionA11yOption* lxsession_a11y_option_construct (GType object_type, LxsessionLxsessionConfig* config);
void lxsession_a11y_option_activate (LxsessionA11yOption* self);
const gchar* lxsession_lxsession_config_get_proxy_http (LxsessionLxsessionConfig* self);
LxsessionProxyOption* lxsession_proxy_option_new (LxsessionLxsessionConfig* config);
LxsessionProxyOption* lxsession_proxy_option_construct (GType object_type, LxsessionLxsessionConfig* config);
void lxsession_proxy_option_activate (LxsessionProxyOption* self);
const gchar* lxsession_lxsession_config_get_updates_type (LxsessionLxsessionConfig* self);
LxsessionUpdatesOption* lxsession_updates_option_new (LxsessionLxsessionConfig* config);
LxsessionUpdatesOption* lxsession_updates_option_construct (GType object_type, LxsessionLxsessionConfig* config);
void lxsession_updates_option_activate (LxsessionUpdatesOption* self);
const gchar* lxsession_lxsession_config_get_upstart_user_session (LxsessionLxsessionConfig* self);
LxsessionUpstartUserSessionOption* lxsession_upstart_user_session_option_new (LxsessionLxsessionConfig* config);
LxsessionUpstartUserSessionOption* lxsession_upstart_user_session_option_construct (GType object_type, LxsessionLxsessionConfig* config);
void lxsession_upstart_user_session_option_activate (LxsessionUpstartUserSessionOption* self);
const gchar* lxsession_lxsession_config_get_dbus_lxde (LxsessionLxsessionConfig* self);
void lxsession_on_bus_aquired (GDBusConnection* conn);
static void _lxsession_on_bus_aquired_gbus_acquired_callback (GDBusConnection* connection, const gchar* name, gpointer self);
static void ___lambda2_ (void);
static void ____lambda2__gbus_name_acquired_callback (GDBusConnection* connection, const gchar* name, gpointer self);
static void ___lambda3_ (void);
static void ____lambda3__gbus_name_lost_callback (GDBusConnection* connection, const gchar* name, gpointer self);
const gchar* lxsession_lxsession_config_get_dbus_gnome (LxsessionLxsessionConfig* self);
void lxsession_on_gnome_bus_aquired (GDBusConnection* conn);
static void _lxsession_on_gnome_bus_aquired_gbus_acquired_callback (GDBusConnection* connection, const gchar* name, gpointer self);
static void ___lambda4_ (void);
static void ____lambda4__gbus_name_acquired_callback (GDBusConnection* connection, const gchar* name, gpointer self);
static void ___lambda5_ (void);
static void ____lambda5__gbus_name_lost_callback (GDBusConnection* connection, const gchar* name, gpointer self);
void lxsession_clipboard_option_desactivate (LxsessionClipboardOption* self);
void lxsession_polkit_app_deactivate (LxsessionPolkitApp* self);
void lxsession_app_object_stop (LxsessionAppObject* self);
LxsessionMain* lxsession_main_new (void);
LxsessionMain* lxsession_main_construct (GType object_type);
static void lxsession_main_finalize (GObject* obj);

static const GOptionEntry LXSESSION_MAIN_option_entries[7] = {{"session", 's', 0, G_OPTION_ARG_STRING, &lxsession_main_session, "specify name of the desktop session profile", "NAME"}, {"de", 'e', 0, G_OPTION_ARG_STRING, &lxsession_main_desktop_environnement, "specify name of DE, such as LXDE, GNOME, or XFCE.", "NAME"}, {"reload", 'r', 0, G_OPTION_ARG_NONE, &lxsession_main_reload, "reload configurations (for Xsettings daemon)", NULL}, {"noxsettings", 'n', 0, G_OPTION_ARG_NONE, &lxsession_main_noxsettings, "disable Xsettings daemon support", NULL}, {"noautostart", 'a', 0, G_OPTION_ARG_NONE, &lxsession_main_autostart, "autostart applications disable (window-manager mode only)", NULL}, {"compatibility", 'c', 0, G_OPTION_ARG_STRING, &lxsession_main_compatibility, "specify a compatibility mode for settings (only razor-qt supported)", "NAME"}, {NULL}};

static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void _lxsession_on_bus_aquired_gbus_acquired_callback (GDBusConnection* connection, const gchar* name, gpointer self) {
	lxsession_on_bus_aquired (connection);
}


static void ___lambda2_ (void) {
}


static void ____lambda2__gbus_name_acquired_callback (GDBusConnection* connection, const gchar* name, gpointer self) {
	___lambda2_ ();
}


static void ___lambda3_ (void) {
	g_warning ("main.vala:448: Could not aquire name\n");
}


static void ____lambda3__gbus_name_lost_callback (GDBusConnection* connection, const gchar* name, gpointer self) {
	___lambda3_ ();
}


static void _lxsession_on_gnome_bus_aquired_gbus_acquired_callback (GDBusConnection* connection, const gchar* name, gpointer self) {
	lxsession_on_gnome_bus_aquired (connection);
}


static void ___lambda4_ (void) {
}


static void ____lambda4__gbus_name_acquired_callback (GDBusConnection* connection, const gchar* name, gpointer self) {
	___lambda4_ ();
}


static void ___lambda5_ (void) {
	g_warning ("main.vala:457: Could not aquire name\n");
}


static void ____lambda5__gbus_name_lost_callback (GDBusConnection* connection, const gchar* name, gpointer self) {
	___lambda5_ ();
}


gint lxsession_main_main (gchar** args, int args_length1) {
	gint result = 0;
	const gchar* _tmp6_;
	const gchar* _tmp7_;
	const gchar* _tmp8_;
	const gchar* _tmp10_;
	const gchar* _tmp12_;
	gchar* _tmp13_;
	const gchar* _tmp14_ = NULL;
	const gchar* _tmp15_;
	gchar* _tmp16_ = NULL;
	gchar* log_directory;
	const gchar* _tmp17_;
	GFile* _tmp18_ = NULL;
	GFile* dir_log;
	const gchar* _tmp19_;
	gchar* _tmp20_ = NULL;
	gchar* log_path;
	const gchar* _tmp21_;
	const gchar* _tmp22_;
	GFile* _tmp23_;
	gboolean _tmp24_ = FALSE;
	gint fint = 0;
	const gchar* _tmp28_;
	gint _tmp29_ = 0;
	gint _tmp30_;
	gint _tmp31_;
	gint _tmp32_;
	LxsessionLxSignals* _tmp33_;
	LxsessionLxSignals* sig;
	LxsessionLxSignals* _tmp34_;
	LxsessionLxSignals* _tmp35_;
	const gchar* _tmp36_;
	LxsessionLxsessionConfigKeyFile* _tmp47_;
	const gchar* _tmp48_;
	const gchar* _tmp49_;
	LxsessionLxsessionEnv* _tmp50_;
	LxsessionLxsessionEnv* environment;
	LxsessionLxsessionEnv* _tmp51_;
	gchar* _tmp52_ = NULL;
	gchar* conffiles_conf;
	const gchar* _tmp53_;
	gboolean _tmp54_ = FALSE;
	gboolean _tmp55_;
	LxsessionLxsessionConfigKeyFile* _tmp60_;
	const gchar* _tmp61_;
	const gchar* _tmp62_;
	LxsessionLxsessionConfigKeyFile* _tmp74_;
	const gchar* _tmp75_;
	const gchar* _tmp76_;
	gboolean _tmp77_;
	LxsessionLxsessionConfigKeyFile* _tmp209_;
	const gchar* _tmp210_;
	const gchar* _tmp211_;
	LxsessionLxsessionConfigKeyFile* _tmp217_;
	const gchar* _tmp218_;
	const gchar* _tmp219_;
	LxsessionLxsessionConfigKeyFile* _tmp220_;
	const gchar* _tmp221_;
	const gchar* _tmp222_;
	LxsessionLxsessionConfigKeyFile* _tmp228_;
	const gchar* _tmp229_;
	const gchar* _tmp230_;
	LxsessionLxsessionConfigKeyFile* _tmp236_;
	const gchar* _tmp237_;
	const gchar* _tmp238_;
	LxsessionLxsessionConfigKeyFile* _tmp244_;
	const gchar* _tmp245_;
	const gchar* _tmp246_;
	LxsessionLxsessionConfigKeyFile* _tmp252_;
	const gchar* _tmp253_;
	const gchar* _tmp254_;
	LxsessionLxsessionConfigKeyFile* _tmp260_;
	const gchar* _tmp261_;
	const gchar* _tmp262_;
	LxsessionLxsessionConfigKeyFile* _tmp268_;
	const gchar* _tmp269_;
	const gchar* _tmp270_;
	LxsessionLxsessionConfigKeyFile* _tmp276_;
	const gchar* _tmp277_;
	const gchar* _tmp278_;
	LxsessionLxsessionConfigKeyFile* _tmp279_;
	const gchar* _tmp280_;
	const gchar* _tmp281_;
	GMainLoop* _tmp282_;
	GMainLoop* _tmp283_;
	LxsessionClipboardOption* _tmp284_;
	LxsessionLxsessionConfigKeyFile* _tmp286_;
	const gchar* _tmp287_;
	const gchar* _tmp288_;
	LxsessionPanelApp* _tmp291_;
	LxsessionDockApp* _tmp293_;
	LxsessionWindowsManagerApp* _tmp295_;
	LxsessionDesktopApp* _tmp297_;
	LxsessionPolkitApp* _tmp299_;
	LxsessionScreensaverApp* _tmp301_;
	LxsessionPowerManagerApp* _tmp303_;
	LxsessionNetworkGuiApp* _tmp305_;
	LxsessionCompositeManagerApp* _tmp307_;
	GError * _inner_error_ = NULL;
	{
		GOptionContext* _tmp0_;
		GOptionContext* options_args;
		GOptionContext* _tmp1_;
		GOptionContext* _tmp2_;
		GOptionContext* _tmp3_;
		_tmp0_ = g_option_context_new ("- Lightweight Session manager");
		options_args = _tmp0_;
		_tmp1_ = options_args;
		g_option_context_set_help_enabled (_tmp1_, TRUE);
		_tmp2_ = options_args;
		g_option_context_add_main_entries (_tmp2_, LXSESSION_MAIN_option_entries, NULL);
		_tmp3_ = options_args;
		g_option_context_parse (_tmp3_, &args_length1, &args, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_option_context_free0 (options_args);
			if (_inner_error_->domain == G_OPTION_ERROR) {
				goto __catch0_g_option_error;
			}
			_g_option_context_free0 (options_args);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return 0;
		}
		_g_option_context_free0 (options_args);
	}
	goto __finally0;
	__catch0_g_option_error:
	{
		GError* e = NULL;
		GError* _tmp4_;
		const gchar* _tmp5_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp4_ = e;
		_tmp5_ = _tmp4_->message;
		g_critical ("main.vala:92: Option parsing failed: %s\n", _tmp5_);
		result = -1;
		_g_error_free0 (e);
		return result;
	}
	__finally0:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0;
	}
	_tmp6_ = lxsession_main_session;
	g_message ("main.vala:96: Session is %s", _tmp6_);
	_tmp7_ = lxsession_main_desktop_environnement;
	g_message ("main.vala:97: DE is %s", _tmp7_);
	_tmp8_ = lxsession_main_session;
	if (_tmp8_ == NULL) {
		gchar* _tmp9_;
		g_message ("main.vala:101: No session set, fallback to LXDE session");
		_tmp9_ = g_strdup ("LXDE");
		_g_free0 (lxsession_main_session);
		lxsession_main_session = _tmp9_;
	}
	_tmp10_ = lxsession_main_desktop_environnement;
	if (_tmp10_ == NULL) {
		gchar* _tmp11_;
		g_message ("main.vala:107: No desktop environnement set, fallback to LXDE");
		_tmp11_ = g_strdup ("LXDE");
		_g_free0 (lxsession_main_desktop_environnement);
		lxsession_main_desktop_environnement = _tmp11_;
	}
	_tmp12_ = lxsession_main_session;
	_tmp13_ = g_strdup (_tmp12_);
	_g_free0 (lxsession_session_global);
	lxsession_session_global = _tmp13_;
	_tmp14_ = g_get_user_cache_dir ();
	_tmp15_ = lxsession_main_session;
	_tmp16_ = g_build_filename (_tmp14_, "lxsession", _tmp15_, NULL);
	log_directory = _tmp16_;
	_tmp17_ = log_directory;
	_tmp18_ = g_file_new_for_path (_tmp17_);
	dir_log = _tmp18_;
	_tmp19_ = log_directory;
	_tmp20_ = g_build_filename (_tmp19_, "run.log", NULL);
	log_path = _tmp20_;
	_tmp21_ = log_directory;
	g_message ("main.vala:128: log directory: %s", _tmp21_);
	_tmp22_ = log_path;
	g_message ("main.vala:129: log path: %s", _tmp22_);
	_tmp23_ = dir_log;
	_tmp24_ = g_file_query_exists (_tmp23_, NULL);
	if (!_tmp24_) {
		{
			GFile* _tmp25_;
			_tmp25_ = dir_log;
			g_file_make_directory_with_parents (_tmp25_, NULL, &_inner_error_);
			if (_inner_error_ != NULL) {
				goto __catch1_g_error;
			}
		}
		goto __finally1;
		__catch1_g_error:
		{
			GError* err = NULL;
			GError* _tmp26_;
			const gchar* _tmp27_;
			err = _inner_error_;
			_inner_error_ = NULL;
			_tmp26_ = err;
			_tmp27_ = _tmp26_->message;
			g_message ("main.vala:139: %s", _tmp27_);
			_g_error_free0 (err);
		}
		__finally1:
		if (_inner_error_ != NULL) {
			_g_free0 (log_path);
			_g_object_unref0 (dir_log);
			_g_free0 (log_directory);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return 0;
		}
	}
	_tmp28_ = log_path;
	_tmp29_ = open (_tmp28_, (O_WRONLY | O_CREAT) | O_TRUNC, (mode_t) 0600);
	fint = _tmp29_;
	_tmp30_ = fint;
	dup2 (_tmp30_, STDOUT_FILENO);
	_tmp31_ = fint;
	dup2 (_tmp31_, STDERR_FILENO);
	_tmp32_ = fint;
	close (_tmp32_);
	_tmp33_ = lxsession_lx_signals_new ();
	sig = _tmp33_;
	_tmp34_ = sig;
	_tmp35_ = _g_object_ref0 (_tmp34_);
	_g_object_unref0 (lxsession_global_sig);
	lxsession_global_sig = _tmp35_;
	_tmp36_ = lxsession_main_compatibility;
	if (g_strcmp0 (_tmp36_, "razor-qt") == 0) {
		const gchar* _tmp37_;
		const gchar* _tmp38_;
		LxsessionRazorQtConfigKeyFile* _tmp39_;
		LxsessionRazorQtConfigKeyFile* config;
		LxsessionRazorQtConfigKeyFile* _tmp40_;
		LxsessionLxsessionConfigKeyFile* _tmp41_;
		_tmp37_ = lxsession_main_session;
		_tmp38_ = lxsession_main_desktop_environnement;
		_tmp39_ = lxsession_razor_qt_config_key_file_new (_tmp37_, _tmp38_);
		config = _tmp39_;
		_tmp40_ = config;
		_tmp41_ = _g_object_ref0 ((LxsessionLxsessionConfigKeyFile*) _tmp40_);
		_g_object_unref0 (lxsession_global_settings);
		lxsession_global_settings = _tmp41_;
		_g_object_unref0 (config);
	} else {
		const gchar* _tmp42_;
		const gchar* _tmp43_;
		LxsessionLxsessionConfigKeyFile* _tmp44_;
		LxsessionLxsessionConfigKeyFile* config;
		LxsessionLxsessionConfigKeyFile* _tmp45_;
		LxsessionLxsessionConfigKeyFile* _tmp46_;
		_tmp42_ = lxsession_main_session;
		_tmp43_ = lxsession_main_desktop_environnement;
		_tmp44_ = lxsession_lxsession_config_key_file_new (_tmp42_, _tmp43_);
		config = _tmp44_;
		_tmp45_ = config;
		_tmp46_ = _g_object_ref0 (_tmp45_);
		_g_object_unref0 (lxsession_global_settings);
		lxsession_global_settings = _tmp46_;
		_g_object_unref0 (config);
	}
	_tmp47_ = lxsession_global_settings;
	lxsession_lxsession_config_key_file_sync_setting_files (_tmp47_);
	_tmp48_ = lxsession_main_session;
	_tmp49_ = lxsession_main_desktop_environnement;
	_tmp50_ = lxsession_lxsession_env_new (_tmp48_, _tmp49_);
	environment = _tmp50_;
	_tmp51_ = environment;
	lxsession_lxsession_env_export_env (_tmp51_);
	_tmp52_ = lxsession_get_config_path ("conffiles.conf");
	conffiles_conf = _tmp52_;
	_tmp53_ = conffiles_conf;
	_tmp54_ = g_file_test (_tmp53_, G_FILE_TEST_EXISTS);
	if (_tmp54_) {
	}
	_tmp55_ = lxsession_main_noxsettings;
	if (_tmp55_ == FALSE) {
		gchar* _tmp56_ = NULL;
		gchar* _tmp57_;
		GKeyFile* _tmp58_ = NULL;
		GKeyFile* _tmp59_;
		_tmp56_ = lxsession_get_config_path ("desktop.conf");
		_tmp57_ = _tmp56_;
		_tmp58_ = lxsession_load_keyfile (_tmp57_);
		_tmp59_ = _tmp58_;
		settings_daemon_start (_tmp59_);
		_g_key_file_free0 (_tmp59_);
		_g_free0 (_tmp57_);
	}
	_tmp60_ = lxsession_global_settings;
	_tmp61_ = lxsession_lxsession_config_get_window_manager ((LxsessionLxsessionConfig*) _tmp60_);
	_tmp62_ = _tmp61_;
	if (_tmp62_ != NULL) {
		LxsessionWindowsManagerApp* _tmp63_;
		LxsessionWindowsManagerApp* windowsmanager;
		LxsessionWindowsManagerApp* _tmp64_;
		LxsessionWindowsManagerApp* _tmp65_;
		LxsessionWindowsManagerApp* _tmp66_;
		_tmp63_ = lxsession_windows_manager_app_new ();
		windowsmanager = _tmp63_;
		_tmp64_ = windowsmanager;
		_tmp65_ = _g_object_ref0 (_tmp64_);
		_g_object_unref0 (lxsession_global_windows_manager);
		lxsession_global_windows_manager = _tmp65_;
		_tmp66_ = lxsession_global_windows_manager;
		lxsession_windows_manager_app_launch (_tmp66_);
		_g_object_unref0 (windowsmanager);
	} else {
		LxsessionLxsessionConfigKeyFile* _tmp67_;
		const gchar* _tmp68_;
		const gchar* _tmp69_;
		_tmp67_ = lxsession_global_settings;
		_tmp68_ = lxsession_lxsession_config_get_windows_manager_command ((LxsessionLxsessionConfig*) _tmp67_);
		_tmp69_ = _tmp68_;
		if (_tmp69_ != NULL) {
			LxsessionWindowsManagerApp* _tmp70_;
			LxsessionWindowsManagerApp* windowsmanager;
			LxsessionWindowsManagerApp* _tmp71_;
			LxsessionWindowsManagerApp* _tmp72_;
			LxsessionWindowsManagerApp* _tmp73_;
			_tmp70_ = lxsession_windows_manager_app_new ();
			windowsmanager = _tmp70_;
			_tmp71_ = windowsmanager;
			_tmp72_ = _g_object_ref0 (_tmp71_);
			_g_object_unref0 (lxsession_global_windows_manager);
			lxsession_global_windows_manager = _tmp72_;
			_tmp73_ = lxsession_global_windows_manager;
			lxsession_windows_manager_app_launch (_tmp73_);
			_g_object_unref0 (windowsmanager);
		}
	}
	_tmp74_ = lxsession_global_settings;
	_tmp75_ = lxsession_lxsession_config_get_disable_autostart ((LxsessionLxsessionConfig*) _tmp74_);
	_tmp76_ = _tmp75_;
	if (g_strcmp0 (_tmp76_, "all") == 0) {
		lxsession_main_autostart = TRUE;
	}
	_tmp77_ = lxsession_main_autostart;
	if (_tmp77_ == FALSE) {
		LxsessionLxsessionConfigKeyFile* _tmp78_;
		const gchar* _tmp79_;
		const gchar* _tmp80_;
		LxsessionLxsessionConfigKeyFile* _tmp85_;
		const gchar* _tmp86_;
		const gchar* _tmp87_;
		LxsessionLxsessionConfigKeyFile* _tmp92_;
		const gchar* _tmp93_;
		const gchar* _tmp94_;
		LxsessionLxsessionConfigKeyFile* _tmp99_;
		const gchar* _tmp100_;
		const gchar* _tmp101_;
		LxsessionLxsessionConfigKeyFile* _tmp119_;
		const gchar* _tmp120_;
		const gchar* _tmp121_;
		LxsessionLxsessionConfigKeyFile* _tmp139_;
		const gchar* _tmp140_;
		const gchar* _tmp141_;
		LxsessionLxsessionConfigKeyFile* _tmp146_;
		const gchar* _tmp147_;
		const gchar* _tmp148_;
		LxsessionLxsessionConfigKeyFile* _tmp156_;
		const gchar* _tmp157_;
		const gchar* _tmp158_;
		LxsessionLxsessionConfigKeyFile* _tmp163_;
		const gchar* _tmp164_;
		const gchar* _tmp165_;
		LxsessionLxsessionConfigKeyFile* _tmp173_;
		const gchar* _tmp174_;
		const gchar* _tmp175_;
		LxsessionLxsessionConfigKeyFile* _tmp183_;
		const gchar* _tmp184_;
		const gchar* _tmp185_;
		LxsessionLxsessionConfigKeyFile* _tmp193_;
		const gchar* _tmp194_;
		const gchar* _tmp195_;
		LxsessionLxsessionAutostartConfig* _tmp203_;
		LxsessionLxsessionAutostartConfig* _auto_;
		LxsessionLxsessionAutostartConfig* _tmp204_;
		LxsessionLxsessionConfigKeyFile* _tmp205_;
		const gchar* _tmp206_;
		const gchar* _tmp207_;
		_tmp78_ = lxsession_global_settings;
		_tmp79_ = lxsession_lxsession_config_get_panel_command ((LxsessionLxsessionConfig*) _tmp78_);
		_tmp80_ = _tmp79_;
		if (_tmp80_ != NULL) {
			LxsessionPanelApp* _tmp81_;
			LxsessionPanelApp* panel;
			LxsessionPanelApp* _tmp82_;
			LxsessionPanelApp* _tmp83_;
			LxsessionPanelApp* _tmp84_;
			_tmp81_ = lxsession_panel_app_new ();
			panel = _tmp81_;
			_tmp82_ = panel;
			_tmp83_ = _g_object_ref0 (_tmp82_);
			_g_object_unref0 (lxsession_global_panel);
			lxsession_global_panel = _tmp83_;
			_tmp84_ = lxsession_global_panel;
			lxsession_app_object_launch ((LxsessionAppObject*) _tmp84_);
			_g_object_unref0 (panel);
		}
		_tmp85_ = lxsession_global_settings;
		_tmp86_ = lxsession_lxsession_config_get_dock_command ((LxsessionLxsessionConfig*) _tmp85_);
		_tmp87_ = _tmp86_;
		if (_tmp87_ != NULL) {
			LxsessionDockApp* _tmp88_;
			LxsessionDockApp* dock;
			LxsessionDockApp* _tmp89_;
			LxsessionDockApp* _tmp90_;
			LxsessionDockApp* _tmp91_;
			_tmp88_ = lxsession_dock_app_new ();
			dock = _tmp88_;
			_tmp89_ = dock;
			_tmp90_ = _g_object_ref0 (_tmp89_);
			_g_object_unref0 (lxsession_global_dock);
			lxsession_global_dock = _tmp90_;
			_tmp91_ = lxsession_global_dock;
			lxsession_app_object_launch ((LxsessionAppObject*) _tmp91_);
			_g_object_unref0 (dock);
		}
		_tmp92_ = lxsession_global_settings;
		_tmp93_ = lxsession_lxsession_config_get_screensaver_command ((LxsessionLxsessionConfig*) _tmp92_);
		_tmp94_ = _tmp93_;
		if (_tmp94_ != NULL) {
			LxsessionScreensaverApp* _tmp95_;
			LxsessionScreensaverApp* screensaver;
			LxsessionScreensaverApp* _tmp96_;
			LxsessionScreensaverApp* _tmp97_;
			LxsessionScreensaverApp* _tmp98_;
			_tmp95_ = lxsession_screensaver_app_new ();
			screensaver = _tmp95_;
			_tmp96_ = screensaver;
			_tmp97_ = _g_object_ref0 (_tmp96_);
			_g_object_unref0 (lxsession_global_screensaver);
			lxsession_global_screensaver = _tmp97_;
			_tmp98_ = lxsession_global_screensaver;
			lxsession_app_object_launch ((LxsessionAppObject*) _tmp98_);
			_g_object_unref0 (screensaver);
		}
		_tmp99_ = lxsession_global_settings;
		_tmp100_ = lxsession_lxsession_config_get_power_manager_command ((LxsessionLxsessionConfig*) _tmp99_);
		_tmp101_ = _tmp100_;
		if (_tmp101_ != NULL) {
			LxsessionLxsessionConfigKeyFile* _tmp102_;
			const gchar* _tmp103_;
			const gchar* _tmp104_;
			_tmp102_ = lxsession_global_settings;
			_tmp103_ = lxsession_lxsession_config_get_laptop_mode ((LxsessionLxsessionConfig*) _tmp102_);
			_tmp104_ = _tmp103_;
			if (g_strcmp0 (_tmp104_, "unknown") == 0) {
				gboolean _tmp105_ = FALSE;
				gboolean state;
				gchar* _tmp106_;
				gchar* state_text;
				gboolean _tmp107_;
				LxsessionLxSignals* _tmp109_;
				const gchar* _tmp110_;
				LxsessionPowerManagerApp* _tmp111_;
				LxsessionPowerManagerApp* powermanager;
				LxsessionPowerManagerApp* _tmp112_;
				LxsessionPowerManagerApp* _tmp113_;
				LxsessionPowerManagerApp* _tmp114_;
				_tmp105_ = lxsession_detect_laptop ();
				state = _tmp105_;
				_tmp106_ = g_strdup ("no");
				state_text = _tmp106_;
				_tmp107_ = state;
				if (_tmp107_ == TRUE) {
					gchar* _tmp108_;
					_tmp108_ = g_strdup ("yes");
					_g_free0 (state_text);
					state_text = _tmp108_;
				}
				_tmp109_ = lxsession_global_sig;
				_tmp110_ = state_text;
				g_signal_emit_by_name (_tmp109_, "request-laptop-mode-set", _tmp110_, "State", "laptop_mode", NULL);
				_tmp111_ = lxsession_power_manager_app_new ();
				powermanager = _tmp111_;
				_tmp112_ = powermanager;
				_tmp113_ = _g_object_ref0 (_tmp112_);
				_g_object_unref0 (lxsession_global_power_manager);
				lxsession_global_power_manager = _tmp113_;
				_tmp114_ = lxsession_global_power_manager;
				lxsession_app_object_launch ((LxsessionAppObject*) _tmp114_);
				_g_object_unref0 (powermanager);
				_g_free0 (state_text);
			} else {
				LxsessionPowerManagerApp* _tmp115_;
				LxsessionPowerManagerApp* powermanager;
				LxsessionPowerManagerApp* _tmp116_;
				LxsessionPowerManagerApp* _tmp117_;
				LxsessionPowerManagerApp* _tmp118_;
				_tmp115_ = lxsession_power_manager_app_new ();
				powermanager = _tmp115_;
				_tmp116_ = powermanager;
				_tmp117_ = _g_object_ref0 (_tmp116_);
				_g_object_unref0 (lxsession_global_power_manager);
				lxsession_global_power_manager = _tmp117_;
				_tmp118_ = lxsession_global_power_manager;
				lxsession_app_object_launch ((LxsessionAppObject*) _tmp118_);
				_g_object_unref0 (powermanager);
			}
		}
		_tmp119_ = lxsession_global_settings;
		_tmp120_ = lxsession_lxsession_config_get_network_gui_command ((LxsessionLxsessionConfig*) _tmp119_);
		_tmp121_ = _tmp120_;
		if (_tmp121_ != NULL) {
			LxsessionLxsessionConfigKeyFile* _tmp122_;
			const gchar* _tmp123_;
			const gchar* _tmp124_;
			_tmp122_ = lxsession_global_settings;
			_tmp123_ = lxsession_lxsession_config_get_laptop_mode ((LxsessionLxsessionConfig*) _tmp122_);
			_tmp124_ = _tmp123_;
			if (g_strcmp0 (_tmp124_, "unknown") == 0) {
				gboolean _tmp125_ = FALSE;
				gboolean state;
				gchar* _tmp126_;
				gchar* state_text;
				gboolean _tmp127_;
				LxsessionLxSignals* _tmp129_;
				const gchar* _tmp130_;
				LxsessionNetworkGuiApp* _tmp131_;
				LxsessionNetworkGuiApp* networkgui;
				LxsessionNetworkGuiApp* _tmp132_;
				LxsessionNetworkGuiApp* _tmp133_;
				LxsessionNetworkGuiApp* _tmp134_;
				_tmp125_ = lxsession_detect_laptop ();
				state = _tmp125_;
				_tmp126_ = g_strdup ("no");
				state_text = _tmp126_;
				_tmp127_ = state;
				if (_tmp127_ == TRUE) {
					gchar* _tmp128_;
					_tmp128_ = g_strdup ("yes");
					_g_free0 (state_text);
					state_text = _tmp128_;
				}
				_tmp129_ = lxsession_global_sig;
				_tmp130_ = state_text;
				g_signal_emit_by_name (_tmp129_, "request-laptop-mode-set", _tmp130_, "State", "laptop_mode", NULL);
				_tmp131_ = lxsession_network_gui_app_new ();
				networkgui = _tmp131_;
				_tmp132_ = networkgui;
				_tmp133_ = _g_object_ref0 (_tmp132_);
				_g_object_unref0 (lxsession_global_network_gui);
				lxsession_global_network_gui = _tmp133_;
				_tmp134_ = lxsession_global_network_gui;
				lxsession_app_object_launch ((LxsessionAppObject*) _tmp134_);
				_g_object_unref0 (networkgui);
				_g_free0 (state_text);
			} else {
				LxsessionNetworkGuiApp* _tmp135_;
				LxsessionNetworkGuiApp* networkgui;
				LxsessionNetworkGuiApp* _tmp136_;
				LxsessionNetworkGuiApp* _tmp137_;
				LxsessionNetworkGuiApp* _tmp138_;
				_tmp135_ = lxsession_network_gui_app_new ();
				networkgui = _tmp135_;
				_tmp136_ = networkgui;
				_tmp137_ = _g_object_ref0 (_tmp136_);
				_g_object_unref0 (lxsession_global_network_gui);
				lxsession_global_network_gui = _tmp137_;
				_tmp138_ = lxsession_global_network_gui;
				lxsession_app_object_launch ((LxsessionAppObject*) _tmp138_);
				_g_object_unref0 (networkgui);
			}
		}
		_tmp139_ = lxsession_global_settings;
		_tmp140_ = lxsession_lxsession_config_get_desktop_command ((LxsessionLxsessionConfig*) _tmp139_);
		_tmp141_ = _tmp140_;
		if (_tmp141_ != NULL) {
			LxsessionDesktopApp* _tmp142_;
			LxsessionDesktopApp* desktopmanager;
			LxsessionDesktopApp* _tmp143_;
			LxsessionDesktopApp* _tmp144_;
			LxsessionDesktopApp* _tmp145_;
			_tmp142_ = lxsession_desktop_app_new ();
			desktopmanager = _tmp142_;
			_tmp143_ = desktopmanager;
			_tmp144_ = _g_object_ref0 (_tmp143_);
			_g_object_unref0 (lxsession_global_desktop);
			lxsession_global_desktop = _tmp144_;
			_tmp145_ = lxsession_global_desktop;
			lxsession_app_object_launch ((LxsessionAppObject*) _tmp145_);
			_g_object_unref0 (desktopmanager);
		}
		_tmp146_ = lxsession_global_settings;
		_tmp147_ = lxsession_lxsession_config_get_composite_manager_autostart ((LxsessionLxsessionConfig*) _tmp146_);
		_tmp148_ = _tmp147_;
		if (g_strcmp0 (_tmp148_, "true") == 0) {
			LxsessionLxsessionConfigKeyFile* _tmp149_;
			const gchar* _tmp150_;
			const gchar* _tmp151_;
			_tmp149_ = lxsession_global_settings;
			_tmp150_ = lxsession_lxsession_config_get_composite_manager_command ((LxsessionLxsessionConfig*) _tmp149_);
			_tmp151_ = _tmp150_;
			if (_tmp151_ != NULL) {
				LxsessionCompositeManagerApp* _tmp152_;
				LxsessionCompositeManagerApp* compositemanager;
				LxsessionCompositeManagerApp* _tmp153_;
				LxsessionCompositeManagerApp* _tmp154_;
				LxsessionCompositeManagerApp* _tmp155_;
				_tmp152_ = lxsession_composite_manager_app_new ();
				compositemanager = _tmp152_;
				_tmp153_ = compositemanager;
				_tmp154_ = _g_object_ref0 (_tmp153_);
				_g_object_unref0 (lxsession_global_composite_manager);
				lxsession_global_composite_manager = _tmp154_;
				_tmp155_ = lxsession_global_composite_manager;
				lxsession_app_object_launch ((LxsessionAppObject*) _tmp155_);
				_g_object_unref0 (compositemanager);
			}
		}
		_tmp156_ = lxsession_global_settings;
		_tmp157_ = lxsession_lxsession_config_get_polkit_command ((LxsessionLxsessionConfig*) _tmp156_);
		_tmp158_ = _tmp157_;
		if (_tmp158_ != NULL) {
			LxsessionPolkitApp* _tmp159_;
			LxsessionPolkitApp* securitypolkit;
			LxsessionPolkitApp* _tmp160_;
			LxsessionPolkitApp* _tmp161_;
			LxsessionPolkitApp* _tmp162_;
			_tmp159_ = lxsession_polkit_app_new ();
			securitypolkit = _tmp159_;
			_tmp160_ = securitypolkit;
			_tmp161_ = _g_object_ref0 (_tmp160_);
			_g_object_unref0 (lxsession_global_polkit);
			lxsession_global_polkit = _tmp161_;
			_tmp162_ = lxsession_global_polkit;
			lxsession_app_object_launch ((LxsessionAppObject*) _tmp162_);
			_g_object_unref0 (securitypolkit);
		}
		_tmp163_ = lxsession_global_settings;
		_tmp164_ = lxsession_lxsession_config_get_launcher_manager_autostart ((LxsessionLxsessionConfig*) _tmp163_);
		_tmp165_ = _tmp164_;
		if (g_strcmp0 (_tmp165_, "true") == 0) {
			LxsessionLxsessionConfigKeyFile* _tmp166_;
			const gchar* _tmp167_;
			const gchar* _tmp168_;
			_tmp166_ = lxsession_global_settings;
			_tmp167_ = lxsession_lxsession_config_get_launcher_manager_command ((LxsessionLxsessionConfig*) _tmp166_);
			_tmp168_ = _tmp167_;
			if (_tmp168_ != NULL) {
				LxsessionLauncherManagerApp* _tmp169_;
				LxsessionLauncherManagerApp* launcher;
				LxsessionLauncherManagerApp* _tmp170_;
				LxsessionLauncherManagerApp* _tmp171_;
				LxsessionLauncherManagerApp* _tmp172_;
				_tmp169_ = lxsession_launcher_manager_app_new ();
				launcher = _tmp169_;
				_tmp170_ = launcher;
				_tmp171_ = _g_object_ref0 (_tmp170_);
				_g_object_unref0 (lxsession_global_launcher_manager);
				lxsession_global_launcher_manager = _tmp171_;
				_tmp172_ = lxsession_global_launcher_manager;
				lxsession_launcher_manager_app_autostart_launch (_tmp172_);
				_g_object_unref0 (launcher);
			}
		}
		_tmp173_ = lxsession_global_settings;
		_tmp174_ = lxsession_lxsession_config_get_im1_autostart ((LxsessionLxsessionConfig*) _tmp173_);
		_tmp175_ = _tmp174_;
		if (g_strcmp0 (_tmp175_, "true") == 0) {
			LxsessionLxsessionConfigKeyFile* _tmp176_;
			const gchar* _tmp177_;
			const gchar* _tmp178_;
			_tmp176_ = lxsession_global_settings;
			_tmp177_ = lxsession_lxsession_config_get_im1_command ((LxsessionLxsessionConfig*) _tmp176_);
			_tmp178_ = _tmp177_;
			if (_tmp178_ != NULL) {
				LxsessionIM1App* _tmp179_;
				LxsessionIM1App* im1;
				LxsessionIM1App* _tmp180_;
				LxsessionIM1App* _tmp181_;
				LxsessionIM1App* _tmp182_;
				_tmp179_ = lxsession_im1_app_new ();
				im1 = _tmp179_;
				_tmp180_ = im1;
				_tmp181_ = _g_object_ref0 (_tmp180_);
				_g_object_unref0 (lxsession_global_im1);
				lxsession_global_im1 = _tmp181_;
				_tmp182_ = lxsession_global_im1;
				lxsession_app_object_launch ((LxsessionAppObject*) _tmp182_);
				_g_object_unref0 (im1);
			}
		}
		_tmp183_ = lxsession_global_settings;
		_tmp184_ = lxsession_lxsession_config_get_im2_autostart ((LxsessionLxsessionConfig*) _tmp183_);
		_tmp185_ = _tmp184_;
		if (g_strcmp0 (_tmp185_, "true") == 0) {
			LxsessionLxsessionConfigKeyFile* _tmp186_;
			const gchar* _tmp187_;
			const gchar* _tmp188_;
			_tmp186_ = lxsession_global_settings;
			_tmp187_ = lxsession_lxsession_config_get_im2_command ((LxsessionLxsessionConfig*) _tmp186_);
			_tmp188_ = _tmp187_;
			if (_tmp188_ != NULL) {
				LxsessionIM2App* _tmp189_;
				LxsessionIM2App* im2;
				LxsessionIM2App* _tmp190_;
				LxsessionIM2App* _tmp191_;
				LxsessionIM2App* _tmp192_;
				_tmp189_ = lxsession_im2_app_new ();
				im2 = _tmp189_;
				_tmp190_ = im2;
				_tmp191_ = _g_object_ref0 (_tmp190_);
				_g_object_unref0 (lxsession_global_im2);
				lxsession_global_im2 = _tmp191_;
				_tmp192_ = lxsession_global_im2;
				lxsession_app_object_launch ((LxsessionAppObject*) _tmp192_);
				_g_object_unref0 (im2);
			}
		}
		_tmp193_ = lxsession_global_settings;
		_tmp194_ = lxsession_lxsession_config_get_widget1_autostart ((LxsessionLxsessionConfig*) _tmp193_);
		_tmp195_ = _tmp194_;
		if (g_strcmp0 (_tmp195_, "true") == 0) {
			LxsessionLxsessionConfigKeyFile* _tmp196_;
			const gchar* _tmp197_;
			const gchar* _tmp198_;
			_tmp196_ = lxsession_global_settings;
			_tmp197_ = lxsession_lxsession_config_get_widget1_command ((LxsessionLxsessionConfig*) _tmp196_);
			_tmp198_ = _tmp197_;
			if (_tmp198_ != NULL) {
				LxsessionWidgetApp* _tmp199_;
				LxsessionWidgetApp* widget1;
				LxsessionWidgetApp* _tmp200_;
				LxsessionWidgetApp* _tmp201_;
				LxsessionWidgetApp* _tmp202_;
				_tmp199_ = lxsession_widget_app_new ();
				widget1 = _tmp199_;
				_tmp200_ = widget1;
				_tmp201_ = _g_object_ref0 (_tmp200_);
				_g_object_unref0 (lxsession_global_widget1);
				lxsession_global_widget1 = _tmp201_;
				_tmp202_ = lxsession_global_widget1;
				lxsession_app_object_launch ((LxsessionAppObject*) _tmp202_);
				_g_object_unref0 (widget1);
			}
		}
		_tmp203_ = lxsession_lxsession_autostart_config_new ();
		_auto_ = _tmp203_;
		_tmp204_ = _auto_;
		lxsession_lxsession_autostart_config_start_applications (_tmp204_);
		_tmp205_ = lxsession_global_settings;
		_tmp206_ = lxsession_lxsession_config_get_disable_autostart ((LxsessionLxsessionConfig*) _tmp205_);
		_tmp207_ = _tmp206_;
		if (g_strcmp0 (_tmp207_, "config-only") == 0) {
		} else {
			const gchar* _tmp208_;
			_tmp208_ = lxsession_main_desktop_environnement;
			xdg_autostart (_tmp208_);
		}
		_g_object_unref0 (_auto_);
	}
	_tmp209_ = lxsession_global_settings;
	_tmp210_ = lxsession_lxsession_config_get_clipboard_command ((LxsessionLxsessionConfig*) _tmp209_);
	_tmp211_ = _tmp210_;
	if (_tmp211_ != NULL) {
		LxsessionLxsessionConfigKeyFile* _tmp212_;
		LxsessionClipboardOption* _tmp213_;
		LxsessionClipboardOption* clipboard;
		LxsessionClipboardOption* _tmp214_;
		LxsessionClipboardOption* _tmp215_;
		LxsessionClipboardOption* _tmp216_;
		_tmp212_ = lxsession_global_settings;
		_tmp213_ = lxsession_clipboard_option_new ((LxsessionLxsessionConfig*) _tmp212_);
		clipboard = _tmp213_;
		_tmp214_ = clipboard;
		_tmp215_ = _g_object_ref0 (_tmp214_);
		_g_object_unref0 (lxsession_global_clipboard);
		lxsession_global_clipboard = _tmp215_;
		_tmp216_ = lxsession_global_clipboard;
		lxsession_option_activate ((LxsessionOption*) _tmp216_);
		_g_object_unref0 (clipboard);
	}
	_tmp217_ = lxsession_global_settings;
	_tmp218_ = lxsession_lxsession_config_get_keymap_mode ((LxsessionLxsessionConfig*) _tmp217_);
	_tmp219_ = _tmp218_;
	g_message ("main.vala:391: Check keymap_mode %s", _tmp219_);
	_tmp220_ = lxsession_global_settings;
	_tmp221_ = lxsession_lxsession_config_get_keymap_mode ((LxsessionLxsessionConfig*) _tmp220_);
	_tmp222_ = _tmp221_;
	if (_tmp222_ != NULL) {
		LxsessionLxsessionConfigKeyFile* _tmp223_;
		LxsessionKeymapOption* _tmp224_;
		LxsessionKeymapOption* keymap;
		LxsessionKeymapOption* _tmp225_;
		LxsessionKeymapOption* _tmp226_;
		LxsessionKeymapOption* _tmp227_;
		g_message ("main.vala:394: Create Option Keymap");
		_tmp223_ = lxsession_global_settings;
		_tmp224_ = lxsession_keymap_option_new ((LxsessionLxsessionConfig*) _tmp223_);
		keymap = _tmp224_;
		_tmp225_ = keymap;
		_tmp226_ = _g_object_ref0 (_tmp225_);
		_g_object_unref0 (lxsession_global_keymap);
		lxsession_global_keymap = _tmp226_;
		_tmp227_ = lxsession_global_keymap;
		lxsession_option_activate ((LxsessionOption*) _tmp227_);
		_g_object_unref0 (keymap);
	}
	_tmp228_ = lxsession_global_settings;
	_tmp229_ = lxsession_lxsession_config_get_xrandr_mode ((LxsessionLxsessionConfig*) _tmp228_);
	_tmp230_ = _tmp229_;
	if (_tmp230_ != NULL) {
		LxsessionLxsessionConfigKeyFile* _tmp231_;
		LxsessionXrandrOption* _tmp232_;
		LxsessionXrandrOption* xrandr;
		LxsessionXrandrOption* _tmp233_;
		LxsessionXrandrOption* _tmp234_;
		LxsessionXrandrOption* _tmp235_;
		_tmp231_ = lxsession_global_settings;
		_tmp232_ = lxsession_xrandr_option_new ((LxsessionLxsessionConfig*) _tmp231_);
		xrandr = _tmp232_;
		_tmp233_ = xrandr;
		_tmp234_ = _g_object_ref0 (_tmp233_);
		_g_object_unref0 (lxsession_global_xrandr);
		lxsession_global_xrandr = _tmp234_;
		_tmp235_ = xrandr;
		lxsession_option_activate ((LxsessionOption*) _tmp235_);
		_g_object_unref0 (xrandr);
	}
	_tmp236_ = lxsession_global_settings;
	_tmp237_ = lxsession_lxsession_config_get_security_keyring ((LxsessionLxsessionConfig*) _tmp236_);
	_tmp238_ = _tmp237_;
	if (_tmp238_ != NULL) {
		LxsessionLxsessionConfigKeyFile* _tmp239_;
		LxsessionKeyringOption* _tmp240_;
		LxsessionKeyringOption* keyring;
		LxsessionKeyringOption* _tmp241_;
		LxsessionKeyringOption* _tmp242_;
		LxsessionKeyringOption* _tmp243_;
		_tmp239_ = lxsession_global_settings;
		_tmp240_ = lxsession_keyring_option_new ((LxsessionLxsessionConfig*) _tmp239_);
		keyring = _tmp240_;
		_tmp241_ = keyring;
		_tmp242_ = _g_object_ref0 (_tmp241_);
		_g_object_unref0 (lxsession_global_keyring);
		lxsession_global_keyring = _tmp242_;
		_tmp243_ = lxsession_global_keyring;
		lxsession_keyring_option_activate (_tmp243_);
		_g_object_unref0 (keyring);
	}
	_tmp244_ = lxsession_global_settings;
	_tmp245_ = lxsession_lxsession_config_get_a11y_type ((LxsessionLxsessionConfig*) _tmp244_);
	_tmp246_ = _tmp245_;
	if (g_strcmp0 (_tmp246_, "true") == 0) {
		LxsessionLxsessionConfigKeyFile* _tmp247_;
		LxsessionA11yOption* _tmp248_;
		LxsessionA11yOption* a11y;
		LxsessionA11yOption* _tmp249_;
		LxsessionA11yOption* _tmp250_;
		LxsessionA11yOption* _tmp251_;
		_tmp247_ = lxsession_global_settings;
		_tmp248_ = lxsession_a11y_option_new ((LxsessionLxsessionConfig*) _tmp247_);
		a11y = _tmp248_;
		_tmp249_ = a11y;
		_tmp250_ = _g_object_ref0 (_tmp249_);
		_g_object_unref0 (lxsession_global_a11y);
		lxsession_global_a11y = _tmp250_;
		_tmp251_ = lxsession_global_a11y;
		lxsession_a11y_option_activate (_tmp251_);
		_g_object_unref0 (a11y);
	}
	_tmp252_ = lxsession_global_settings;
	_tmp253_ = lxsession_lxsession_config_get_proxy_http ((LxsessionLxsessionConfig*) _tmp252_);
	_tmp254_ = _tmp253_;
	if (_tmp254_ != NULL) {
		LxsessionLxsessionConfigKeyFile* _tmp255_;
		LxsessionProxyOption* _tmp256_;
		LxsessionProxyOption* proxy;
		LxsessionProxyOption* _tmp257_;
		LxsessionProxyOption* _tmp258_;
		LxsessionProxyOption* _tmp259_;
		_tmp255_ = lxsession_global_settings;
		_tmp256_ = lxsession_proxy_option_new ((LxsessionLxsessionConfig*) _tmp255_);
		proxy = _tmp256_;
		_tmp257_ = proxy;
		_tmp258_ = _g_object_ref0 (_tmp257_);
		_g_object_unref0 (lxsession_global_proxy);
		lxsession_global_proxy = _tmp258_;
		_tmp259_ = lxsession_global_proxy;
		lxsession_proxy_option_activate (_tmp259_);
		_g_object_unref0 (proxy);
	}
	_tmp260_ = lxsession_global_settings;
	_tmp261_ = lxsession_lxsession_config_get_updates_type ((LxsessionLxsessionConfig*) _tmp260_);
	_tmp262_ = _tmp261_;
	if (_tmp262_ != NULL) {
		LxsessionLxsessionConfigKeyFile* _tmp263_;
		LxsessionUpdatesOption* _tmp264_;
		LxsessionUpdatesOption* updates;
		LxsessionUpdatesOption* _tmp265_;
		LxsessionUpdatesOption* _tmp266_;
		LxsessionUpdatesOption* _tmp267_;
		_tmp263_ = lxsession_global_settings;
		_tmp264_ = lxsession_updates_option_new ((LxsessionLxsessionConfig*) _tmp263_);
		updates = _tmp264_;
		_tmp265_ = updates;
		_tmp266_ = _g_object_ref0 (_tmp265_);
		_g_object_unref0 (lxsession_global_updates);
		lxsession_global_updates = _tmp266_;
		_tmp267_ = lxsession_global_updates;
		lxsession_updates_option_activate (_tmp267_);
		_g_object_unref0 (updates);
	}
	_tmp268_ = lxsession_global_settings;
	_tmp269_ = lxsession_lxsession_config_get_upstart_user_session ((LxsessionLxsessionConfig*) _tmp268_);
	_tmp270_ = _tmp269_;
	if (g_strcmp0 (_tmp270_, "true") == 0) {
		LxsessionLxsessionConfigKeyFile* _tmp271_;
		LxsessionUpstartUserSessionOption* _tmp272_;
		LxsessionUpstartUserSessionOption* upstart_session;
		LxsessionUpstartUserSessionOption* _tmp273_;
		LxsessionUpstartUserSessionOption* _tmp274_;
		LxsessionUpstartUserSessionOption* _tmp275_;
		_tmp271_ = lxsession_global_settings;
		_tmp272_ = lxsession_upstart_user_session_option_new ((LxsessionLxsessionConfig*) _tmp271_);
		upstart_session = _tmp272_;
		_tmp273_ = upstart_session;
		_tmp274_ = _g_object_ref0 (_tmp273_);
		_g_object_unref0 (lxsession_global_upstart_session);
		lxsession_global_upstart_session = _tmp274_;
		_tmp275_ = lxsession_global_upstart_session;
		lxsession_upstart_user_session_option_activate (_tmp275_);
		_g_object_unref0 (upstart_session);
	}
	_tmp276_ = lxsession_global_settings;
	_tmp277_ = lxsession_lxsession_config_get_dbus_lxde ((LxsessionLxsessionConfig*) _tmp276_);
	_tmp278_ = _tmp277_;
	if (g_strcmp0 (_tmp278_, "true") == 0) {
		g_bus_own_name_with_closures (G_BUS_TYPE_SESSION, "org.lxde.SessionManager", G_BUS_NAME_OWNER_FLAGS_NONE, (GClosure*) ((_lxsession_on_bus_aquired_gbus_acquired_callback == NULL) ? NULL : g_cclosure_new ((GCallback) _lxsession_on_bus_aquired_gbus_acquired_callback, NULL, NULL)), (GClosure*) ((____lambda2__gbus_name_acquired_callback == NULL) ? NULL : g_cclosure_new ((GCallback) ____lambda2__gbus_name_acquired_callback, NULL, NULL)), (GClosure*) ((____lambda3__gbus_name_lost_callback == NULL) ? NULL : g_cclosure_new ((GCallback) ____lambda3__gbus_name_lost_callback, NULL, NULL)));
	}
	_tmp279_ = lxsession_global_settings;
	_tmp280_ = lxsession_lxsession_config_get_dbus_gnome ((LxsessionLxsessionConfig*) _tmp279_);
	_tmp281_ = _tmp280_;
	if (g_strcmp0 (_tmp281_, "true") == 0) {
		g_bus_own_name_with_closures (G_BUS_TYPE_SESSION, "org.gnome.SessionManager", G_BUS_NAME_OWNER_FLAGS_NONE, (GClosure*) ((_lxsession_on_gnome_bus_aquired_gbus_acquired_callback == NULL) ? NULL : g_cclosure_new ((GCallback) _lxsession_on_gnome_bus_aquired_gbus_acquired_callback, NULL, NULL)), (GClosure*) ((____lambda4__gbus_name_acquired_callback == NULL) ? NULL : g_cclosure_new ((GCallback) ____lambda4__gbus_name_acquired_callback, NULL, NULL)), (GClosure*) ((____lambda5__gbus_name_lost_callback == NULL) ? NULL : g_cclosure_new ((GCallback) ____lambda5__gbus_name_lost_callback, NULL, NULL)));
	}
	_tmp282_ = g_main_loop_new (NULL, FALSE);
	_tmp283_ = _tmp282_;
	g_main_loop_run (_tmp283_);
	_g_main_loop_unref0 (_tmp283_);
	_tmp284_ = lxsession_global_clipboard;
	if (_tmp284_ != NULL) {
		LxsessionClipboardOption* _tmp285_;
		_tmp285_ = lxsession_global_clipboard;
		lxsession_clipboard_option_desactivate (_tmp285_);
	}
	_tmp286_ = lxsession_global_settings;
	_tmp287_ = lxsession_lxsession_config_get_polkit_command ((LxsessionLxsessionConfig*) _tmp286_);
	_tmp288_ = _tmp287_;
	if (_tmp288_ != NULL) {
		LxsessionPolkitApp* _tmp289_;
		LxsessionPolkitApp* _tmp290_;
		_tmp289_ = lxsession_global_polkit;
		lxsession_polkit_app_deactivate (_tmp289_);
		_tmp290_ = lxsession_global_polkit;
		lxsession_app_object_stop ((LxsessionAppObject*) _tmp290_);
	}
	_tmp291_ = lxsession_global_panel;
	if (_tmp291_ != NULL) {
		LxsessionPanelApp* _tmp292_;
		_tmp292_ = lxsession_global_panel;
		lxsession_app_object_stop ((LxsessionAppObject*) _tmp292_);
	}
	_tmp293_ = lxsession_global_dock;
	if (_tmp293_ != NULL) {
		LxsessionDockApp* _tmp294_;
		_tmp294_ = lxsession_global_dock;
		lxsession_app_object_stop ((LxsessionAppObject*) _tmp294_);
	}
	_tmp295_ = lxsession_global_windows_manager;
	if (_tmp295_ != NULL) {
		LxsessionWindowsManagerApp* _tmp296_;
		_tmp296_ = lxsession_global_windows_manager;
		lxsession_app_object_stop ((LxsessionAppObject*) _tmp296_);
	}
	_tmp297_ = lxsession_global_desktop;
	if (_tmp297_ != NULL) {
		LxsessionDesktopApp* _tmp298_;
		_tmp298_ = lxsession_global_desktop;
		lxsession_app_object_stop ((LxsessionAppObject*) _tmp298_);
	}
	_tmp299_ = lxsession_global_polkit;
	if (_tmp299_ != NULL) {
		LxsessionPolkitApp* _tmp300_;
		_tmp300_ = lxsession_global_polkit;
		lxsession_app_object_stop ((LxsessionAppObject*) _tmp300_);
	}
	_tmp301_ = lxsession_global_screensaver;
	if (_tmp301_ != NULL) {
		LxsessionScreensaverApp* _tmp302_;
		_tmp302_ = lxsession_global_screensaver;
		lxsession_app_object_stop ((LxsessionAppObject*) _tmp302_);
	}
	_tmp303_ = lxsession_global_power_manager;
	if (_tmp303_ != NULL) {
		LxsessionPowerManagerApp* _tmp304_;
		_tmp304_ = lxsession_global_power_manager;
		lxsession_app_object_stop ((LxsessionAppObject*) _tmp304_);
	}
	_tmp305_ = lxsession_global_network_gui;
	if (_tmp305_ != NULL) {
		LxsessionNetworkGuiApp* _tmp306_;
		_tmp306_ = lxsession_global_network_gui;
		lxsession_app_object_stop ((LxsessionAppObject*) _tmp306_);
	}
	_tmp307_ = lxsession_global_composite_manager;
	if (_tmp307_ != NULL) {
		LxsessionCompositeManagerApp* _tmp308_;
		_tmp308_ = lxsession_global_composite_manager;
		lxsession_app_object_stop ((LxsessionAppObject*) _tmp308_);
	}
	result = 0;
	_g_free0 (conffiles_conf);
	_g_object_unref0 (environment);
	_g_object_unref0 (sig);
	_g_free0 (log_path);
	_g_object_unref0 (dir_log);
	_g_free0 (log_directory);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return lxsession_main_main (argv, argc);
}


LxsessionMain* lxsession_main_construct (GType object_type) {
	LxsessionMain * self = NULL;
	self = (LxsessionMain*) g_object_new (object_type, NULL);
	return self;
}


LxsessionMain* lxsession_main_new (void) {
	return lxsession_main_construct (LXSESSION_TYPE_MAIN);
}


static void lxsession_main_class_init (LxsessionMainClass * klass) {
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	lxsession_main_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = lxsession_main_finalize;
	_tmp0_ = g_strdup ("LXDE");
	lxsession_main_session = _tmp0_;
	_tmp1_ = g_strdup ("LXDE");
	lxsession_main_desktop_environnement = _tmp1_;
	_tmp2_ = g_strdup ("");
	lxsession_main_compatibility = _tmp2_;
}


static void lxsession_main_instance_init (LxsessionMain * self) {
}


static void lxsession_main_finalize (GObject* obj) {
	LxsessionMain * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, LXSESSION_TYPE_MAIN, LxsessionMain);
	G_OBJECT_CLASS (lxsession_main_parent_class)->finalize (obj);
}


GType lxsession_main_get_type (void) {
	static volatile gsize lxsession_main_type_id__volatile = 0;
	if (g_once_init_enter (&lxsession_main_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LxsessionMainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) lxsession_main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LxsessionMain), 0, (GInstanceInitFunc) lxsession_main_instance_init, NULL };
		GType lxsession_main_type_id;
		lxsession_main_type_id = g_type_register_static (G_TYPE_OBJECT, "LxsessionMain", &g_define_type_info, 0);
		g_once_init_leave (&lxsession_main_type_id__volatile, lxsession_main_type_id);
	}
	return lxsession_main_type_id__volatile;
}



