/* options.c generated by valac 0.18.1, the Vala compiler
 * generated from options.vala, do not modify */

/* 
 *      Copyright 2011 Julien Lavergne <gilir@ubuntu.com>
 *
 *      This program is free software; you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published by
 *      the Free Software Foundation; either version 2 of the License, or
 *      (at your option) any later version.
 *
 *      This program is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 *
 *      You should have received a copy of the GNU General Public License
 *      along with this program; if not, write to the Free Software
 *      Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 *      MA 02110-1301, USA.
 */
/* TODO Replace other utlity in the start script */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>


#define LXSESSION_TYPE_OPTION (lxsession_option_get_type ())
#define LXSESSION_OPTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_OPTION, LxsessionOption))
#define LXSESSION_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_OPTION, LxsessionOptionClass))
#define LXSESSION_IS_OPTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_OPTION))
#define LXSESSION_IS_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_OPTION))
#define LXSESSION_OPTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_OPTION, LxsessionOptionClass))

typedef struct _LxsessionOption LxsessionOption;
typedef struct _LxsessionOptionClass LxsessionOptionClass;
typedef struct _LxsessionOptionPrivate LxsessionOptionPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

#define LXSESSION_TYPE_LXSESSION_CONFIG (lxsession_lxsession_config_get_type ())
#define LXSESSION_LXSESSION_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_LXSESSION_CONFIG, LxsessionLxsessionConfig))
#define LXSESSION_LXSESSION_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_LXSESSION_CONFIG, LxsessionLxsessionConfigClass))
#define LXSESSION_IS_LXSESSION_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_LXSESSION_CONFIG))
#define LXSESSION_IS_LXSESSION_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_LXSESSION_CONFIG))
#define LXSESSION_LXSESSION_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_LXSESSION_CONFIG, LxsessionLxsessionConfigClass))

typedef struct _LxsessionLxsessionConfig LxsessionLxsessionConfig;
typedef struct _LxsessionLxsessionConfigClass LxsessionLxsessionConfigClass;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define LXSESSION_TYPE_KEYMAP_OPTION (lxsession_keymap_option_get_type ())
#define LXSESSION_KEYMAP_OPTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_KEYMAP_OPTION, LxsessionKeymapOption))
#define LXSESSION_KEYMAP_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_KEYMAP_OPTION, LxsessionKeymapOptionClass))
#define LXSESSION_IS_KEYMAP_OPTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_KEYMAP_OPTION))
#define LXSESSION_IS_KEYMAP_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_KEYMAP_OPTION))
#define LXSESSION_KEYMAP_OPTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_KEYMAP_OPTION, LxsessionKeymapOptionClass))

typedef struct _LxsessionKeymapOption LxsessionKeymapOption;
typedef struct _LxsessionKeymapOptionClass LxsessionKeymapOptionClass;
typedef struct _LxsessionKeymapOptionPrivate LxsessionKeymapOptionPrivate;
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))

#define LXSESSION_TYPE_XRANDR_OPTION (lxsession_xrandr_option_get_type ())
#define LXSESSION_XRANDR_OPTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_XRANDR_OPTION, LxsessionXrandrOption))
#define LXSESSION_XRANDR_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_XRANDR_OPTION, LxsessionXrandrOptionClass))
#define LXSESSION_IS_XRANDR_OPTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_XRANDR_OPTION))
#define LXSESSION_IS_XRANDR_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_XRANDR_OPTION))
#define LXSESSION_XRANDR_OPTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_XRANDR_OPTION, LxsessionXrandrOptionClass))

typedef struct _LxsessionXrandrOption LxsessionXrandrOption;
typedef struct _LxsessionXrandrOptionClass LxsessionXrandrOptionClass;
typedef struct _LxsessionXrandrOptionPrivate LxsessionXrandrOptionPrivate;

#define LXSESSION_TYPE_KEYRING_OPTION (lxsession_keyring_option_get_type ())
#define LXSESSION_KEYRING_OPTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_KEYRING_OPTION, LxsessionKeyringOption))
#define LXSESSION_KEYRING_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_KEYRING_OPTION, LxsessionKeyringOptionClass))
#define LXSESSION_IS_KEYRING_OPTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_KEYRING_OPTION))
#define LXSESSION_IS_KEYRING_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_KEYRING_OPTION))
#define LXSESSION_KEYRING_OPTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_KEYRING_OPTION, LxsessionKeyringOptionClass))

typedef struct _LxsessionKeyringOption LxsessionKeyringOption;
typedef struct _LxsessionKeyringOptionClass LxsessionKeyringOptionClass;
typedef struct _LxsessionKeyringOptionPrivate LxsessionKeyringOptionPrivate;

#define LXSESSION_TYPE_A11Y_OPTION (lxsession_a11y_option_get_type ())
#define LXSESSION_A11Y_OPTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_A11Y_OPTION, LxsessionA11yOption))
#define LXSESSION_A11Y_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_A11Y_OPTION, LxsessionA11yOptionClass))
#define LXSESSION_IS_A11Y_OPTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_A11Y_OPTION))
#define LXSESSION_IS_A11Y_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_A11Y_OPTION))
#define LXSESSION_A11Y_OPTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_A11Y_OPTION, LxsessionA11yOptionClass))

typedef struct _LxsessionA11yOption LxsessionA11yOption;
typedef struct _LxsessionA11yOptionClass LxsessionA11yOptionClass;
typedef struct _LxsessionA11yOptionPrivate LxsessionA11yOptionPrivate;

#define LXSESSION_TYPE_CLIPBOARD_OPTION (lxsession_clipboard_option_get_type ())
#define LXSESSION_CLIPBOARD_OPTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_CLIPBOARD_OPTION, LxsessionClipboardOption))
#define LXSESSION_CLIPBOARD_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_CLIPBOARD_OPTION, LxsessionClipboardOptionClass))
#define LXSESSION_IS_CLIPBOARD_OPTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_CLIPBOARD_OPTION))
#define LXSESSION_IS_CLIPBOARD_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_CLIPBOARD_OPTION))
#define LXSESSION_CLIPBOARD_OPTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_CLIPBOARD_OPTION, LxsessionClipboardOptionClass))

typedef struct _LxsessionClipboardOption LxsessionClipboardOption;
typedef struct _LxsessionClipboardOptionClass LxsessionClipboardOptionClass;
typedef struct _LxsessionClipboardOptionPrivate LxsessionClipboardOptionPrivate;

#define LXSESSION_TYPE_UPDATES_OPTION (lxsession_updates_option_get_type ())
#define LXSESSION_UPDATES_OPTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_UPDATES_OPTION, LxsessionUpdatesOption))
#define LXSESSION_UPDATES_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_UPDATES_OPTION, LxsessionUpdatesOptionClass))
#define LXSESSION_IS_UPDATES_OPTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_UPDATES_OPTION))
#define LXSESSION_IS_UPDATES_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_UPDATES_OPTION))
#define LXSESSION_UPDATES_OPTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_UPDATES_OPTION, LxsessionUpdatesOptionClass))

typedef struct _LxsessionUpdatesOption LxsessionUpdatesOption;
typedef struct _LxsessionUpdatesOptionClass LxsessionUpdatesOptionClass;
typedef struct _LxsessionUpdatesOptionPrivate LxsessionUpdatesOptionPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define LXSESSION_TYPE_UPSTART_USER_SESSION_OPTION (lxsession_upstart_user_session_option_get_type ())
#define LXSESSION_UPSTART_USER_SESSION_OPTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_UPSTART_USER_SESSION_OPTION, LxsessionUpstartUserSessionOption))
#define LXSESSION_UPSTART_USER_SESSION_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_UPSTART_USER_SESSION_OPTION, LxsessionUpstartUserSessionOptionClass))
#define LXSESSION_IS_UPSTART_USER_SESSION_OPTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_UPSTART_USER_SESSION_OPTION))
#define LXSESSION_IS_UPSTART_USER_SESSION_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_UPSTART_USER_SESSION_OPTION))
#define LXSESSION_UPSTART_USER_SESSION_OPTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_UPSTART_USER_SESSION_OPTION, LxsessionUpstartUserSessionOptionClass))

typedef struct _LxsessionUpstartUserSessionOption LxsessionUpstartUserSessionOption;
typedef struct _LxsessionUpstartUserSessionOptionClass LxsessionUpstartUserSessionOptionClass;
typedef struct _LxsessionUpstartUserSessionOptionPrivate LxsessionUpstartUserSessionOptionPrivate;

#define LXSESSION_TYPE_PROXY_OPTION (lxsession_proxy_option_get_type ())
#define LXSESSION_PROXY_OPTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_PROXY_OPTION, LxsessionProxyOption))
#define LXSESSION_PROXY_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_PROXY_OPTION, LxsessionProxyOptionClass))
#define LXSESSION_IS_PROXY_OPTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_PROXY_OPTION))
#define LXSESSION_IS_PROXY_OPTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_PROXY_OPTION))
#define LXSESSION_PROXY_OPTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_PROXY_OPTION, LxsessionProxyOptionClass))

typedef struct _LxsessionProxyOption LxsessionProxyOption;
typedef struct _LxsessionProxyOptionClass LxsessionProxyOptionClass;
typedef struct _LxsessionProxyOptionPrivate LxsessionProxyOptionPrivate;

#define LXSESSION_TYPE_LXSESSION_CONFIG_KEY_FILE (lxsession_lxsession_config_key_file_get_type ())
#define LXSESSION_LXSESSION_CONFIG_KEY_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_LXSESSION_CONFIG_KEY_FILE, LxsessionLxsessionConfigKeyFile))
#define LXSESSION_LXSESSION_CONFIG_KEY_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_LXSESSION_CONFIG_KEY_FILE, LxsessionLxsessionConfigKeyFileClass))
#define LXSESSION_IS_LXSESSION_CONFIG_KEY_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_LXSESSION_CONFIG_KEY_FILE))
#define LXSESSION_IS_LXSESSION_CONFIG_KEY_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_LXSESSION_CONFIG_KEY_FILE))
#define LXSESSION_LXSESSION_CONFIG_KEY_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_LXSESSION_CONFIG_KEY_FILE, LxsessionLxsessionConfigKeyFileClass))

typedef struct _LxsessionLxsessionConfigKeyFile LxsessionLxsessionConfigKeyFile;
typedef struct _LxsessionLxsessionConfigKeyFileClass LxsessionLxsessionConfigKeyFileClass;

struct _LxsessionOption {
	GObject parent_instance;
	LxsessionOptionPrivate * priv;
	gchar* command;
};

struct _LxsessionOptionClass {
	GObjectClass parent_class;
};

struct _LxsessionKeymapOption {
	LxsessionOption parent_instance;
	LxsessionKeymapOptionPrivate * priv;
};

struct _LxsessionKeymapOptionClass {
	LxsessionOptionClass parent_class;
};

struct _LxsessionXrandrOption {
	LxsessionOption parent_instance;
	LxsessionXrandrOptionPrivate * priv;
};

struct _LxsessionXrandrOptionClass {
	LxsessionOptionClass parent_class;
};

struct _LxsessionKeyringOption {
	LxsessionOption parent_instance;
	LxsessionKeyringOptionPrivate * priv;
};

struct _LxsessionKeyringOptionClass {
	LxsessionOptionClass parent_class;
};

struct _LxsessionKeyringOptionPrivate {
	gchar* command1;
	gchar* command2;
	gchar* command3;
	gchar* command4;
};

struct _LxsessionA11yOption {
	LxsessionOption parent_instance;
	LxsessionA11yOptionPrivate * priv;
};

struct _LxsessionA11yOptionClass {
	LxsessionOptionClass parent_class;
};

struct _LxsessionA11yOptionPrivate {
	gchar* command1;
};

struct _LxsessionClipboardOption {
	LxsessionOption parent_instance;
	LxsessionClipboardOptionPrivate * priv;
};

struct _LxsessionClipboardOptionClass {
	LxsessionOptionClass parent_class;
};

struct _LxsessionUpdatesOption {
	LxsessionOption parent_instance;
	LxsessionUpdatesOptionPrivate * priv;
};

struct _LxsessionUpdatesOptionClass {
	LxsessionOptionClass parent_class;
};

struct _LxsessionUpdatesOptionPrivate {
	gchar* command1;
};

struct _LxsessionUpstartUserSessionOption {
	LxsessionOption parent_instance;
	LxsessionUpstartUserSessionOptionPrivate * priv;
};

struct _LxsessionUpstartUserSessionOptionClass {
	LxsessionOptionClass parent_class;
};

struct _LxsessionUpstartUserSessionOptionPrivate {
	gchar* command1;
};

struct _LxsessionProxyOption {
	LxsessionOption parent_instance;
	LxsessionProxyOptionPrivate * priv;
};

struct _LxsessionProxyOptionClass {
	LxsessionOptionClass parent_class;
};

struct _LxsessionProxyOptionPrivate {
	gchar* http;
};


static gpointer lxsession_option_parent_class = NULL;
static gpointer lxsession_keymap_option_parent_class = NULL;
static gpointer lxsession_xrandr_option_parent_class = NULL;
static gpointer lxsession_keyring_option_parent_class = NULL;
static gpointer lxsession_a11y_option_parent_class = NULL;
static gpointer lxsession_clipboard_option_parent_class = NULL;
static gpointer lxsession_updates_option_parent_class = NULL;
static gpointer lxsession_upstart_user_session_option_parent_class = NULL;
static gpointer lxsession_proxy_option_parent_class = NULL;
extern LxsessionLxsessionConfigKeyFile* lxsession_global_settings;

GType lxsession_option_get_type (void) G_GNUC_CONST;
enum  {
	LXSESSION_OPTION_DUMMY_PROPERTY
};
GType lxsession_lxsession_config_get_type (void) G_GNUC_CONST;
LxsessionOption* lxsession_option_new (LxsessionLxsessionConfig* config);
LxsessionOption* lxsession_option_construct (GType object_type, LxsessionLxsessionConfig* config);
void lxsession_option_activate (LxsessionOption* self);
static void lxsession_option_finalize (GObject* obj);
GType lxsession_keymap_option_get_type (void) G_GNUC_CONST;
enum  {
	LXSESSION_KEYMAP_OPTION_DUMMY_PROPERTY
};
LxsessionKeymapOption* lxsession_keymap_option_new (LxsessionLxsessionConfig* config);
LxsessionKeymapOption* lxsession_keymap_option_construct (GType object_type, LxsessionLxsessionConfig* config);
const gchar* lxsession_lxsession_config_get_keymap_mode (LxsessionLxsessionConfig* self);
gchar* lxsession_keymap_option_create_user_mode_command (LxsessionKeymapOption* self, LxsessionLxsessionConfig* config);
const gchar* lxsession_lxsession_config_get_keymap_model (LxsessionLxsessionConfig* self);
const gchar* lxsession_lxsession_config_get_keymap_layout (LxsessionLxsessionConfig* self);
const gchar* lxsession_lxsession_config_get_keymap_variant (LxsessionLxsessionConfig* self);
const gchar* lxsession_lxsession_config_get_keymap_options (LxsessionLxsessionConfig* self);
GType lxsession_xrandr_option_get_type (void) G_GNUC_CONST;
enum  {
	LXSESSION_XRANDR_OPTION_DUMMY_PROPERTY
};
LxsessionXrandrOption* lxsession_xrandr_option_new (LxsessionLxsessionConfig* config);
LxsessionXrandrOption* lxsession_xrandr_option_construct (GType object_type, LxsessionLxsessionConfig* config);
const gchar* lxsession_lxsession_config_get_xrandr_mode (LxsessionLxsessionConfig* self);
gchar* lxsession_xrandr_option_create_command_mode_command (LxsessionXrandrOption* self, LxsessionLxsessionConfig* config);
const gchar* lxsession_lxsession_config_get_xrandr_command (LxsessionLxsessionConfig* self);
GType lxsession_keyring_option_get_type (void) G_GNUC_CONST;
#define LXSESSION_KEYRING_OPTION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), LXSESSION_TYPE_KEYRING_OPTION, LxsessionKeyringOptionPrivate))
enum  {
	LXSESSION_KEYRING_OPTION_DUMMY_PROPERTY
};
LxsessionKeyringOption* lxsession_keyring_option_new (LxsessionLxsessionConfig* config);
LxsessionKeyringOption* lxsession_keyring_option_construct (GType object_type, LxsessionLxsessionConfig* config);
const gchar* lxsession_lxsession_config_get_security_keyring (LxsessionLxsessionConfig* self);
void lxsession_keyring_option_activate (LxsessionKeyringOption* self);
static void lxsession_keyring_option_finalize (GObject* obj);
GType lxsession_a11y_option_get_type (void) G_GNUC_CONST;
#define LXSESSION_A11Y_OPTION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), LXSESSION_TYPE_A11Y_OPTION, LxsessionA11yOptionPrivate))
enum  {
	LXSESSION_A11Y_OPTION_DUMMY_PROPERTY
};
LxsessionA11yOption* lxsession_a11y_option_new (LxsessionLxsessionConfig* config);
LxsessionA11yOption* lxsession_a11y_option_construct (GType object_type, LxsessionLxsessionConfig* config);
const gchar* lxsession_lxsession_config_get_a11y_type (LxsessionLxsessionConfig* self);
void lxsession_a11y_option_activate (LxsessionA11yOption* self);
static void lxsession_a11y_option_finalize (GObject* obj);
GType lxsession_clipboard_option_get_type (void) G_GNUC_CONST;
enum  {
	LXSESSION_CLIPBOARD_OPTION_DUMMY_PROPERTY
};
LxsessionClipboardOption* lxsession_clipboard_option_new (LxsessionLxsessionConfig* config);
LxsessionClipboardOption* lxsession_clipboard_option_construct (GType object_type, LxsessionLxsessionConfig* config);
const gchar* lxsession_lxsession_config_get_clipboard_command (LxsessionLxsessionConfig* self);
void lxsession_clipboard_option_desactivate (LxsessionClipboardOption* self);
GType lxsession_updates_option_get_type (void) G_GNUC_CONST;
#define LXSESSION_UPDATES_OPTION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), LXSESSION_TYPE_UPDATES_OPTION, LxsessionUpdatesOptionPrivate))
enum  {
	LXSESSION_UPDATES_OPTION_DUMMY_PROPERTY
};
LxsessionUpdatesOption* lxsession_updates_option_new (LxsessionLxsessionConfig* config);
LxsessionUpdatesOption* lxsession_updates_option_construct (GType object_type, LxsessionLxsessionConfig* config);
const gchar* lxsession_lxsession_config_get_updates_type (LxsessionLxsessionConfig* self);
void lxsession_updates_option_activate (LxsessionUpdatesOption* self);
void lxsession_updates_option_setup_apt_config (LxsessionUpdatesOption* self);
void lxsession_updates_option_on_apt_update_file_change (LxsessionUpdatesOption* self);
static void _lxsession_updates_option_on_apt_update_file_change_g_file_monitor_changed (GFileMonitor* _sender, GFile* file, GFile* other_file, GFileMonitorEvent event_type, gpointer self);
static void lxsession_updates_option_finalize (GObject* obj);
GType lxsession_upstart_user_session_option_get_type (void) G_GNUC_CONST;
#define LXSESSION_UPSTART_USER_SESSION_OPTION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), LXSESSION_TYPE_UPSTART_USER_SESSION_OPTION, LxsessionUpstartUserSessionOptionPrivate))
enum  {
	LXSESSION_UPSTART_USER_SESSION_OPTION_DUMMY_PROPERTY
};
LxsessionUpstartUserSessionOption* lxsession_upstart_user_session_option_new (LxsessionLxsessionConfig* config);
LxsessionUpstartUserSessionOption* lxsession_upstart_user_session_option_construct (GType object_type, LxsessionLxsessionConfig* config);
const gchar* lxsession_lxsession_config_get_upstart_user_session (LxsessionLxsessionConfig* self);
void lxsession_upstart_user_session_option_activate (LxsessionUpstartUserSessionOption* self);
static void lxsession_upstart_user_session_option_finalize (GObject* obj);
GType lxsession_proxy_option_get_type (void) G_GNUC_CONST;
#define LXSESSION_PROXY_OPTION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), LXSESSION_TYPE_PROXY_OPTION, LxsessionProxyOptionPrivate))
enum  {
	LXSESSION_PROXY_OPTION_DUMMY_PROPERTY
};
LxsessionProxyOption* lxsession_proxy_option_new (LxsessionLxsessionConfig* config);
LxsessionProxyOption* lxsession_proxy_option_construct (GType object_type, LxsessionLxsessionConfig* config);
void lxsession_proxy_option_activate (LxsessionProxyOption* self);
GType lxsession_lxsession_config_key_file_get_type (void) G_GNUC_CONST;
const gchar* lxsession_lxsession_config_get_proxy_http (LxsessionLxsessionConfig* self);
static void lxsession_proxy_option_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


LxsessionOption* lxsession_option_construct (GType object_type, LxsessionLxsessionConfig* config) {
	LxsessionOption * self = NULL;
	g_return_val_if_fail (config != NULL, NULL);
	self = (LxsessionOption*) g_object_new (object_type, NULL);
	return self;
}


LxsessionOption* lxsession_option_new (LxsessionLxsessionConfig* config) {
	return lxsession_option_construct (LXSESSION_TYPE_OPTION, config);
}


void lxsession_option_activate (LxsessionOption* self) {
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	GQuark _tmp3_ = 0U;
	static GQuark _tmp2_label0 = 0;
	static GQuark _tmp2_label1 = 0;
	static GQuark _tmp2_label2 = 0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->command;
	_tmp1_ = _tmp0_;
	_tmp3_ = (NULL == _tmp1_) ? 0 : g_quark_from_string (_tmp1_);
	if (_tmp3_ == ((0 != _tmp2_label0) ? _tmp2_label0 : (_tmp2_label0 = g_quark_from_static_string (NULL)))) {
		switch (0) {
			default:
			{
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label1) ? _tmp2_label1 : (_tmp2_label1 = g_quark_from_static_string ("")))) {
		switch (0) {
			default:
			{
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label2) ? _tmp2_label2 : (_tmp2_label2 = g_quark_from_static_string (" ")))) {
		switch (0) {
			default:
			{
				break;
			}
		}
	} else {
		switch (0) {
			default:
			{
				{
					const gchar* _tmp4_;
					const gchar* _tmp5_;
					_tmp4_ = self->command;
					g_message ("options.vala:46: Options - Launch command %s", _tmp4_);
					_tmp5_ = self->command;
					g_spawn_command_line_async (_tmp5_, &_inner_error_);
					if (_inner_error_ != NULL) {
						if (_inner_error_->domain == G_SPAWN_ERROR) {
							goto __catch18_g_spawn_error;
						}
						g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return;
					}
				}
				goto __finally18;
				__catch18_g_spawn_error:
				{
					GError* err = NULL;
					GError* _tmp6_;
					const gchar* _tmp7_;
					err = _inner_error_;
					_inner_error_ = NULL;
					_tmp6_ = err;
					_tmp7_ = _tmp6_->message;
					g_warning ("options.vala:51: %s", _tmp7_);
					_g_error_free0 (err);
				}
				__finally18:
				if (_inner_error_ != NULL) {
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return;
				}
				break;
			}
		}
	}
}


static void lxsession_option_class_init (LxsessionOptionClass * klass) {
	lxsession_option_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = lxsession_option_finalize;
}


static void lxsession_option_instance_init (LxsessionOption * self) {
}


static void lxsession_option_finalize (GObject* obj) {
	LxsessionOption * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, LXSESSION_TYPE_OPTION, LxsessionOption);
	_g_free0 (self->command);
	G_OBJECT_CLASS (lxsession_option_parent_class)->finalize (obj);
}


GType lxsession_option_get_type (void) {
	static volatile gsize lxsession_option_type_id__volatile = 0;
	if (g_once_init_enter (&lxsession_option_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LxsessionOptionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) lxsession_option_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LxsessionOption), 0, (GInstanceInitFunc) lxsession_option_instance_init, NULL };
		GType lxsession_option_type_id;
		lxsession_option_type_id = g_type_register_static (G_TYPE_OBJECT, "LxsessionOption", &g_define_type_info, 0);
		g_once_init_leave (&lxsession_option_type_id__volatile, lxsession_option_type_id);
	}
	return lxsession_option_type_id__volatile;
}


LxsessionKeymapOption* lxsession_keymap_option_construct (GType object_type, LxsessionLxsessionConfig* config) {
	LxsessionKeymapOption * self = NULL;
	LxsessionLxsessionConfig* _tmp0_;
	LxsessionLxsessionConfig* _tmp1_;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	g_return_val_if_fail (config != NULL, NULL);
	_tmp0_ = config;
	self = (LxsessionKeymapOption*) lxsession_option_construct (object_type, _tmp0_);
	_tmp1_ = config;
	_tmp2_ = lxsession_lxsession_config_get_keymap_mode (_tmp1_);
	_tmp3_ = _tmp2_;
	if (g_strcmp0 (_tmp3_, "user") == 0) {
		LxsessionLxsessionConfig* _tmp4_;
		gchar* _tmp5_ = NULL;
		_tmp4_ = config;
		_tmp5_ = lxsession_keymap_option_create_user_mode_command (self, _tmp4_);
		_g_free0 (((LxsessionOption*) self)->command);
		((LxsessionOption*) self)->command = _tmp5_;
	}
	return self;
}


LxsessionKeymapOption* lxsession_keymap_option_new (LxsessionLxsessionConfig* config) {
	return lxsession_keymap_option_construct (LXSESSION_TYPE_KEYMAP_OPTION, config);
}


gchar* lxsession_keymap_option_create_user_mode_command (LxsessionKeymapOption* self, LxsessionLxsessionConfig* config) {
	gchar* result = NULL;
	GString* _tmp0_;
	GString* builder;
	GString* _tmp1_;
	LxsessionLxsessionConfig* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	LxsessionLxsessionConfig* _tmp11_;
	const gchar* _tmp12_;
	const gchar* _tmp13_;
	LxsessionLxsessionConfig* _tmp20_;
	const gchar* _tmp21_;
	const gchar* _tmp22_;
	LxsessionLxsessionConfig* _tmp32_;
	const gchar* _tmp33_;
	const gchar* _tmp34_;
	GString* _tmp44_;
	const gchar* _tmp45_;
	gchar* _tmp46_;
	const gchar* _tmp47_;
	const gchar* _tmp48_;
	gchar* _tmp49_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (config != NULL, NULL);
	_tmp0_ = g_string_new ("");
	builder = _tmp0_;
	_tmp1_ = builder;
	g_string_append (_tmp1_, "setxkbmap ");
	_tmp2_ = config;
	_tmp3_ = lxsession_lxsession_config_get_keymap_model (_tmp2_);
	_tmp4_ = _tmp3_;
	if (_tmp4_ != NULL) {
		GString* _tmp5_;
		GString* _tmp6_;
		LxsessionLxsessionConfig* _tmp7_;
		const gchar* _tmp8_;
		const gchar* _tmp9_;
		GString* _tmp10_;
		_tmp5_ = builder;
		g_string_append (_tmp5_, "-model ");
		_tmp6_ = builder;
		_tmp7_ = config;
		_tmp8_ = lxsession_lxsession_config_get_keymap_model (_tmp7_);
		_tmp9_ = _tmp8_;
		g_string_append (_tmp6_, _tmp9_);
		_tmp10_ = builder;
		g_string_append (_tmp10_, " ");
	}
	_tmp11_ = config;
	_tmp12_ = lxsession_lxsession_config_get_keymap_layout (_tmp11_);
	_tmp13_ = _tmp12_;
	if (_tmp13_ != NULL) {
		GString* _tmp14_;
		GString* _tmp15_;
		LxsessionLxsessionConfig* _tmp16_;
		const gchar* _tmp17_;
		const gchar* _tmp18_;
		GString* _tmp19_;
		_tmp14_ = builder;
		g_string_append (_tmp14_, "-layout ");
		_tmp15_ = builder;
		_tmp16_ = config;
		_tmp17_ = lxsession_lxsession_config_get_keymap_layout (_tmp16_);
		_tmp18_ = _tmp17_;
		g_string_append (_tmp15_, _tmp18_);
		_tmp19_ = builder;
		g_string_append (_tmp19_, " ");
	}
	_tmp20_ = config;
	_tmp21_ = lxsession_lxsession_config_get_keymap_variant (_tmp20_);
	_tmp22_ = _tmp21_;
	if (_tmp22_ != NULL) {
		GString* _tmp23_;
		LxsessionLxsessionConfig* _tmp24_;
		const gchar* _tmp25_;
		const gchar* _tmp26_;
		GString* _tmp27_;
		LxsessionLxsessionConfig* _tmp28_;
		const gchar* _tmp29_;
		const gchar* _tmp30_;
		GString* _tmp31_;
		_tmp23_ = builder;
		g_string_append (_tmp23_, "-variant ");
		_tmp24_ = config;
		_tmp25_ = lxsession_lxsession_config_get_keymap_variant (_tmp24_);
		_tmp26_ = _tmp25_;
		g_message ("options.vala:87: Show keymap variant : %s", _tmp26_);
		_tmp27_ = builder;
		_tmp28_ = config;
		_tmp29_ = lxsession_lxsession_config_get_keymap_variant (_tmp28_);
		_tmp30_ = _tmp29_;
		g_string_append (_tmp27_, _tmp30_);
		_tmp31_ = builder;
		g_string_append (_tmp31_, " ");
	}
	_tmp32_ = config;
	_tmp33_ = lxsession_lxsession_config_get_keymap_options (_tmp32_);
	_tmp34_ = _tmp33_;
	if (_tmp34_ != NULL) {
		GString* _tmp35_;
		LxsessionLxsessionConfig* _tmp36_;
		const gchar* _tmp37_;
		const gchar* _tmp38_;
		GString* _tmp39_;
		LxsessionLxsessionConfig* _tmp40_;
		const gchar* _tmp41_;
		const gchar* _tmp42_;
		GString* _tmp43_;
		_tmp35_ = builder;
		g_string_append (_tmp35_, "-options ");
		_tmp36_ = config;
		_tmp37_ = lxsession_lxsession_config_get_keymap_options (_tmp36_);
		_tmp38_ = _tmp37_;
		g_message ("options.vala:94: Show keymap options : %s", _tmp38_);
		_tmp39_ = builder;
		_tmp40_ = config;
		_tmp41_ = lxsession_lxsession_config_get_keymap_options (_tmp40_);
		_tmp42_ = _tmp41_;
		g_string_append (_tmp39_, _tmp42_);
		_tmp43_ = builder;
		g_string_append (_tmp43_, " ");
	}
	_tmp44_ = builder;
	_tmp45_ = _tmp44_->str;
	_tmp46_ = g_strdup (_tmp45_);
	_g_free0 (((LxsessionOption*) self)->command);
	((LxsessionOption*) self)->command = _tmp46_;
	_tmp47_ = ((LxsessionOption*) self)->command;
	g_message ("options.vala:100: Keymap options - return user command %s", _tmp47_);
	_tmp48_ = ((LxsessionOption*) self)->command;
	_tmp49_ = g_strdup (_tmp48_);
	result = _tmp49_;
	_g_string_free0 (builder);
	return result;
}


static void lxsession_keymap_option_class_init (LxsessionKeymapOptionClass * klass) {
	lxsession_keymap_option_parent_class = g_type_class_peek_parent (klass);
}


static void lxsession_keymap_option_instance_init (LxsessionKeymapOption * self) {
}


GType lxsession_keymap_option_get_type (void) {
	static volatile gsize lxsession_keymap_option_type_id__volatile = 0;
	if (g_once_init_enter (&lxsession_keymap_option_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LxsessionKeymapOptionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) lxsession_keymap_option_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LxsessionKeymapOption), 0, (GInstanceInitFunc) lxsession_keymap_option_instance_init, NULL };
		GType lxsession_keymap_option_type_id;
		lxsession_keymap_option_type_id = g_type_register_static (LXSESSION_TYPE_OPTION, "LxsessionKeymapOption", &g_define_type_info, 0);
		g_once_init_leave (&lxsession_keymap_option_type_id__volatile, lxsession_keymap_option_type_id);
	}
	return lxsession_keymap_option_type_id__volatile;
}


LxsessionXrandrOption* lxsession_xrandr_option_construct (GType object_type, LxsessionLxsessionConfig* config) {
	LxsessionXrandrOption * self = NULL;
	LxsessionLxsessionConfig* _tmp0_;
	LxsessionLxsessionConfig* _tmp1_;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	g_return_val_if_fail (config != NULL, NULL);
	_tmp0_ = config;
	self = (LxsessionXrandrOption*) lxsession_option_construct (object_type, _tmp0_);
	_tmp1_ = config;
	_tmp2_ = lxsession_lxsession_config_get_xrandr_mode (_tmp1_);
	_tmp3_ = _tmp2_;
	if (g_strcmp0 (_tmp3_, "command") == 0) {
		LxsessionLxsessionConfig* _tmp4_;
		gchar* _tmp5_ = NULL;
		_tmp4_ = config;
		_tmp5_ = lxsession_xrandr_option_create_command_mode_command (self, _tmp4_);
		_g_free0 (((LxsessionOption*) self)->command);
		((LxsessionOption*) self)->command = _tmp5_;
	}
	return self;
}


LxsessionXrandrOption* lxsession_xrandr_option_new (LxsessionLxsessionConfig* config) {
	return lxsession_xrandr_option_construct (LXSESSION_TYPE_XRANDR_OPTION, config);
}


gchar* lxsession_xrandr_option_create_command_mode_command (LxsessionXrandrOption* self, LxsessionLxsessionConfig* config) {
	gchar* result = NULL;
	LxsessionLxsessionConfig* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	const gchar* _tmp4_;
	gchar* _tmp5_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (config != NULL, NULL);
	_tmp0_ = config;
	_tmp1_ = lxsession_lxsession_config_get_xrandr_command (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_strdup (_tmp2_);
	_g_free0 (((LxsessionOption*) self)->command);
	((LxsessionOption*) self)->command = _tmp3_;
	_tmp4_ = ((LxsessionOption*) self)->command;
	_tmp5_ = g_strdup (_tmp4_);
	result = _tmp5_;
	return result;
}


static void lxsession_xrandr_option_class_init (LxsessionXrandrOptionClass * klass) {
	lxsession_xrandr_option_parent_class = g_type_class_peek_parent (klass);
}


static void lxsession_xrandr_option_instance_init (LxsessionXrandrOption * self) {
}


GType lxsession_xrandr_option_get_type (void) {
	static volatile gsize lxsession_xrandr_option_type_id__volatile = 0;
	if (g_once_init_enter (&lxsession_xrandr_option_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LxsessionXrandrOptionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) lxsession_xrandr_option_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LxsessionXrandrOption), 0, (GInstanceInitFunc) lxsession_xrandr_option_instance_init, NULL };
		GType lxsession_xrandr_option_type_id;
		lxsession_xrandr_option_type_id = g_type_register_static (LXSESSION_TYPE_OPTION, "LxsessionXrandrOption", &g_define_type_info, 0);
		g_once_init_leave (&lxsession_xrandr_option_type_id__volatile, lxsession_xrandr_option_type_id);
	}
	return lxsession_xrandr_option_type_id__volatile;
}


LxsessionKeyringOption* lxsession_keyring_option_construct (GType object_type, LxsessionLxsessionConfig* config) {
	LxsessionKeyringOption * self = NULL;
	LxsessionLxsessionConfig* _tmp0_;
	LxsessionLxsessionConfig* _tmp1_;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	GQuark _tmp6_ = 0U;
	static GQuark _tmp5_label0 = 0;
	static GQuark _tmp5_label1 = 0;
	g_return_val_if_fail (config != NULL, NULL);
	_tmp0_ = config;
	self = (LxsessionKeyringOption*) lxsession_option_construct (object_type, _tmp0_);
	_tmp1_ = config;
	_tmp2_ = lxsession_lxsession_config_get_security_keyring (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = _tmp3_;
	_tmp6_ = (NULL == _tmp4_) ? 0 : g_quark_from_string (_tmp4_);
	if (_tmp6_ == ((0 != _tmp5_label0) ? _tmp5_label0 : (_tmp5_label0 = g_quark_from_static_string ("gnome-all")))) {
		switch (0) {
			default:
			{
				gchar* _tmp7_;
				gchar* _tmp8_;
				gchar* _tmp9_;
				gchar* _tmp10_;
				_tmp7_ = g_strdup ("gnome-keyring-daemon --start --components=gpg");
				_g_free0 (self->priv->command1);
				self->priv->command1 = _tmp7_;
				_tmp8_ = g_strdup ("gnome-keyring-daemon --start --components=pkcs11");
				_g_free0 (self->priv->command2);
				self->priv->command2 = _tmp8_;
				_tmp9_ = g_strdup ("gnome-keyring-daemon --start --components=secrets");
				_g_free0 (self->priv->command3);
				self->priv->command3 = _tmp9_;
				_tmp10_ = g_strdup ("gnome-keyring-daemon --start --components=ssh");
				_g_free0 (self->priv->command4);
				self->priv->command4 = _tmp10_;
				break;
			}
		}
	} else if (_tmp6_ == ((0 != _tmp5_label1) ? _tmp5_label1 : (_tmp5_label1 = g_quark_from_static_string ("ssh-agent")))) {
		switch (0) {
			default:
			{
				gchar* _tmp11_;
				_tmp11_ = g_strdup ("/usr/bin/ssh-agent -s");
				_g_free0 (self->priv->command1);
				self->priv->command1 = _tmp11_;
				break;
			}
		}
	}
	return self;
}


LxsessionKeyringOption* lxsession_keyring_option_new (LxsessionLxsessionConfig* config) {
	return lxsession_keyring_option_construct (LXSESSION_TYPE_KEYRING_OPTION, config);
}


void lxsession_keyring_option_activate (LxsessionKeyringOption* self) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	{
		const gchar* _tmp0_;
		const gchar* _tmp2_;
		const gchar* _tmp4_;
		const gchar* _tmp6_;
		_tmp0_ = self->priv->command1;
		if (_tmp0_ != NULL) {
			const gchar* _tmp1_;
			_tmp1_ = self->priv->command1;
			g_spawn_command_line_async (_tmp1_, &_inner_error_);
			if (_inner_error_ != NULL) {
				if (_inner_error_->domain == G_SPAWN_ERROR) {
					goto __catch19_g_spawn_error;
				}
				g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return;
			}
		}
		_tmp2_ = self->priv->command2;
		if (_tmp2_ != NULL) {
			const gchar* _tmp3_;
			_tmp3_ = self->priv->command2;
			g_spawn_command_line_async (_tmp3_, &_inner_error_);
			if (_inner_error_ != NULL) {
				if (_inner_error_->domain == G_SPAWN_ERROR) {
					goto __catch19_g_spawn_error;
				}
				g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return;
			}
		}
		_tmp4_ = self->priv->command3;
		if (_tmp4_ != NULL) {
			const gchar* _tmp5_;
			_tmp5_ = self->priv->command3;
			g_spawn_command_line_async (_tmp5_, &_inner_error_);
			if (_inner_error_ != NULL) {
				if (_inner_error_->domain == G_SPAWN_ERROR) {
					goto __catch19_g_spawn_error;
				}
				g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return;
			}
		}
		_tmp6_ = self->priv->command4;
		if (_tmp6_ != NULL) {
			const gchar* _tmp7_;
			_tmp7_ = self->priv->command4;
			g_spawn_command_line_async (_tmp7_, &_inner_error_);
			if (_inner_error_ != NULL) {
				if (_inner_error_->domain == G_SPAWN_ERROR) {
					goto __catch19_g_spawn_error;
				}
				g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return;
			}
		}
	}
	goto __finally19;
	__catch19_g_spawn_error:
	{
		GError* err = NULL;
		GError* _tmp8_;
		const gchar* _tmp9_;
		err = _inner_error_;
		_inner_error_ = NULL;
		_tmp8_ = err;
		_tmp9_ = _tmp8_->message;
		g_warning ("options.vala:170: %s", _tmp9_);
		_g_error_free0 (err);
	}
	__finally19:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void lxsession_keyring_option_class_init (LxsessionKeyringOptionClass * klass) {
	lxsession_keyring_option_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (LxsessionKeyringOptionPrivate));
	G_OBJECT_CLASS (klass)->finalize = lxsession_keyring_option_finalize;
}


static void lxsession_keyring_option_instance_init (LxsessionKeyringOption * self) {
	self->priv = LXSESSION_KEYRING_OPTION_GET_PRIVATE (self);
}


static void lxsession_keyring_option_finalize (GObject* obj) {
	LxsessionKeyringOption * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, LXSESSION_TYPE_KEYRING_OPTION, LxsessionKeyringOption);
	_g_free0 (self->priv->command1);
	_g_free0 (self->priv->command2);
	_g_free0 (self->priv->command3);
	_g_free0 (self->priv->command4);
	G_OBJECT_CLASS (lxsession_keyring_option_parent_class)->finalize (obj);
}


GType lxsession_keyring_option_get_type (void) {
	static volatile gsize lxsession_keyring_option_type_id__volatile = 0;
	if (g_once_init_enter (&lxsession_keyring_option_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LxsessionKeyringOptionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) lxsession_keyring_option_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LxsessionKeyringOption), 0, (GInstanceInitFunc) lxsession_keyring_option_instance_init, NULL };
		GType lxsession_keyring_option_type_id;
		lxsession_keyring_option_type_id = g_type_register_static (LXSESSION_TYPE_OPTION, "LxsessionKeyringOption", &g_define_type_info, 0);
		g_once_init_leave (&lxsession_keyring_option_type_id__volatile, lxsession_keyring_option_type_id);
	}
	return lxsession_keyring_option_type_id__volatile;
}


LxsessionA11yOption* lxsession_a11y_option_construct (GType object_type, LxsessionLxsessionConfig* config) {
	LxsessionA11yOption * self = NULL;
	LxsessionLxsessionConfig* _tmp0_;
	LxsessionLxsessionConfig* _tmp1_;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	GQuark _tmp6_ = 0U;
	static GQuark _tmp5_label0 = 0;
	g_return_val_if_fail (config != NULL, NULL);
	_tmp0_ = config;
	self = (LxsessionA11yOption*) lxsession_option_construct (object_type, _tmp0_);
	_tmp1_ = config;
	_tmp2_ = lxsession_lxsession_config_get_a11y_type (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = _tmp3_;
	_tmp6_ = (NULL == _tmp4_) ? 0 : g_quark_from_string (_tmp4_);
	if (_tmp6_ == ((0 != _tmp5_label0) ? _tmp5_label0 : (_tmp5_label0 = g_quark_from_static_string ("gnome")))) {
		switch (0) {
			default:
			{
				gchar* _tmp7_;
				_tmp7_ = g_strdup ("/usr/lib/at-spi2-core/at-spi-bus-launcher --launch-immediately");
				_g_free0 (self->priv->command1);
				self->priv->command1 = _tmp7_;
				break;
			}
		}
	}
	return self;
}


LxsessionA11yOption* lxsession_a11y_option_new (LxsessionLxsessionConfig* config) {
	return lxsession_a11y_option_construct (LXSESSION_TYPE_A11Y_OPTION, config);
}


void lxsession_a11y_option_activate (LxsessionA11yOption* self) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	{
		const gchar* _tmp0_;
		_tmp0_ = self->priv->command1;
		g_spawn_command_line_async (_tmp0_, &_inner_error_);
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_SPAWN_ERROR) {
				goto __catch20_g_spawn_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	goto __finally20;
	__catch20_g_spawn_error:
	{
		GError* err = NULL;
		GError* _tmp1_;
		const gchar* _tmp2_;
		err = _inner_error_;
		_inner_error_ = NULL;
		_tmp1_ = err;
		_tmp2_ = _tmp1_->message;
		g_warning ("options.vala:197: %s", _tmp2_);
		_g_error_free0 (err);
	}
	__finally20:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void lxsession_a11y_option_class_init (LxsessionA11yOptionClass * klass) {
	lxsession_a11y_option_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (LxsessionA11yOptionPrivate));
	G_OBJECT_CLASS (klass)->finalize = lxsession_a11y_option_finalize;
}


static void lxsession_a11y_option_instance_init (LxsessionA11yOption * self) {
	self->priv = LXSESSION_A11Y_OPTION_GET_PRIVATE (self);
}


static void lxsession_a11y_option_finalize (GObject* obj) {
	LxsessionA11yOption * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, LXSESSION_TYPE_A11Y_OPTION, LxsessionA11yOption);
	_g_free0 (self->priv->command1);
	G_OBJECT_CLASS (lxsession_a11y_option_parent_class)->finalize (obj);
}


GType lxsession_a11y_option_get_type (void) {
	static volatile gsize lxsession_a11y_option_type_id__volatile = 0;
	if (g_once_init_enter (&lxsession_a11y_option_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LxsessionA11yOptionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) lxsession_a11y_option_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LxsessionA11yOption), 0, (GInstanceInitFunc) lxsession_a11y_option_instance_init, NULL };
		GType lxsession_a11y_option_type_id;
		lxsession_a11y_option_type_id = g_type_register_static (LXSESSION_TYPE_OPTION, "LxsessionA11yOption", &g_define_type_info, 0);
		g_once_init_leave (&lxsession_a11y_option_type_id__volatile, lxsession_a11y_option_type_id);
	}
	return lxsession_a11y_option_type_id__volatile;
}


LxsessionClipboardOption* lxsession_clipboard_option_construct (GType object_type, LxsessionLxsessionConfig* config) {
	LxsessionClipboardOption * self = NULL;
	LxsessionLxsessionConfig* _tmp0_;
	LxsessionLxsessionConfig* _tmp1_;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	GQuark _tmp6_ = 0U;
	static GQuark _tmp5_label0 = 0;
	g_return_val_if_fail (config != NULL, NULL);
	_tmp0_ = config;
	self = (LxsessionClipboardOption*) lxsession_option_construct (object_type, _tmp0_);
	_tmp1_ = config;
	_tmp2_ = lxsession_lxsession_config_get_clipboard_command (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = _tmp3_;
	_tmp6_ = (NULL == _tmp4_) ? 0 : g_quark_from_string (_tmp4_);
	if (_tmp6_ == ((0 != _tmp5_label0) ? _tmp5_label0 : (_tmp5_label0 = g_quark_from_static_string ("lxclipboard")))) {
		switch (0) {
			default:
			{
				gchar* _tmp7_;
				g_message ("options.vala:213: Create Option Clipboard");
				_tmp7_ = g_strdup ("lxclipboard");
				_g_free0 (((LxsessionOption*) self)->command);
				((LxsessionOption*) self)->command = _tmp7_;
				break;
			}
		}
	}
	return self;
}


LxsessionClipboardOption* lxsession_clipboard_option_new (LxsessionLxsessionConfig* config) {
	return lxsession_clipboard_option_construct (LXSESSION_TYPE_CLIPBOARD_OPTION, config);
}


void lxsession_clipboard_option_desactivate (LxsessionClipboardOption* self) {
	g_return_if_fail (self != NULL);
}


static void lxsession_clipboard_option_class_init (LxsessionClipboardOptionClass * klass) {
	lxsession_clipboard_option_parent_class = g_type_class_peek_parent (klass);
}


static void lxsession_clipboard_option_instance_init (LxsessionClipboardOption * self) {
}


GType lxsession_clipboard_option_get_type (void) {
	static volatile gsize lxsession_clipboard_option_type_id__volatile = 0;
	if (g_once_init_enter (&lxsession_clipboard_option_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LxsessionClipboardOptionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) lxsession_clipboard_option_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LxsessionClipboardOption), 0, (GInstanceInitFunc) lxsession_clipboard_option_instance_init, NULL };
		GType lxsession_clipboard_option_type_id;
		lxsession_clipboard_option_type_id = g_type_register_static (LXSESSION_TYPE_OPTION, "LxsessionClipboardOption", &g_define_type_info, 0);
		g_once_init_leave (&lxsession_clipboard_option_type_id__volatile, lxsession_clipboard_option_type_id);
	}
	return lxsession_clipboard_option_type_id__volatile;
}


LxsessionUpdatesOption* lxsession_updates_option_construct (GType object_type, LxsessionLxsessionConfig* config) {
	LxsessionUpdatesOption * self = NULL;
	LxsessionLxsessionConfig* _tmp0_;
	LxsessionLxsessionConfig* _tmp1_;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	GQuark _tmp6_ = 0U;
	static GQuark _tmp5_label0 = 0;
	static GQuark _tmp5_label1 = 0;
	g_return_val_if_fail (config != NULL, NULL);
	_tmp0_ = config;
	self = (LxsessionUpdatesOption*) lxsession_option_construct (object_type, _tmp0_);
	_tmp1_ = config;
	_tmp2_ = lxsession_lxsession_config_get_updates_type (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = _tmp3_;
	_tmp6_ = (NULL == _tmp4_) ? 0 : g_quark_from_string (_tmp4_);
	if (_tmp6_ == ((0 != _tmp5_label0) ? _tmp5_label0 : (_tmp5_label0 = g_quark_from_static_string ("update-notifier")))) {
		switch (0) {
			default:
			{
				gchar* _tmp7_;
				_tmp7_ = g_strdup ("update-notifier");
				_g_free0 (self->priv->command1);
				self->priv->command1 = _tmp7_;
				break;
			}
		}
	} else if (_tmp6_ == ((0 != _tmp5_label1) ? _tmp5_label1 : (_tmp5_label1 = g_quark_from_static_string ("build-in")))) {
		switch (0) {
			default:
			{
				gchar* _tmp8_;
				_tmp8_ = g_strdup ("build-in");
				_g_free0 (self->priv->command1);
				self->priv->command1 = _tmp8_;
				break;
			}
		}
	}
	return self;
}


LxsessionUpdatesOption* lxsession_updates_option_new (LxsessionLxsessionConfig* config) {
	return lxsession_updates_option_construct (LXSESSION_TYPE_UPDATES_OPTION, config);
}


void lxsession_updates_option_activate (LxsessionUpdatesOption* self) {
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	GQuark _tmp3_ = 0U;
	static GQuark _tmp2_label0 = 0;
	static GQuark _tmp2_label1 = 0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->command1;
	_tmp1_ = _tmp0_;
	_tmp3_ = (NULL == _tmp1_) ? 0 : g_quark_from_string (_tmp1_);
	if (_tmp3_ == ((0 != _tmp2_label0) ? _tmp2_label0 : (_tmp2_label0 = g_quark_from_static_string ("build-in")))) {
		switch (0) {
			default:
			{
				lxsession_updates_option_setup_apt_config (self);
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label1) ? _tmp2_label1 : (_tmp2_label1 = g_quark_from_static_string ("update-notifier")))) {
		switch (0) {
			default:
			{
				{
					const gchar* _tmp4_;
					_tmp4_ = self->priv->command1;
					g_spawn_command_line_async (_tmp4_, &_inner_error_);
					if (_inner_error_ != NULL) {
						if (_inner_error_->domain == G_SPAWN_ERROR) {
							goto __catch21_g_spawn_error;
						}
						g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return;
					}
				}
				goto __finally21;
				__catch21_g_spawn_error:
				{
					GError* err = NULL;
					GError* _tmp5_;
					const gchar* _tmp6_;
					err = _inner_error_;
					_inner_error_ = NULL;
					_tmp5_ = err;
					_tmp6_ = _tmp5_->message;
					g_warning ("options.vala:258: %s", _tmp6_);
					_g_error_free0 (err);
				}
				__finally21:
				if (_inner_error_ != NULL) {
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return;
				}
				break;
			}
		}
	}
}


void lxsession_updates_option_on_apt_update_file_change (LxsessionUpdatesOption* self) {
	gchar* _tmp0_;
	gchar* command;
	gchar** _tmp1_;
	gchar** _tmp2_ = NULL;
	gchar** create_command;
	gint create_command_length1;
	gint _create_command_size_;
	gchar* _tmp3_;
	gchar* standard_output;
	gchar* _tmp4_;
	gchar* standard_error;
	gchar** updates_num = NULL;
	gint updates_num_length1 = 0;
	gint _updates_num_size_ = 0;
	gint exit_status = 0;
	const gchar* _tmp11_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup ("/usr/bin/nice" " " "/usr/bin/ionice" " " "-c3" " " "/usr/lib/update-notifier/apt-check");
	command = _tmp0_;
	_tmp2_ = _tmp1_ = g_strsplit_set (command, " ", 0);
	create_command = _tmp2_;
	create_command_length1 = _vala_array_length (_tmp1_);
	_create_command_size_ = create_command_length1;
	_tmp3_ = g_strdup ("");
	standard_output = _tmp3_;
	_tmp4_ = g_strdup ("");
	standard_error = _tmp4_;
	{
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		gint _tmp7_ = 0;
		const gchar* _tmp8_;
		g_spawn_sync (NULL, create_command, NULL, G_SPAWN_STDOUT_TO_DEV_NULL, NULL, NULL, &_tmp5_, &_tmp6_, &_tmp7_, &_inner_error_);
		_g_free0 (standard_output);
		standard_output = _tmp5_;
		_g_free0 (standard_error);
		standard_error = _tmp6_;
		exit_status = _tmp7_;
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_SPAWN_ERROR) {
				goto __catch22_g_spawn_error;
			}
			updates_num = (_vala_array_free (updates_num, updates_num_length1, (GDestroyNotify) g_free), NULL);
			_g_free0 (standard_error);
			_g_free0 (standard_output);
			create_command = (_vala_array_free (create_command, create_command_length1, (GDestroyNotify) g_free), NULL);
			_g_free0 (command);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
		g_message ("options.vala:287: Launching %s", command);
		_tmp8_ = standard_error;
		g_message ("options.vala:288: Update state: %s", _tmp8_);
		g_message ("options.vala:289: Update exit status: %i", exit_status);
	}
	goto __finally22;
	__catch22_g_spawn_error:
	{
		GError* err = NULL;
		GError* _tmp9_;
		const gchar* _tmp10_;
		err = _inner_error_;
		_inner_error_ = NULL;
		_tmp9_ = err;
		_tmp10_ = _tmp9_->message;
		g_warning ("options.vala:294: %s", _tmp10_);
		_g_error_free0 (err);
	}
	__finally22:
	if (_inner_error_ != NULL) {
		updates_num = (_vala_array_free (updates_num, updates_num_length1, (GDestroyNotify) g_free), NULL);
		_g_free0 (standard_error);
		_g_free0 (standard_output);
		create_command = (_vala_array_free (create_command, create_command_length1, (GDestroyNotify) g_free), NULL);
		_g_free0 (command);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp11_ = standard_error;
	if (g_strcmp0 (_tmp11_, "") != 0) {
		const gchar* _tmp12_;
		gchar** _tmp13_;
		gchar** _tmp14_ = NULL;
		gchar** _tmp15_;
		gint _tmp15__length1;
		const gchar* _tmp16_;
		gchar** _tmp17_;
		gint _tmp17__length1;
		const gchar* _tmp18_;
		_tmp12_ = standard_error;
		_tmp14_ = _tmp13_ = g_strsplit_set (_tmp12_, ";", 2);
		updates_num = (_vala_array_free (updates_num, updates_num_length1, (GDestroyNotify) g_free), NULL);
		updates_num = _tmp14_;
		updates_num_length1 = _vala_array_length (_tmp13_);
		_updates_num_size_ = updates_num_length1;
		_tmp15_ = updates_num;
		_tmp15__length1 = updates_num_length1;
		_tmp16_ = _tmp15_[0];
		g_message ("options.vala:300: Number of upgrades: %s", _tmp16_);
		_tmp17_ = updates_num;
		_tmp17__length1 = updates_num_length1;
		_tmp18_ = _tmp17_[1];
		g_message ("options.vala:301: Number of security upgrades: %s", _tmp18_);
	}
	updates_num = (_vala_array_free (updates_num, updates_num_length1, (GDestroyNotify) g_free), NULL);
	_g_free0 (standard_error);
	_g_free0 (standard_output);
	create_command = (_vala_array_free (create_command, create_command_length1, (GDestroyNotify) g_free), NULL);
	_g_free0 (command);
}


static void _lxsession_updates_option_on_apt_update_file_change_g_file_monitor_changed (GFileMonitor* _sender, GFile* file, GFile* other_file, GFileMonitorEvent event_type, gpointer self) {
	lxsession_updates_option_on_apt_update_file_change (self);
}


void lxsession_updates_option_setup_apt_config (LxsessionUpdatesOption* self) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	{
		gchar* _tmp0_;
		gchar* apt_update_path;
		GFile* apt_update_file = NULL;
		GFileMonitor* apt_update_monitor = NULL;
		GFile* _tmp1_ = NULL;
		GFileMonitor* _tmp2_ = NULL;
		GFileMonitor* _tmp3_;
		GFileMonitor* _tmp4_;
		_tmp0_ = g_strdup ("/var/lib/apt/periodic/update-success-stamp");
		apt_update_path = _tmp0_;
		_tmp1_ = g_file_new_for_path (apt_update_path);
		_g_object_unref0 (apt_update_file);
		apt_update_file = _tmp1_;
		_tmp2_ = g_file_monitor_file (apt_update_file, G_FILE_MONITOR_NONE, NULL, &_inner_error_);
		_tmp3_ = _tmp2_;
		if (_inner_error_ != NULL) {
			_g_object_unref0 (apt_update_monitor);
			_g_object_unref0 (apt_update_file);
			_g_free0 (apt_update_path);
			goto __catch23_g_error;
		}
		_g_object_unref0 (apt_update_monitor);
		apt_update_monitor = _tmp3_;
		_tmp4_ = apt_update_monitor;
		g_signal_connect_object (_tmp4_, "changed", (GCallback) _lxsession_updates_option_on_apt_update_file_change_g_file_monitor_changed, self, 0);
		g_message ("options.vala:316: Monitoring apt changes");
		_g_object_unref0 (apt_update_monitor);
		_g_object_unref0 (apt_update_file);
		_g_free0 (apt_update_path);
	}
	goto __finally23;
	__catch23_g_error:
	{
		GError* err = NULL;
		GError* _tmp5_;
		const gchar* _tmp6_;
		err = _inner_error_;
		_inner_error_ = NULL;
		_tmp5_ = err;
		_tmp6_ = _tmp5_->message;
		g_message ("options.vala:320: %s", _tmp6_);
		_g_error_free0 (err);
	}
	__finally23:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void lxsession_updates_option_class_init (LxsessionUpdatesOptionClass * klass) {
	lxsession_updates_option_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (LxsessionUpdatesOptionPrivate));
	G_OBJECT_CLASS (klass)->finalize = lxsession_updates_option_finalize;
}


static void lxsession_updates_option_instance_init (LxsessionUpdatesOption * self) {
	self->priv = LXSESSION_UPDATES_OPTION_GET_PRIVATE (self);
}


static void lxsession_updates_option_finalize (GObject* obj) {
	LxsessionUpdatesOption * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, LXSESSION_TYPE_UPDATES_OPTION, LxsessionUpdatesOption);
	_g_free0 (self->priv->command1);
	G_OBJECT_CLASS (lxsession_updates_option_parent_class)->finalize (obj);
}


GType lxsession_updates_option_get_type (void) {
	static volatile gsize lxsession_updates_option_type_id__volatile = 0;
	if (g_once_init_enter (&lxsession_updates_option_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LxsessionUpdatesOptionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) lxsession_updates_option_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LxsessionUpdatesOption), 0, (GInstanceInitFunc) lxsession_updates_option_instance_init, NULL };
		GType lxsession_updates_option_type_id;
		lxsession_updates_option_type_id = g_type_register_static (LXSESSION_TYPE_OPTION, "LxsessionUpdatesOption", &g_define_type_info, 0);
		g_once_init_leave (&lxsession_updates_option_type_id__volatile, lxsession_updates_option_type_id);
	}
	return lxsession_updates_option_type_id__volatile;
}


LxsessionUpstartUserSessionOption* lxsession_upstart_user_session_option_construct (GType object_type, LxsessionLxsessionConfig* config) {
	LxsessionUpstartUserSessionOption * self = NULL;
	LxsessionLxsessionConfig* _tmp0_;
	LxsessionLxsessionConfig* _tmp1_;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	g_return_val_if_fail (config != NULL, NULL);
	_tmp0_ = config;
	self = (LxsessionUpstartUserSessionOption*) lxsession_option_construct (object_type, _tmp0_);
	_tmp1_ = config;
	_tmp2_ = lxsession_lxsession_config_get_upstart_user_session (_tmp1_);
	_tmp3_ = _tmp2_;
	if (g_strcmp0 (_tmp3_, "true") == 0) {
		gchar* _tmp4_;
		_tmp4_ = g_strdup ("init --user");
		_g_free0 (self->priv->command1);
		self->priv->command1 = _tmp4_;
	}
	return self;
}


LxsessionUpstartUserSessionOption* lxsession_upstart_user_session_option_new (LxsessionLxsessionConfig* config) {
	return lxsession_upstart_user_session_option_construct (LXSESSION_TYPE_UPSTART_USER_SESSION_OPTION, config);
}


void lxsession_upstart_user_session_option_activate (LxsessionUpstartUserSessionOption* self) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	{
		const gchar* _tmp0_;
		_tmp0_ = self->priv->command1;
		g_spawn_command_line_async (_tmp0_, &_inner_error_);
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_SPAWN_ERROR) {
				goto __catch24_g_spawn_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	goto __finally24;
	__catch24_g_spawn_error:
	{
		GError* err = NULL;
		GError* _tmp1_;
		const gchar* _tmp2_;
		err = _inner_error_;
		_inner_error_ = NULL;
		_tmp1_ = err;
		_tmp2_ = _tmp1_->message;
		g_warning ("options.vala:345: %s", _tmp2_);
		_g_error_free0 (err);
	}
	__finally24:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void lxsession_upstart_user_session_option_class_init (LxsessionUpstartUserSessionOptionClass * klass) {
	lxsession_upstart_user_session_option_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (LxsessionUpstartUserSessionOptionPrivate));
	G_OBJECT_CLASS (klass)->finalize = lxsession_upstart_user_session_option_finalize;
}


static void lxsession_upstart_user_session_option_instance_init (LxsessionUpstartUserSessionOption * self) {
	self->priv = LXSESSION_UPSTART_USER_SESSION_OPTION_GET_PRIVATE (self);
}


static void lxsession_upstart_user_session_option_finalize (GObject* obj) {
	LxsessionUpstartUserSessionOption * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, LXSESSION_TYPE_UPSTART_USER_SESSION_OPTION, LxsessionUpstartUserSessionOption);
	_g_free0 (self->priv->command1);
	G_OBJECT_CLASS (lxsession_upstart_user_session_option_parent_class)->finalize (obj);
}


GType lxsession_upstart_user_session_option_get_type (void) {
	static volatile gsize lxsession_upstart_user_session_option_type_id__volatile = 0;
	if (g_once_init_enter (&lxsession_upstart_user_session_option_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LxsessionUpstartUserSessionOptionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) lxsession_upstart_user_session_option_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LxsessionUpstartUserSessionOption), 0, (GInstanceInitFunc) lxsession_upstart_user_session_option_instance_init, NULL };
		GType lxsession_upstart_user_session_option_type_id;
		lxsession_upstart_user_session_option_type_id = g_type_register_static (LXSESSION_TYPE_OPTION, "LxsessionUpstartUserSessionOption", &g_define_type_info, 0);
		g_once_init_leave (&lxsession_upstart_user_session_option_type_id__volatile, lxsession_upstart_user_session_option_type_id);
	}
	return lxsession_upstart_user_session_option_type_id__volatile;
}


LxsessionProxyOption* lxsession_proxy_option_construct (GType object_type, LxsessionLxsessionConfig* config) {
	LxsessionProxyOption * self = NULL;
	LxsessionLxsessionConfig* _tmp0_;
	g_return_val_if_fail (config != NULL, NULL);
	_tmp0_ = config;
	self = (LxsessionProxyOption*) lxsession_option_construct (object_type, _tmp0_);
	return self;
}


LxsessionProxyOption* lxsession_proxy_option_new (LxsessionLxsessionConfig* config) {
	return lxsession_proxy_option_construct (LXSESSION_TYPE_PROXY_OPTION, config);
}


void lxsession_proxy_option_activate (LxsessionProxyOption* self) {
	LxsessionLxsessionConfigKeyFile* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	GQuark _tmp7_ = 0U;
	static GQuark _tmp6_label0 = 0;
	static GQuark _tmp6_label1 = 0;
	static GQuark _tmp6_label2 = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = lxsession_global_settings;
	_tmp1_ = lxsession_lxsession_config_get_proxy_http ((LxsessionLxsessionConfig*) _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_strdup (_tmp2_);
	_g_free0 (self->priv->http);
	self->priv->http = _tmp3_;
	_tmp4_ = self->priv->http;
	_tmp5_ = _tmp4_;
	_tmp7_ = (NULL == _tmp5_) ? 0 : g_quark_from_string (_tmp5_);
	if (_tmp7_ == ((0 != _tmp6_label0) ? _tmp6_label0 : (_tmp6_label0 = g_quark_from_static_string (NULL)))) {
		switch (0) {
			default:
			{
				break;
			}
		}
	} else if (_tmp7_ == ((0 != _tmp6_label1) ? _tmp6_label1 : (_tmp6_label1 = g_quark_from_static_string ("")))) {
		switch (0) {
			default:
			{
				break;
			}
		}
	} else if (_tmp7_ == ((0 != _tmp6_label2) ? _tmp6_label2 : (_tmp6_label2 = g_quark_from_static_string (" ")))) {
		switch (0) {
			default:
			{
				break;
			}
		}
	} else {
		switch (0) {
			default:
			{
				const gchar* _tmp8_;
				_tmp8_ = self->priv->http;
				g_setenv ("HTTP_PROXY", _tmp8_, TRUE);
				break;
			}
		}
	}
}


static void lxsession_proxy_option_class_init (LxsessionProxyOptionClass * klass) {
	lxsession_proxy_option_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (LxsessionProxyOptionPrivate));
	G_OBJECT_CLASS (klass)->finalize = lxsession_proxy_option_finalize;
}


static void lxsession_proxy_option_instance_init (LxsessionProxyOption * self) {
	self->priv = LXSESSION_PROXY_OPTION_GET_PRIVATE (self);
}


static void lxsession_proxy_option_finalize (GObject* obj) {
	LxsessionProxyOption * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, LXSESSION_TYPE_PROXY_OPTION, LxsessionProxyOption);
	_g_free0 (self->priv->http);
	G_OBJECT_CLASS (lxsession_proxy_option_parent_class)->finalize (obj);
}


GType lxsession_proxy_option_get_type (void) {
	static volatile gsize lxsession_proxy_option_type_id__volatile = 0;
	if (g_once_init_enter (&lxsession_proxy_option_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LxsessionProxyOptionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) lxsession_proxy_option_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LxsessionProxyOption), 0, (GInstanceInitFunc) lxsession_proxy_option_instance_init, NULL };
		GType lxsession_proxy_option_type_id;
		lxsession_proxy_option_type_id = g_type_register_static (LXSESSION_TYPE_OPTION, "LxsessionProxyOption", &g_define_type_info, 0);
		g_once_init_leave (&lxsession_proxy_option_type_id__volatile, lxsession_proxy_option_type_id);
	}
	return lxsession_proxy_option_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



